// Code generated by internal/gen; DO NOT EDIT.

package pumpamm

type ProgramError struct {
	Code uint32
	Name string
	Msg  string
}

var Errors = map[uint32]ProgramError{
	6000: {Code: 6000, Name: "FeeBasisPointsExceedsMaximum", Msg: ""},
	6001: {Code: 6001, Name: "ZeroBaseAmount", Msg: ""},
	6002: {Code: 6002, Name: "ZeroQuoteAmount", Msg: ""},
	6003: {Code: 6003, Name: "TooLittlePoolTokenLiquidity", Msg: ""},
	6004: {Code: 6004, Name: "ExceededSlippage", Msg: ""},
	6005: {Code: 6005, Name: "InvalidAdmin", Msg: ""},
	6006: {Code: 6006, Name: "UnsupportedBaseMint", Msg: ""},
	6007: {Code: 6007, Name: "UnsupportedQuoteMint", Msg: ""},
	6008: {Code: 6008, Name: "InvalidBaseMint", Msg: ""},
	6009: {Code: 6009, Name: "InvalidQuoteMint", Msg: ""},
	6010: {Code: 6010, Name: "InvalidLpMint", Msg: ""},
	6011: {Code: 6011, Name: "AllProtocolFeeRecipientsShouldBeNonZero", Msg: ""},
	6012: {Code: 6012, Name: "UnsortedNotUniqueProtocolFeeRecipients", Msg: ""},
	6013: {Code: 6013, Name: "InvalidProtocolFeeRecipient", Msg: ""},
	6014: {Code: 6014, Name: "InvalidPoolBaseTokenAccount", Msg: ""},
	6015: {Code: 6015, Name: "InvalidPoolQuoteTokenAccount", Msg: ""},
	6016: {Code: 6016, Name: "BuyMoreBaseAmountThanPoolReserves", Msg: ""},
	6017: {Code: 6017, Name: "DisabledCreatePool", Msg: ""},
	6018: {Code: 6018, Name: "DisabledDeposit", Msg: ""},
	6019: {Code: 6019, Name: "DisabledWithdraw", Msg: ""},
	6020: {Code: 6020, Name: "DisabledBuy", Msg: ""},
	6021: {Code: 6021, Name: "DisabledSell", Msg: ""},
	6022: {Code: 6022, Name: "SameMint", Msg: ""},
	6023: {Code: 6023, Name: "Overflow", Msg: ""},
	6024: {Code: 6024, Name: "Truncation", Msg: ""},
	6025: {Code: 6025, Name: "DivisionByZero", Msg: ""},
	6026: {Code: 6026, Name: "NewSizeLessThanCurrentSize", Msg: ""},
	6027: {Code: 6027, Name: "AccountTypeNotSupported", Msg: ""},
	6028: {Code: 6028, Name: "OnlyCanonicalPumpPoolsCanHaveCoinCreator", Msg: ""},
	6029: {Code: 6029, Name: "InvalidAdminSetCoinCreatorAuthority", Msg: ""},
	6030: {Code: 6030, Name: "StartTimeInThePast", Msg: ""},
	6031: {Code: 6031, Name: "EndTimeInThePast", Msg: ""},
	6032: {Code: 6032, Name: "EndTimeBeforeStartTime", Msg: ""},
	6033: {Code: 6033, Name: "TimeRangeTooLarge", Msg: ""},
	6034: {Code: 6034, Name: "EndTimeBeforeCurrentDay", Msg: ""},
	6035: {Code: 6035, Name: "SupplyUpdateForFinishedRange", Msg: ""},
	6036: {Code: 6036, Name: "DayIndexAfterEndIndex", Msg: ""},
	6037: {Code: 6037, Name: "DayInActiveRange", Msg: ""},
	6038: {Code: 6038, Name: "InvalidIncentiveMint", Msg: ""},
	6039: {Code: 6039, Name: "BuyNotEnoughQuoteTokensToCoverFees", Msg: "buy: Not enough quote tokens to cover for fees."},
	6040: {Code: 6040, Name: "BuySlippageBelowMinBaseAmountOut", Msg: "buy: slippage - would buy less tokens than expected min_base_amount_out"},
	6041: {Code: 6041, Name: "MayhemModeDisabled", Msg: ""},
	6042: {Code: 6042, Name: "OnlyPumpPoolsMayhemMode", Msg: ""},
	6043: {Code: 6043, Name: "MayhemModeInDesiredState", Msg: ""},
	6044: {Code: 6044, Name: "NotEnoughRemainingAccounts", Msg: ""},
	6045: {Code: 6045, Name: "InvalidSharingConfigBaseMint", Msg: ""},
	6046: {Code: 6046, Name: "InvalidSharingConfigCoinCreator", Msg: ""},
	6047: {Code: 6047, Name: "CoinCreatorMigratedToSharingConfig", Msg: "coin creator has been migrated to sharing config, use pump_fees::reset_fee_sharing_config instead"},
	6048: {Code: 6048, Name: "CreatorVaultMigratedToSharingConfig", Msg: "creator_vault has been migrated to sharing config, use pump:distribute_creator_fees instead"},
	6049: {Code: 6049, Name: "CashbackNotEnabled", Msg: "Cashback is disabled"},
	6050: {Code: 6050, Name: "OnlyPumpPoolsCashback", Msg: ""},
	6051: {Code: 6051, Name: "CashbackNotInDesiredState", Msg: ""},
	6052: {Code: 6052, Name: "TokensInVaultLessThanCashbackEarned", Msg: ""},
	6053: {Code: 6053, Name: "BuybackFeeRecipientNotAuthorized", Msg: "Buyback fee recipient not authorized"},
	6054: {Code: 6054, Name: "AllBuybackFeeRecipientsShouldBeNonZero", Msg: ""},
	6055: {Code: 6055, Name: "NotUniqueBuybackFeeRecipients", Msg: ""},
	6056: {Code: 6056, Name: "BuybackBasisPointsOutOfRange", Msg: "buyback_basis_points must be <= 10_000"},
	6057: {Code: 6057, Name: "WrongBuybackFeeRecipientsCount", Msg: "buyback fee recipients require exactly 8 remaining accounts (or none)"},
	6058: {Code: 6058, Name: "BuybackFeeRecipientMissing", Msg: ""},
	6059: {Code: 6059, Name: "MissingCashbackAccounts", Msg: "Cashback trade is missing the required remaining accounts"},
	6060: {Code: 6060, Name: "InvalidCashbackAccumulator", Msg: "Cashback user_volume_accumulator account is invalid"},
	6061: {Code: 6061, Name: "InvalidCashbackAccumulatorAta", Msg: "Cashback user_volume_accumulator ATA is missing or invalid"},
	6062: {Code: 6062, Name: "InvalidPoolV2", Msg: "pool_v2 remaining account is missing or invalid"},
	6063: {Code: 6063, Name: "InsufficientRealQuoteReserves", Msg: "BOOST: sell output exceeds the real quote vault. effective = real + virtual is pricing-only; payout is capped at real_vault, so quote min(out, real_vault)"},
	6064: {Code: 6064, Name: "BoostPoolLiquidityUnsupported", Msg: "BOOST: deposit/withdraw don't apply to boost pools"},
	6065: {Code: 6065, Name: "PoolCannotBoost", Msg: "BOOST: pool cannot be boosted (no virtual reserves)"},
	6066: {Code: 6066, Name: "BoostDisabled", Msg: "BOOST: boost is disabled"},
	6067: {Code: 6067, Name: "SeedLockViolation", Msg: "BOOST: lp_supply must never drop below the circulating LP mint supply"},
}

func ErrorFromCode(code uint32) (ProgramError, bool) {
	err, ok := Errors[code]
	return err, ok
}
