// Code generated by internal/gen; DO NOT EDIT.
// Generated at 2025-12-07T17:54:49Z

package pumpamm

import (
	"bytes"
	"encoding/binary"
	"fmt"

	bin "github.com/gagliardetto/binary"
	"github.com/gagliardetto/solana-go"
)

var AdminSetCoinCreatorDiscriminator = []byte{242, 40, 117, 145, 73, 96, 105, 104}

type AdminSetCoinCreatorArgs struct {
	CoinCreator solana.PublicKey `bin:"coin_creator"`
}

type AdminSetCoinCreatorAccounts struct {
	AdminSetCoinCreatorAuthority solana.PublicKey
	GlobalConfig                 solana.PublicKey
	Pool                         solana.PublicKey
	EventAuthority               solana.PublicKey
	Program                      solana.PublicKey
}

func (a AdminSetCoinCreatorAccounts) ToAccountMetas() []*solana.AccountMeta {
	metas := make([]*solana.AccountMeta, 0, 5)
	metas = append(metas, solana.NewAccountMeta(a.AdminSetCoinCreatorAuthority, false, true))
	metas = append(metas, solana.NewAccountMeta(a.GlobalConfig, false, false))
	metas = append(metas, solana.NewAccountMeta(a.Pool, true, false))
	metas = append(metas, solana.NewAccountMeta(a.EventAuthority, false, false))
	metas = append(metas, solana.NewAccountMeta(a.Program, false, false))
	return metas
}

func BuildAdminSetCoinCreator(accounts AdminSetCoinCreatorAccounts, args AdminSetCoinCreatorArgs) (solana.Instruction, error) {
	buf := bytes.NewBuffer(make([]byte, 0, 128))
	buf.Write(AdminSetCoinCreatorDiscriminator)
	if err := bin.NewBorshEncoder(buf).Encode(args); err != nil {
		return nil, fmt.Errorf("encode args: %w", err)
	}
	data := buf.Bytes()
	return solana.NewInstruction(ProgramKey, accounts.ToAccountMetas(), data), nil
}

func DeriveAdminSetCoinCreatorEventAuthorityPDA(accounts AdminSetCoinCreatorAccounts, args AdminSetCoinCreatorArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 1)
	seeds = append(seeds, []byte{95, 95, 101, 118, 101, 110, 116, 95, 97, 117, 116, 104, 111, 114, 105, 116, 121})
	return solana.FindProgramAddress(seeds, ProgramKey)
}

var AdminUpdateTokenIncentivesDiscriminator = []byte{209, 11, 115, 87, 213, 23, 124, 204}

type AdminUpdateTokenIncentivesArgs struct {
	StartTime         int64  `bin:"start_time"`
	EndTime           int64  `bin:"end_time"`
	SecondsInADay     int64  `bin:"seconds_in_a_day"`
	DayNumber         uint64 `bin:"day_number"`
	TokenSupplyPerDay uint64 `bin:"token_supply_per_day"`
}

type AdminUpdateTokenIncentivesAccounts struct {
	Admin                       solana.PublicKey
	GlobalConfig                solana.PublicKey
	GlobalVolumeAccumulator     solana.PublicKey
	Mint                        solana.PublicKey
	GlobalIncentiveTokenAccount solana.PublicKey
	AssociatedTokenProgram      solana.PublicKey
	SystemProgram               solana.PublicKey
	TokenProgram                solana.PublicKey
	EventAuthority              solana.PublicKey
	Program                     solana.PublicKey
}

func (a AdminUpdateTokenIncentivesAccounts) ToAccountMetas() []*solana.AccountMeta {
	metas := make([]*solana.AccountMeta, 0, 10)
	metas = append(metas, solana.NewAccountMeta(a.Admin, true, true))
	metas = append(metas, solana.NewAccountMeta(a.GlobalConfig, false, false))
	metas = append(metas, solana.NewAccountMeta(a.GlobalVolumeAccumulator, true, false))
	metas = append(metas, solana.NewAccountMeta(a.Mint, false, false))
	metas = append(metas, solana.NewAccountMeta(a.GlobalIncentiveTokenAccount, true, false))
	var defaultAdminUpdateTokenIncentivesAssociatedTokenProgram = func() solana.PublicKey {
		return solana.MustPublicKeyFromBase58("ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL")
	}

	metas = append(metas, solana.NewAccountMeta(defaultAdminUpdateTokenIncentivesAssociatedTokenProgram(), false, false))
	var defaultAdminUpdateTokenIncentivesSystemProgram = func() solana.PublicKey {
		return solana.MustPublicKeyFromBase58("11111111111111111111111111111111")
	}

	metas = append(metas, solana.NewAccountMeta(defaultAdminUpdateTokenIncentivesSystemProgram(), false, false))
	metas = append(metas, solana.NewAccountMeta(a.TokenProgram, false, false))
	metas = append(metas, solana.NewAccountMeta(a.EventAuthority, false, false))
	metas = append(metas, solana.NewAccountMeta(a.Program, false, false))
	return metas
}

func BuildAdminUpdateTokenIncentives(accounts AdminUpdateTokenIncentivesAccounts, args AdminUpdateTokenIncentivesArgs) (solana.Instruction, error) {
	buf := bytes.NewBuffer(make([]byte, 0, 128))
	buf.Write(AdminUpdateTokenIncentivesDiscriminator)
	if err := bin.NewBorshEncoder(buf).Encode(args); err != nil {
		return nil, fmt.Errorf("encode args: %w", err)
	}
	data := buf.Bytes()
	return solana.NewInstruction(ProgramKey, accounts.ToAccountMetas(), data), nil
}

func DeriveAdminUpdateTokenIncentivesGlobalConfigPDA(accounts AdminUpdateTokenIncentivesAccounts, args AdminUpdateTokenIncentivesArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 1)
	seeds = append(seeds, []byte{103, 108, 111, 98, 97, 108, 95, 99, 111, 110, 102, 105, 103})
	return solana.FindProgramAddress(seeds, ProgramKey)
}

func DeriveAdminUpdateTokenIncentivesGlobalVolumeAccumulatorPDA(accounts AdminUpdateTokenIncentivesAccounts, args AdminUpdateTokenIncentivesArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 1)
	seeds = append(seeds, []byte{103, 108, 111, 98, 97, 108, 95, 118, 111, 108, 117, 109, 101, 95, 97, 99, 99, 117, 109, 117, 108, 97, 116, 111, 114})
	return solana.FindProgramAddress(seeds, ProgramKey)
}

func DeriveAdminUpdateTokenIncentivesGlobalIncentiveTokenAccountPDA(accounts AdminUpdateTokenIncentivesAccounts, args AdminUpdateTokenIncentivesArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 3)
	seeds = append(seeds, accounts.GlobalVolumeAccumulator[:])
	seeds = append(seeds, accounts.TokenProgram[:])
	seeds = append(seeds, accounts.Mint[:])
	return solana.FindProgramAddress(seeds, solana.PublicKeyFromBytes([]byte{140, 151, 37, 143, 78, 36, 137, 241, 187, 61, 16, 41, 20, 142, 13, 131, 11, 90, 19, 153, 218, 255, 16, 132, 4, 142, 123, 216, 219, 233, 248, 89}))
}

func DeriveAdminUpdateTokenIncentivesEventAuthorityPDA(accounts AdminUpdateTokenIncentivesAccounts, args AdminUpdateTokenIncentivesArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 1)
	seeds = append(seeds, []byte{95, 95, 101, 118, 101, 110, 116, 95, 97, 117, 116, 104, 111, 114, 105, 116, 121})
	return solana.FindProgramAddress(seeds, ProgramKey)
}

var BuyDiscriminator = []byte{102, 6, 61, 18, 1, 218, 235, 234}

type BuyArgs struct {
	BaseAmountOut    uint64     `bin:"base_amount_out"`
	MaxQuoteAmountIn uint64     `bin:"max_quote_amount_in"`
	TrackVolume      OptionBool `bin:"track_volume"`
}

type BuyAccounts struct {
	Pool                             solana.PublicKey
	User                             solana.PublicKey
	GlobalConfig                     solana.PublicKey
	BaseMint                         solana.PublicKey
	QuoteMint                        solana.PublicKey
	UserBaseTokenAccount             solana.PublicKey
	UserQuoteTokenAccount            solana.PublicKey
	PoolBaseTokenAccount             solana.PublicKey
	PoolQuoteTokenAccount            solana.PublicKey
	ProtocolFeeRecipient             solana.PublicKey
	ProtocolFeeRecipientTokenAccount solana.PublicKey
	BaseTokenProgram                 solana.PublicKey
	QuoteTokenProgram                solana.PublicKey
	SystemProgram                    solana.PublicKey
	AssociatedTokenProgram           solana.PublicKey
	EventAuthority                   solana.PublicKey
	Program                          solana.PublicKey
	CoinCreatorVaultAta              solana.PublicKey
	CoinCreatorVaultAuthority        solana.PublicKey
	GlobalVolumeAccumulator          solana.PublicKey
	UserVolumeAccumulator            solana.PublicKey
	FeeConfig                        solana.PublicKey
	FeeProgram                       solana.PublicKey
}

func (a BuyAccounts) ToAccountMetas() []*solana.AccountMeta {
	metas := make([]*solana.AccountMeta, 0, 23)
	metas = append(metas, solana.NewAccountMeta(a.Pool, true, false))
	metas = append(metas, solana.NewAccountMeta(a.User, true, true))
	metas = append(metas, solana.NewAccountMeta(a.GlobalConfig, false, false))
	metas = append(metas, solana.NewAccountMeta(a.BaseMint, false, false))
	metas = append(metas, solana.NewAccountMeta(a.QuoteMint, false, false))
	metas = append(metas, solana.NewAccountMeta(a.UserBaseTokenAccount, true, false))
	metas = append(metas, solana.NewAccountMeta(a.UserQuoteTokenAccount, true, false))
	metas = append(metas, solana.NewAccountMeta(a.PoolBaseTokenAccount, true, false))
	metas = append(metas, solana.NewAccountMeta(a.PoolQuoteTokenAccount, true, false))
	metas = append(metas, solana.NewAccountMeta(a.ProtocolFeeRecipient, false, false))
	metas = append(metas, solana.NewAccountMeta(a.ProtocolFeeRecipientTokenAccount, true, false))
	metas = append(metas, solana.NewAccountMeta(a.BaseTokenProgram, false, false))
	metas = append(metas, solana.NewAccountMeta(a.QuoteTokenProgram, false, false))
	var defaultBuySystemProgram = func() solana.PublicKey {
		return solana.MustPublicKeyFromBase58("11111111111111111111111111111111")
	}

	metas = append(metas, solana.NewAccountMeta(defaultBuySystemProgram(), false, false))
	var defaultBuyAssociatedTokenProgram = func() solana.PublicKey {
		return solana.MustPublicKeyFromBase58("ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL")
	}

	metas = append(metas, solana.NewAccountMeta(defaultBuyAssociatedTokenProgram(), false, false))
	metas = append(metas, solana.NewAccountMeta(a.EventAuthority, false, false))
	var defaultBuyProgram = func() solana.PublicKey {
		return solana.MustPublicKeyFromBase58("pAMMBay6oceH9fJKBRHGP5D4bD4sWpmSwMn52FMfXEA")
	}

	metas = append(metas, solana.NewAccountMeta(defaultBuyProgram(), false, false))
	metas = append(metas, solana.NewAccountMeta(a.CoinCreatorVaultAta, true, false))
	metas = append(metas, solana.NewAccountMeta(a.CoinCreatorVaultAuthority, false, false))
	metas = append(metas, solana.NewAccountMeta(a.GlobalVolumeAccumulator, false, false))
	metas = append(metas, solana.NewAccountMeta(a.UserVolumeAccumulator, true, false))
	metas = append(metas, solana.NewAccountMeta(a.FeeConfig, false, false))
	var defaultBuyFeeProgram = func() solana.PublicKey {
		return solana.MustPublicKeyFromBase58("pfeeUxB6jkeY1Hxd7CsFCAjcbHA9rWtchMGdZ6VojVZ")
	}

	metas = append(metas, solana.NewAccountMeta(defaultBuyFeeProgram(), false, false))
	return metas
}

func BuildBuy(accounts BuyAccounts, args BuyArgs) (solana.Instruction, error) {
	buf := bytes.NewBuffer(make([]byte, 0, 128))
	buf.Write(BuyDiscriminator)
	if err := bin.NewBorshEncoder(buf).Encode(args); err != nil {
		return nil, fmt.Errorf("encode args: %w", err)
	}
	data := buf.Bytes()
	return solana.NewInstruction(ProgramKey, accounts.ToAccountMetas(), data), nil
}

func DeriveBuyProtocolFeeRecipientTokenAccountPDA(accounts BuyAccounts, args BuyArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 3)
	seeds = append(seeds, accounts.ProtocolFeeRecipient[:])
	seeds = append(seeds, accounts.QuoteTokenProgram[:])
	seeds = append(seeds, accounts.QuoteMint[:])
	return solana.FindProgramAddress(seeds, solana.PublicKeyFromBytes([]byte{140, 151, 37, 143, 78, 36, 137, 241, 187, 61, 16, 41, 20, 142, 13, 131, 11, 90, 19, 153, 218, 255, 16, 132, 4, 142, 123, 216, 219, 233, 248, 89}))
}

func DeriveBuyEventAuthorityPDA(accounts BuyAccounts, args BuyArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 1)
	seeds = append(seeds, []byte{95, 95, 101, 118, 101, 110, 116, 95, 97, 117, 116, 104, 111, 114, 105, 116, 121})
	return solana.FindProgramAddress(seeds, ProgramKey)
}

func DeriveBuyCoinCreatorVaultAtaPDA(accounts BuyAccounts, args BuyArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 3)
	seeds = append(seeds, accounts.CoinCreatorVaultAuthority[:])
	seeds = append(seeds, accounts.QuoteTokenProgram[:])
	seeds = append(seeds, accounts.QuoteMint[:])
	return solana.FindProgramAddress(seeds, solana.PublicKeyFromBytes([]byte{140, 151, 37, 143, 78, 36, 137, 241, 187, 61, 16, 41, 20, 142, 13, 131, 11, 90, 19, 153, 218, 255, 16, 132, 4, 142, 123, 216, 219, 233, 248, 89}))
}

func DeriveBuyCoinCreatorVaultAuthorityPDA(accounts BuyAccounts, args BuyArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 2)
	seeds = append(seeds, []byte{99, 114, 101, 97, 116, 111, 114, 95, 118, 97, 117, 108, 116})
	seeds = append(seeds, accounts.Pool[:])
	return solana.FindProgramAddress(seeds, ProgramKey)
}

func DeriveBuyGlobalVolumeAccumulatorPDA(accounts BuyAccounts, args BuyArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 1)
	seeds = append(seeds, []byte{103, 108, 111, 98, 97, 108, 95, 118, 111, 108, 117, 109, 101, 95, 97, 99, 99, 117, 109, 117, 108, 97, 116, 111, 114})
	return solana.FindProgramAddress(seeds, ProgramKey)
}

func DeriveBuyUserVolumeAccumulatorPDA(accounts BuyAccounts, args BuyArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 2)
	seeds = append(seeds, []byte{117, 115, 101, 114, 95, 118, 111, 108, 117, 109, 101, 95, 97, 99, 99, 117, 109, 117, 108, 97, 116, 111, 114})
	seeds = append(seeds, accounts.User[:])
	return solana.FindProgramAddress(seeds, ProgramKey)
}

func DeriveBuyFeeConfigPDA(accounts BuyAccounts, args BuyArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 2)
	seeds = append(seeds, []byte{102, 101, 101, 95, 99, 111, 110, 102, 105, 103})
	seeds = append(seeds, []byte{12, 20, 222, 252, 130, 94, 198, 118, 148, 37, 8, 24, 187, 101, 64, 101, 244, 41, 141, 49, 86, 213, 113, 180, 212, 248, 9, 12, 24, 233, 168, 99})
	return solana.FindProgramAddress(seeds, accounts.FeeProgram)
}

var BuyExactQuoteInDiscriminator = []byte{198, 46, 21, 82, 180, 217, 232, 112}

type BuyExactQuoteInArgs struct {
	SpendableQuoteIn uint64     `bin:"spendable_quote_in"`
	MinBaseAmountOut uint64     `bin:"min_base_amount_out"`
	TrackVolume      OptionBool `bin:"track_volume"`
}

type BuyExactQuoteInAccounts struct {
	Pool                             solana.PublicKey
	User                             solana.PublicKey
	GlobalConfig                     solana.PublicKey
	BaseMint                         solana.PublicKey
	QuoteMint                        solana.PublicKey
	UserBaseTokenAccount             solana.PublicKey
	UserQuoteTokenAccount            solana.PublicKey
	PoolBaseTokenAccount             solana.PublicKey
	PoolQuoteTokenAccount            solana.PublicKey
	ProtocolFeeRecipient             solana.PublicKey
	ProtocolFeeRecipientTokenAccount solana.PublicKey
	BaseTokenProgram                 solana.PublicKey
	QuoteTokenProgram                solana.PublicKey
	SystemProgram                    solana.PublicKey
	AssociatedTokenProgram           solana.PublicKey
	EventAuthority                   solana.PublicKey
	Program                          solana.PublicKey
	CoinCreatorVaultAta              solana.PublicKey
	CoinCreatorVaultAuthority        solana.PublicKey
	GlobalVolumeAccumulator          solana.PublicKey
	UserVolumeAccumulator            solana.PublicKey
	FeeConfig                        solana.PublicKey
	FeeProgram                       solana.PublicKey
}

func (a BuyExactQuoteInAccounts) ToAccountMetas() []*solana.AccountMeta {
	metas := make([]*solana.AccountMeta, 0, 23)
	metas = append(metas, solana.NewAccountMeta(a.Pool, true, false))
	metas = append(metas, solana.NewAccountMeta(a.User, true, true))
	metas = append(metas, solana.NewAccountMeta(a.GlobalConfig, false, false))
	metas = append(metas, solana.NewAccountMeta(a.BaseMint, false, false))
	metas = append(metas, solana.NewAccountMeta(a.QuoteMint, false, false))
	metas = append(metas, solana.NewAccountMeta(a.UserBaseTokenAccount, true, false))
	metas = append(metas, solana.NewAccountMeta(a.UserQuoteTokenAccount, true, false))
	metas = append(metas, solana.NewAccountMeta(a.PoolBaseTokenAccount, true, false))
	metas = append(metas, solana.NewAccountMeta(a.PoolQuoteTokenAccount, true, false))
	metas = append(metas, solana.NewAccountMeta(a.ProtocolFeeRecipient, false, false))
	metas = append(metas, solana.NewAccountMeta(a.ProtocolFeeRecipientTokenAccount, true, false))
	metas = append(metas, solana.NewAccountMeta(a.BaseTokenProgram, false, false))
	metas = append(metas, solana.NewAccountMeta(a.QuoteTokenProgram, false, false))
	var defaultBuyExactQuoteInSystemProgram = func() solana.PublicKey {
		return solana.MustPublicKeyFromBase58("11111111111111111111111111111111")
	}

	metas = append(metas, solana.NewAccountMeta(defaultBuyExactQuoteInSystemProgram(), false, false))
	var defaultBuyExactQuoteInAssociatedTokenProgram = func() solana.PublicKey {
		return solana.MustPublicKeyFromBase58("ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL")
	}

	metas = append(metas, solana.NewAccountMeta(defaultBuyExactQuoteInAssociatedTokenProgram(), false, false))
	metas = append(metas, solana.NewAccountMeta(a.EventAuthority, false, false))
	var defaultBuyExactQuoteInProgram = func() solana.PublicKey {
		return solana.MustPublicKeyFromBase58("pAMMBay6oceH9fJKBRHGP5D4bD4sWpmSwMn52FMfXEA")
	}

	metas = append(metas, solana.NewAccountMeta(defaultBuyExactQuoteInProgram(), false, false))
	metas = append(metas, solana.NewAccountMeta(a.CoinCreatorVaultAta, true, false))
	metas = append(metas, solana.NewAccountMeta(a.CoinCreatorVaultAuthority, false, false))
	metas = append(metas, solana.NewAccountMeta(a.GlobalVolumeAccumulator, false, false))
	metas = append(metas, solana.NewAccountMeta(a.UserVolumeAccumulator, true, false))
	metas = append(metas, solana.NewAccountMeta(a.FeeConfig, false, false))
	var defaultBuyExactQuoteInFeeProgram = func() solana.PublicKey {
		return solana.MustPublicKeyFromBase58("pfeeUxB6jkeY1Hxd7CsFCAjcbHA9rWtchMGdZ6VojVZ")
	}

	metas = append(metas, solana.NewAccountMeta(defaultBuyExactQuoteInFeeProgram(), false, false))
	return metas
}

func BuildBuyExactQuoteIn(accounts BuyExactQuoteInAccounts, args BuyExactQuoteInArgs) (solana.Instruction, error) {
	buf := bytes.NewBuffer(make([]byte, 0, 128))
	buf.Write(BuyExactQuoteInDiscriminator)
	if err := bin.NewBorshEncoder(buf).Encode(args); err != nil {
		return nil, fmt.Errorf("encode args: %w", err)
	}
	data := buf.Bytes()
	return solana.NewInstruction(ProgramKey, accounts.ToAccountMetas(), data), nil
}

func DeriveBuyExactQuoteInProtocolFeeRecipientTokenAccountPDA(accounts BuyExactQuoteInAccounts, args BuyExactQuoteInArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 3)
	seeds = append(seeds, accounts.ProtocolFeeRecipient[:])
	seeds = append(seeds, accounts.QuoteTokenProgram[:])
	seeds = append(seeds, accounts.QuoteMint[:])
	return solana.FindProgramAddress(seeds, solana.PublicKeyFromBytes([]byte{140, 151, 37, 143, 78, 36, 137, 241, 187, 61, 16, 41, 20, 142, 13, 131, 11, 90, 19, 153, 218, 255, 16, 132, 4, 142, 123, 216, 219, 233, 248, 89}))
}

func DeriveBuyExactQuoteInEventAuthorityPDA(accounts BuyExactQuoteInAccounts, args BuyExactQuoteInArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 1)
	seeds = append(seeds, []byte{95, 95, 101, 118, 101, 110, 116, 95, 97, 117, 116, 104, 111, 114, 105, 116, 121})
	return solana.FindProgramAddress(seeds, ProgramKey)
}

func DeriveBuyExactQuoteInCoinCreatorVaultAtaPDA(accounts BuyExactQuoteInAccounts, args BuyExactQuoteInArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 3)
	seeds = append(seeds, accounts.CoinCreatorVaultAuthority[:])
	seeds = append(seeds, accounts.QuoteTokenProgram[:])
	seeds = append(seeds, accounts.QuoteMint[:])
	return solana.FindProgramAddress(seeds, solana.PublicKeyFromBytes([]byte{140, 151, 37, 143, 78, 36, 137, 241, 187, 61, 16, 41, 20, 142, 13, 131, 11, 90, 19, 153, 218, 255, 16, 132, 4, 142, 123, 216, 219, 233, 248, 89}))
}

func DeriveBuyExactQuoteInCoinCreatorVaultAuthorityPDA(accounts BuyExactQuoteInAccounts, args BuyExactQuoteInArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 2)
	seeds = append(seeds, []byte{99, 114, 101, 97, 116, 111, 114, 95, 118, 97, 117, 108, 116})
	seeds = append(seeds, accounts.Pool[:])
	return solana.FindProgramAddress(seeds, ProgramKey)
}

func DeriveBuyExactQuoteInGlobalVolumeAccumulatorPDA(accounts BuyExactQuoteInAccounts, args BuyExactQuoteInArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 1)
	seeds = append(seeds, []byte{103, 108, 111, 98, 97, 108, 95, 118, 111, 108, 117, 109, 101, 95, 97, 99, 99, 117, 109, 117, 108, 97, 116, 111, 114})
	return solana.FindProgramAddress(seeds, ProgramKey)
}

func DeriveBuyExactQuoteInUserVolumeAccumulatorPDA(accounts BuyExactQuoteInAccounts, args BuyExactQuoteInArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 2)
	seeds = append(seeds, []byte{117, 115, 101, 114, 95, 118, 111, 108, 117, 109, 101, 95, 97, 99, 99, 117, 109, 117, 108, 97, 116, 111, 114})
	seeds = append(seeds, accounts.User[:])
	return solana.FindProgramAddress(seeds, ProgramKey)
}

func DeriveBuyExactQuoteInFeeConfigPDA(accounts BuyExactQuoteInAccounts, args BuyExactQuoteInArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 2)
	seeds = append(seeds, []byte{102, 101, 101, 95, 99, 111, 110, 102, 105, 103})
	seeds = append(seeds, []byte{12, 20, 222, 252, 130, 94, 198, 118, 148, 37, 8, 24, 187, 101, 64, 101, 244, 41, 141, 49, 86, 213, 113, 180, 212, 248, 9, 12, 24, 233, 168, 99})
	return solana.FindProgramAddress(seeds, accounts.FeeProgram)
}

var ClaimTokenIncentivesDiscriminator = []byte{16, 4, 71, 28, 204, 1, 40, 27}

type ClaimTokenIncentivesArgs struct{}

type ClaimTokenIncentivesAccounts struct {
	User                        solana.PublicKey
	UserAta                     solana.PublicKey
	GlobalVolumeAccumulator     solana.PublicKey
	GlobalIncentiveTokenAccount solana.PublicKey
	UserVolumeAccumulator       solana.PublicKey
	Mint                        solana.PublicKey
	TokenProgram                solana.PublicKey
	SystemProgram               solana.PublicKey
	AssociatedTokenProgram      solana.PublicKey
	EventAuthority              solana.PublicKey
	Program                     solana.PublicKey
	Payer                       solana.PublicKey
}

func (a ClaimTokenIncentivesAccounts) ToAccountMetas() []*solana.AccountMeta {
	metas := make([]*solana.AccountMeta, 0, 12)
	metas = append(metas, solana.NewAccountMeta(a.User, false, false))
	metas = append(metas, solana.NewAccountMeta(a.UserAta, true, false))
	metas = append(metas, solana.NewAccountMeta(a.GlobalVolumeAccumulator, false, false))
	metas = append(metas, solana.NewAccountMeta(a.GlobalIncentiveTokenAccount, true, false))
	metas = append(metas, solana.NewAccountMeta(a.UserVolumeAccumulator, true, false))
	metas = append(metas, solana.NewAccountMeta(a.Mint, false, false))
	metas = append(metas, solana.NewAccountMeta(a.TokenProgram, false, false))
	var defaultClaimTokenIncentivesSystemProgram = func() solana.PublicKey {
		return solana.MustPublicKeyFromBase58("11111111111111111111111111111111")
	}

	metas = append(metas, solana.NewAccountMeta(defaultClaimTokenIncentivesSystemProgram(), false, false))
	var defaultClaimTokenIncentivesAssociatedTokenProgram = func() solana.PublicKey {
		return solana.MustPublicKeyFromBase58("ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL")
	}

	metas = append(metas, solana.NewAccountMeta(defaultClaimTokenIncentivesAssociatedTokenProgram(), false, false))
	metas = append(metas, solana.NewAccountMeta(a.EventAuthority, false, false))
	var defaultClaimTokenIncentivesProgram = func() solana.PublicKey {
		return solana.MustPublicKeyFromBase58("pAMMBay6oceH9fJKBRHGP5D4bD4sWpmSwMn52FMfXEA")
	}

	metas = append(metas, solana.NewAccountMeta(defaultClaimTokenIncentivesProgram(), false, false))
	metas = append(metas, solana.NewAccountMeta(a.Payer, true, true))
	return metas
}

func BuildClaimTokenIncentives(accounts ClaimTokenIncentivesAccounts, args ClaimTokenIncentivesArgs) (solana.Instruction, error) {
	buf := bytes.NewBuffer(make([]byte, 0, 128))
	buf.Write(ClaimTokenIncentivesDiscriminator)
	data := buf.Bytes()
	return solana.NewInstruction(ProgramKey, accounts.ToAccountMetas(), data), nil
}

func DeriveClaimTokenIncentivesUserAtaPDA(accounts ClaimTokenIncentivesAccounts, args ClaimTokenIncentivesArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 3)
	seeds = append(seeds, accounts.User[:])
	seeds = append(seeds, accounts.TokenProgram[:])
	seeds = append(seeds, accounts.Mint[:])
	return solana.FindProgramAddress(seeds, solana.PublicKeyFromBytes([]byte{140, 151, 37, 143, 78, 36, 137, 241, 187, 61, 16, 41, 20, 142, 13, 131, 11, 90, 19, 153, 218, 255, 16, 132, 4, 142, 123, 216, 219, 233, 248, 89}))
}

func DeriveClaimTokenIncentivesGlobalVolumeAccumulatorPDA(accounts ClaimTokenIncentivesAccounts, args ClaimTokenIncentivesArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 1)
	seeds = append(seeds, []byte{103, 108, 111, 98, 97, 108, 95, 118, 111, 108, 117, 109, 101, 95, 97, 99, 99, 117, 109, 117, 108, 97, 116, 111, 114})
	return solana.FindProgramAddress(seeds, ProgramKey)
}

func DeriveClaimTokenIncentivesGlobalIncentiveTokenAccountPDA(accounts ClaimTokenIncentivesAccounts, args ClaimTokenIncentivesArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 3)
	seeds = append(seeds, accounts.GlobalVolumeAccumulator[:])
	seeds = append(seeds, accounts.TokenProgram[:])
	seeds = append(seeds, accounts.Mint[:])
	return solana.FindProgramAddress(seeds, solana.PublicKeyFromBytes([]byte{140, 151, 37, 143, 78, 36, 137, 241, 187, 61, 16, 41, 20, 142, 13, 131, 11, 90, 19, 153, 218, 255, 16, 132, 4, 142, 123, 216, 219, 233, 248, 89}))
}

func DeriveClaimTokenIncentivesUserVolumeAccumulatorPDA(accounts ClaimTokenIncentivesAccounts, args ClaimTokenIncentivesArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 2)
	seeds = append(seeds, []byte{117, 115, 101, 114, 95, 118, 111, 108, 117, 109, 101, 95, 97, 99, 99, 117, 109, 117, 108, 97, 116, 111, 114})
	seeds = append(seeds, accounts.User[:])
	return solana.FindProgramAddress(seeds, ProgramKey)
}

func DeriveClaimTokenIncentivesEventAuthorityPDA(accounts ClaimTokenIncentivesAccounts, args ClaimTokenIncentivesArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 1)
	seeds = append(seeds, []byte{95, 95, 101, 118, 101, 110, 116, 95, 97, 117, 116, 104, 111, 114, 105, 116, 121})
	return solana.FindProgramAddress(seeds, ProgramKey)
}

var CloseUserVolumeAccumulatorDiscriminator = []byte{249, 69, 164, 218, 150, 103, 84, 138}

type CloseUserVolumeAccumulatorArgs struct{}

type CloseUserVolumeAccumulatorAccounts struct {
	User                  solana.PublicKey
	UserVolumeAccumulator solana.PublicKey
	EventAuthority        solana.PublicKey
	Program               solana.PublicKey
}

func (a CloseUserVolumeAccumulatorAccounts) ToAccountMetas() []*solana.AccountMeta {
	metas := make([]*solana.AccountMeta, 0, 4)
	metas = append(metas, solana.NewAccountMeta(a.User, true, true))
	metas = append(metas, solana.NewAccountMeta(a.UserVolumeAccumulator, true, false))
	metas = append(metas, solana.NewAccountMeta(a.EventAuthority, false, false))
	metas = append(metas, solana.NewAccountMeta(a.Program, false, false))
	return metas
}

func BuildCloseUserVolumeAccumulator(accounts CloseUserVolumeAccumulatorAccounts, args CloseUserVolumeAccumulatorArgs) (solana.Instruction, error) {
	buf := bytes.NewBuffer(make([]byte, 0, 128))
	buf.Write(CloseUserVolumeAccumulatorDiscriminator)
	data := buf.Bytes()
	return solana.NewInstruction(ProgramKey, accounts.ToAccountMetas(), data), nil
}

func DeriveCloseUserVolumeAccumulatorUserVolumeAccumulatorPDA(accounts CloseUserVolumeAccumulatorAccounts, args CloseUserVolumeAccumulatorArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 2)
	seeds = append(seeds, []byte{117, 115, 101, 114, 95, 118, 111, 108, 117, 109, 101, 95, 97, 99, 99, 117, 109, 117, 108, 97, 116, 111, 114})
	seeds = append(seeds, accounts.User[:])
	return solana.FindProgramAddress(seeds, ProgramKey)
}

func DeriveCloseUserVolumeAccumulatorEventAuthorityPDA(accounts CloseUserVolumeAccumulatorAccounts, args CloseUserVolumeAccumulatorArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 1)
	seeds = append(seeds, []byte{95, 95, 101, 118, 101, 110, 116, 95, 97, 117, 116, 104, 111, 114, 105, 116, 121})
	return solana.FindProgramAddress(seeds, ProgramKey)
}

var CollectCoinCreatorFeeDiscriminator = []byte{160, 57, 89, 42, 181, 139, 43, 66}

type CollectCoinCreatorFeeArgs struct{}

type CollectCoinCreatorFeeAccounts struct {
	QuoteMint                 solana.PublicKey
	QuoteTokenProgram         solana.PublicKey
	CoinCreator               solana.PublicKey
	CoinCreatorVaultAuthority solana.PublicKey
	CoinCreatorVaultAta       solana.PublicKey
	CoinCreatorTokenAccount   solana.PublicKey
	EventAuthority            solana.PublicKey
	Program                   solana.PublicKey
}

func (a CollectCoinCreatorFeeAccounts) ToAccountMetas() []*solana.AccountMeta {
	metas := make([]*solana.AccountMeta, 0, 8)
	metas = append(metas, solana.NewAccountMeta(a.QuoteMint, false, false))
	metas = append(metas, solana.NewAccountMeta(a.QuoteTokenProgram, false, false))
	metas = append(metas, solana.NewAccountMeta(a.CoinCreator, false, false))
	metas = append(metas, solana.NewAccountMeta(a.CoinCreatorVaultAuthority, false, false))
	metas = append(metas, solana.NewAccountMeta(a.CoinCreatorVaultAta, true, false))
	metas = append(metas, solana.NewAccountMeta(a.CoinCreatorTokenAccount, true, false))
	metas = append(metas, solana.NewAccountMeta(a.EventAuthority, false, false))
	metas = append(metas, solana.NewAccountMeta(a.Program, false, false))
	return metas
}

func BuildCollectCoinCreatorFee(accounts CollectCoinCreatorFeeAccounts, args CollectCoinCreatorFeeArgs) (solana.Instruction, error) {
	buf := bytes.NewBuffer(make([]byte, 0, 128))
	buf.Write(CollectCoinCreatorFeeDiscriminator)
	data := buf.Bytes()
	return solana.NewInstruction(ProgramKey, accounts.ToAccountMetas(), data), nil
}

func DeriveCollectCoinCreatorFeeCoinCreatorVaultAuthorityPDA(accounts CollectCoinCreatorFeeAccounts, args CollectCoinCreatorFeeArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 2)
	seeds = append(seeds, []byte{99, 114, 101, 97, 116, 111, 114, 95, 118, 97, 117, 108, 116})
	seeds = append(seeds, accounts.CoinCreator[:])
	return solana.FindProgramAddress(seeds, ProgramKey)
}

func DeriveCollectCoinCreatorFeeCoinCreatorVaultAtaPDA(accounts CollectCoinCreatorFeeAccounts, args CollectCoinCreatorFeeArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 3)
	seeds = append(seeds, accounts.CoinCreatorVaultAuthority[:])
	seeds = append(seeds, accounts.QuoteTokenProgram[:])
	seeds = append(seeds, accounts.QuoteMint[:])
	return solana.FindProgramAddress(seeds, solana.PublicKeyFromBytes([]byte{140, 151, 37, 143, 78, 36, 137, 241, 187, 61, 16, 41, 20, 142, 13, 131, 11, 90, 19, 153, 218, 255, 16, 132, 4, 142, 123, 216, 219, 233, 248, 89}))
}

func DeriveCollectCoinCreatorFeeEventAuthorityPDA(accounts CollectCoinCreatorFeeAccounts, args CollectCoinCreatorFeeArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 1)
	seeds = append(seeds, []byte{95, 95, 101, 118, 101, 110, 116, 95, 97, 117, 116, 104, 111, 114, 105, 116, 121})
	return solana.FindProgramAddress(seeds, ProgramKey)
}

var CreateConfigDiscriminator = []byte{201, 207, 243, 114, 75, 111, 47, 189}

type CreateConfigArgs struct {
	LpFeeBasisPoints             uint64              `bin:"lp_fee_basis_points"`
	ProtocolFeeBasisPoints       uint64              `bin:"protocol_fee_basis_points"`
	ProtocolFeeRecipients        [8]solana.PublicKey `bin:"protocol_fee_recipients"`
	CoinCreatorFeeBasisPoints    uint64              `bin:"coin_creator_fee_basis_points"`
	AdminSetCoinCreatorAuthority solana.PublicKey    `bin:"admin_set_coin_creator_authority"`
}

type CreateConfigAccounts struct {
	Admin          solana.PublicKey
	GlobalConfig   solana.PublicKey
	SystemProgram  solana.PublicKey
	EventAuthority solana.PublicKey
	Program        solana.PublicKey
}

func (a CreateConfigAccounts) ToAccountMetas() []*solana.AccountMeta {
	metas := make([]*solana.AccountMeta, 0, 5)
	var defaultCreateConfigAdmin = func() solana.PublicKey {
		return solana.MustPublicKeyFromBase58("8LWu7QM2dGR1G8nKDHthckea57bkCzXyBTAKPJUBDHo8")
	}

	metas = append(metas, solana.NewAccountMeta(defaultCreateConfigAdmin(), true, false))
	metas = append(metas, solana.NewAccountMeta(a.GlobalConfig, true, false))
	var defaultCreateConfigSystemProgram = func() solana.PublicKey {
		return solana.MustPublicKeyFromBase58("11111111111111111111111111111111")
	}

	metas = append(metas, solana.NewAccountMeta(defaultCreateConfigSystemProgram(), false, false))
	metas = append(metas, solana.NewAccountMeta(a.EventAuthority, false, false))
	metas = append(metas, solana.NewAccountMeta(a.Program, false, false))
	return metas
}

func BuildCreateConfig(accounts CreateConfigAccounts, args CreateConfigArgs) (solana.Instruction, error) {
	buf := bytes.NewBuffer(make([]byte, 0, 128))
	buf.Write(CreateConfigDiscriminator)
	if err := bin.NewBorshEncoder(buf).Encode(args); err != nil {
		return nil, fmt.Errorf("encode args: %w", err)
	}
	data := buf.Bytes()
	return solana.NewInstruction(ProgramKey, accounts.ToAccountMetas(), data), nil
}

func DeriveCreateConfigGlobalConfigPDA(accounts CreateConfigAccounts, args CreateConfigArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 1)
	seeds = append(seeds, []byte{103, 108, 111, 98, 97, 108, 95, 99, 111, 110, 102, 105, 103})
	return solana.FindProgramAddress(seeds, ProgramKey)
}

func DeriveCreateConfigEventAuthorityPDA(accounts CreateConfigAccounts, args CreateConfigArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 1)
	seeds = append(seeds, []byte{95, 95, 101, 118, 101, 110, 116, 95, 97, 117, 116, 104, 111, 114, 105, 116, 121})
	return solana.FindProgramAddress(seeds, ProgramKey)
}

var CreatePoolDiscriminator = []byte{233, 146, 209, 142, 207, 104, 64, 188}

type CreatePoolArgs struct {
	Index         uint16           `bin:"index"`
	BaseAmountIn  uint64           `bin:"base_amount_in"`
	QuoteAmountIn uint64           `bin:"quote_amount_in"`
	CoinCreator   solana.PublicKey `bin:"coin_creator"`
	IsMayhemMode  bool             `bin:"is_mayhem_mode"`
}

type CreatePoolAccounts struct {
	Pool                   solana.PublicKey
	GlobalConfig           solana.PublicKey
	Creator                solana.PublicKey
	BaseMint               solana.PublicKey
	QuoteMint              solana.PublicKey
	LpMint                 solana.PublicKey
	UserBaseTokenAccount   solana.PublicKey
	UserQuoteTokenAccount  solana.PublicKey
	UserPoolTokenAccount   solana.PublicKey
	PoolBaseTokenAccount   solana.PublicKey
	PoolQuoteTokenAccount  solana.PublicKey
	SystemProgram          solana.PublicKey
	Token2022Program       solana.PublicKey
	BaseTokenProgram       solana.PublicKey
	QuoteTokenProgram      solana.PublicKey
	AssociatedTokenProgram solana.PublicKey
	EventAuthority         solana.PublicKey
	Program                solana.PublicKey
}

func (a CreatePoolAccounts) ToAccountMetas() []*solana.AccountMeta {
	metas := make([]*solana.AccountMeta, 0, 18)
	metas = append(metas, solana.NewAccountMeta(a.Pool, true, false))
	metas = append(metas, solana.NewAccountMeta(a.GlobalConfig, false, false))
	metas = append(metas, solana.NewAccountMeta(a.Creator, true, true))
	metas = append(metas, solana.NewAccountMeta(a.BaseMint, false, false))
	metas = append(metas, solana.NewAccountMeta(a.QuoteMint, false, false))
	metas = append(metas, solana.NewAccountMeta(a.LpMint, true, false))
	metas = append(metas, solana.NewAccountMeta(a.UserBaseTokenAccount, true, false))
	metas = append(metas, solana.NewAccountMeta(a.UserQuoteTokenAccount, true, false))
	metas = append(metas, solana.NewAccountMeta(a.UserPoolTokenAccount, true, false))
	metas = append(metas, solana.NewAccountMeta(a.PoolBaseTokenAccount, true, false))
	metas = append(metas, solana.NewAccountMeta(a.PoolQuoteTokenAccount, true, false))
	var defaultCreatePoolSystemProgram = func() solana.PublicKey {
		return solana.MustPublicKeyFromBase58("11111111111111111111111111111111")
	}

	metas = append(metas, solana.NewAccountMeta(defaultCreatePoolSystemProgram(), false, false))
	var defaultCreatePoolToken2022Program = func() solana.PublicKey {
		return solana.MustPublicKeyFromBase58("TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb")
	}

	metas = append(metas, solana.NewAccountMeta(defaultCreatePoolToken2022Program(), false, false))
	metas = append(metas, solana.NewAccountMeta(a.BaseTokenProgram, false, false))
	metas = append(metas, solana.NewAccountMeta(a.QuoteTokenProgram, false, false))
	var defaultCreatePoolAssociatedTokenProgram = func() solana.PublicKey {
		return solana.MustPublicKeyFromBase58("ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL")
	}

	metas = append(metas, solana.NewAccountMeta(defaultCreatePoolAssociatedTokenProgram(), false, false))
	metas = append(metas, solana.NewAccountMeta(a.EventAuthority, false, false))
	metas = append(metas, solana.NewAccountMeta(a.Program, false, false))
	return metas
}

func BuildCreatePool(accounts CreatePoolAccounts, args CreatePoolArgs) (solana.Instruction, error) {
	buf := bytes.NewBuffer(make([]byte, 0, 128))
	buf.Write(CreatePoolDiscriminator)
	if err := bin.NewBorshEncoder(buf).Encode(args); err != nil {
		return nil, fmt.Errorf("encode args: %w", err)
	}
	data := buf.Bytes()
	return solana.NewInstruction(ProgramKey, accounts.ToAccountMetas(), data), nil
}

func DeriveCreatePoolPoolPDA(accounts CreatePoolAccounts, args CreatePoolArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 5)
	seeds = append(seeds, []byte{112, 111, 111, 108})
	{
		tmp := make([]byte, 8)
		binary.LittleEndian.PutUint64(tmp, uint64(args.Index))
		seeds = append(seeds, tmp)
	}
	seeds = append(seeds, accounts.Creator[:])
	seeds = append(seeds, accounts.BaseMint[:])
	seeds = append(seeds, accounts.QuoteMint[:])
	return solana.FindProgramAddress(seeds, ProgramKey)
}

func DeriveCreatePoolLpMintPDA(accounts CreatePoolAccounts, args CreatePoolArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 2)
	seeds = append(seeds, []byte{112, 111, 111, 108, 95, 108, 112, 95, 109, 105, 110, 116})
	seeds = append(seeds, accounts.Pool[:])
	return solana.FindProgramAddress(seeds, ProgramKey)
}

func DeriveCreatePoolUserPoolTokenAccountPDA(accounts CreatePoolAccounts, args CreatePoolArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 3)
	seeds = append(seeds, accounts.Creator[:])
	seeds = append(seeds, accounts.Token2022Program[:])
	seeds = append(seeds, accounts.LpMint[:])
	return solana.FindProgramAddress(seeds, solana.PublicKeyFromBytes([]byte{140, 151, 37, 143, 78, 36, 137, 241, 187, 61, 16, 41, 20, 142, 13, 131, 11, 90, 19, 153, 218, 255, 16, 132, 4, 142, 123, 216, 219, 233, 248, 89}))
}

func DeriveCreatePoolPoolBaseTokenAccountPDA(accounts CreatePoolAccounts, args CreatePoolArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 3)
	seeds = append(seeds, accounts.Pool[:])
	seeds = append(seeds, accounts.BaseTokenProgram[:])
	seeds = append(seeds, accounts.BaseMint[:])
	return solana.FindProgramAddress(seeds, solana.PublicKeyFromBytes([]byte{140, 151, 37, 143, 78, 36, 137, 241, 187, 61, 16, 41, 20, 142, 13, 131, 11, 90, 19, 153, 218, 255, 16, 132, 4, 142, 123, 216, 219, 233, 248, 89}))
}

func DeriveCreatePoolPoolQuoteTokenAccountPDA(accounts CreatePoolAccounts, args CreatePoolArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 3)
	seeds = append(seeds, accounts.Pool[:])
	seeds = append(seeds, accounts.QuoteTokenProgram[:])
	seeds = append(seeds, accounts.QuoteMint[:])
	return solana.FindProgramAddress(seeds, solana.PublicKeyFromBytes([]byte{140, 151, 37, 143, 78, 36, 137, 241, 187, 61, 16, 41, 20, 142, 13, 131, 11, 90, 19, 153, 218, 255, 16, 132, 4, 142, 123, 216, 219, 233, 248, 89}))
}

func DeriveCreatePoolEventAuthorityPDA(accounts CreatePoolAccounts, args CreatePoolArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 1)
	seeds = append(seeds, []byte{95, 95, 101, 118, 101, 110, 116, 95, 97, 117, 116, 104, 111, 114, 105, 116, 121})
	return solana.FindProgramAddress(seeds, ProgramKey)
}

var DepositDiscriminator = []byte{242, 35, 198, 137, 82, 225, 242, 182}

type DepositArgs struct {
	LpTokenAmountOut uint64 `bin:"lp_token_amount_out"`
	MaxBaseAmountIn  uint64 `bin:"max_base_amount_in"`
	MaxQuoteAmountIn uint64 `bin:"max_quote_amount_in"`
}

type DepositAccounts struct {
	Pool                  solana.PublicKey
	GlobalConfig          solana.PublicKey
	User                  solana.PublicKey
	BaseMint              solana.PublicKey
	QuoteMint             solana.PublicKey
	LpMint                solana.PublicKey
	UserBaseTokenAccount  solana.PublicKey
	UserQuoteTokenAccount solana.PublicKey
	UserPoolTokenAccount  solana.PublicKey
	PoolBaseTokenAccount  solana.PublicKey
	PoolQuoteTokenAccount solana.PublicKey
	TokenProgram          solana.PublicKey
	Token2022Program      solana.PublicKey
	EventAuthority        solana.PublicKey
	Program               solana.PublicKey
}

func (a DepositAccounts) ToAccountMetas() []*solana.AccountMeta {
	metas := make([]*solana.AccountMeta, 0, 15)
	metas = append(metas, solana.NewAccountMeta(a.Pool, true, false))
	metas = append(metas, solana.NewAccountMeta(a.GlobalConfig, false, false))
	metas = append(metas, solana.NewAccountMeta(a.User, false, true))
	metas = append(metas, solana.NewAccountMeta(a.BaseMint, false, false))
	metas = append(metas, solana.NewAccountMeta(a.QuoteMint, false, false))
	metas = append(metas, solana.NewAccountMeta(a.LpMint, true, false))
	metas = append(metas, solana.NewAccountMeta(a.UserBaseTokenAccount, true, false))
	metas = append(metas, solana.NewAccountMeta(a.UserQuoteTokenAccount, true, false))
	metas = append(metas, solana.NewAccountMeta(a.UserPoolTokenAccount, true, false))
	metas = append(metas, solana.NewAccountMeta(a.PoolBaseTokenAccount, true, false))
	metas = append(metas, solana.NewAccountMeta(a.PoolQuoteTokenAccount, true, false))
	var defaultDepositTokenProgram = func() solana.PublicKey {
		return solana.MustPublicKeyFromBase58("TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA")
	}

	metas = append(metas, solana.NewAccountMeta(defaultDepositTokenProgram(), false, false))
	var defaultDepositToken2022Program = func() solana.PublicKey {
		return solana.MustPublicKeyFromBase58("TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb")
	}

	metas = append(metas, solana.NewAccountMeta(defaultDepositToken2022Program(), false, false))
	metas = append(metas, solana.NewAccountMeta(a.EventAuthority, false, false))
	metas = append(metas, solana.NewAccountMeta(a.Program, false, false))
	return metas
}

func BuildDeposit(accounts DepositAccounts, args DepositArgs) (solana.Instruction, error) {
	buf := bytes.NewBuffer(make([]byte, 0, 128))
	buf.Write(DepositDiscriminator)
	if err := bin.NewBorshEncoder(buf).Encode(args); err != nil {
		return nil, fmt.Errorf("encode args: %w", err)
	}
	data := buf.Bytes()
	return solana.NewInstruction(ProgramKey, accounts.ToAccountMetas(), data), nil
}

func DeriveDepositEventAuthorityPDA(accounts DepositAccounts, args DepositArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 1)
	seeds = append(seeds, []byte{95, 95, 101, 118, 101, 110, 116, 95, 97, 117, 116, 104, 111, 114, 105, 116, 121})
	return solana.FindProgramAddress(seeds, ProgramKey)
}

var DisableDiscriminator = []byte{185, 173, 187, 90, 216, 15, 238, 233}

type DisableArgs struct {
	DisableCreatePool bool `bin:"disable_create_pool"`
	DisableDeposit    bool `bin:"disable_deposit"`
	DisableWithdraw   bool `bin:"disable_withdraw"`
	DisableBuy        bool `bin:"disable_buy"`
	DisableSell       bool `bin:"disable_sell"`
}

type DisableAccounts struct {
	Admin          solana.PublicKey
	GlobalConfig   solana.PublicKey
	EventAuthority solana.PublicKey
	Program        solana.PublicKey
}

func (a DisableAccounts) ToAccountMetas() []*solana.AccountMeta {
	metas := make([]*solana.AccountMeta, 0, 4)
	metas = append(metas, solana.NewAccountMeta(a.Admin, false, true))
	metas = append(metas, solana.NewAccountMeta(a.GlobalConfig, true, false))
	metas = append(metas, solana.NewAccountMeta(a.EventAuthority, false, false))
	metas = append(metas, solana.NewAccountMeta(a.Program, false, false))
	return metas
}

func BuildDisable(accounts DisableAccounts, args DisableArgs) (solana.Instruction, error) {
	buf := bytes.NewBuffer(make([]byte, 0, 128))
	buf.Write(DisableDiscriminator)
	if err := bin.NewBorshEncoder(buf).Encode(args); err != nil {
		return nil, fmt.Errorf("encode args: %w", err)
	}
	data := buf.Bytes()
	return solana.NewInstruction(ProgramKey, accounts.ToAccountMetas(), data), nil
}

func DeriveDisableEventAuthorityPDA(accounts DisableAccounts, args DisableArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 1)
	seeds = append(seeds, []byte{95, 95, 101, 118, 101, 110, 116, 95, 97, 117, 116, 104, 111, 114, 105, 116, 121})
	return solana.FindProgramAddress(seeds, ProgramKey)
}

var ExtendAccountDiscriminator = []byte{234, 102, 194, 203, 150, 72, 62, 229}

type ExtendAccountArgs struct{}

type ExtendAccountAccounts struct {
	Account        solana.PublicKey
	User           solana.PublicKey
	SystemProgram  solana.PublicKey
	EventAuthority solana.PublicKey
	Program        solana.PublicKey
}

func (a ExtendAccountAccounts) ToAccountMetas() []*solana.AccountMeta {
	metas := make([]*solana.AccountMeta, 0, 5)
	metas = append(metas, solana.NewAccountMeta(a.Account, true, false))
	metas = append(metas, solana.NewAccountMeta(a.User, false, true))
	var defaultExtendAccountSystemProgram = func() solana.PublicKey {
		return solana.MustPublicKeyFromBase58("11111111111111111111111111111111")
	}

	metas = append(metas, solana.NewAccountMeta(defaultExtendAccountSystemProgram(), false, false))
	metas = append(metas, solana.NewAccountMeta(a.EventAuthority, false, false))
	metas = append(metas, solana.NewAccountMeta(a.Program, false, false))
	return metas
}

func BuildExtendAccount(accounts ExtendAccountAccounts, args ExtendAccountArgs) (solana.Instruction, error) {
	buf := bytes.NewBuffer(make([]byte, 0, 128))
	buf.Write(ExtendAccountDiscriminator)
	data := buf.Bytes()
	return solana.NewInstruction(ProgramKey, accounts.ToAccountMetas(), data), nil
}

func DeriveExtendAccountEventAuthorityPDA(accounts ExtendAccountAccounts, args ExtendAccountArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 1)
	seeds = append(seeds, []byte{95, 95, 101, 118, 101, 110, 116, 95, 97, 117, 116, 104, 111, 114, 105, 116, 121})
	return solana.FindProgramAddress(seeds, ProgramKey)
}

var InitUserVolumeAccumulatorDiscriminator = []byte{94, 6, 202, 115, 255, 96, 232, 183}

type InitUserVolumeAccumulatorArgs struct{}

type InitUserVolumeAccumulatorAccounts struct {
	Payer                 solana.PublicKey
	User                  solana.PublicKey
	UserVolumeAccumulator solana.PublicKey
	SystemProgram         solana.PublicKey
	EventAuthority        solana.PublicKey
	Program               solana.PublicKey
}

func (a InitUserVolumeAccumulatorAccounts) ToAccountMetas() []*solana.AccountMeta {
	metas := make([]*solana.AccountMeta, 0, 6)
	metas = append(metas, solana.NewAccountMeta(a.Payer, true, true))
	metas = append(metas, solana.NewAccountMeta(a.User, false, false))
	metas = append(metas, solana.NewAccountMeta(a.UserVolumeAccumulator, true, false))
	var defaultInitUserVolumeAccumulatorSystemProgram = func() solana.PublicKey {
		return solana.MustPublicKeyFromBase58("11111111111111111111111111111111")
	}

	metas = append(metas, solana.NewAccountMeta(defaultInitUserVolumeAccumulatorSystemProgram(), false, false))
	metas = append(metas, solana.NewAccountMeta(a.EventAuthority, false, false))
	metas = append(metas, solana.NewAccountMeta(a.Program, false, false))
	return metas
}

func BuildInitUserVolumeAccumulator(accounts InitUserVolumeAccumulatorAccounts, args InitUserVolumeAccumulatorArgs) (solana.Instruction, error) {
	buf := bytes.NewBuffer(make([]byte, 0, 128))
	buf.Write(InitUserVolumeAccumulatorDiscriminator)
	data := buf.Bytes()
	return solana.NewInstruction(ProgramKey, accounts.ToAccountMetas(), data), nil
}

func DeriveInitUserVolumeAccumulatorUserVolumeAccumulatorPDA(accounts InitUserVolumeAccumulatorAccounts, args InitUserVolumeAccumulatorArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 2)
	seeds = append(seeds, []byte{117, 115, 101, 114, 95, 118, 111, 108, 117, 109, 101, 95, 97, 99, 99, 117, 109, 117, 108, 97, 116, 111, 114})
	seeds = append(seeds, accounts.User[:])
	return solana.FindProgramAddress(seeds, ProgramKey)
}

func DeriveInitUserVolumeAccumulatorEventAuthorityPDA(accounts InitUserVolumeAccumulatorAccounts, args InitUserVolumeAccumulatorArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 1)
	seeds = append(seeds, []byte{95, 95, 101, 118, 101, 110, 116, 95, 97, 117, 116, 104, 111, 114, 105, 116, 121})
	return solana.FindProgramAddress(seeds, ProgramKey)
}

var SellDiscriminator = []byte{51, 230, 133, 164, 1, 127, 131, 173}

type SellArgs struct {
	BaseAmountIn      uint64 `bin:"base_amount_in"`
	MinQuoteAmountOut uint64 `bin:"min_quote_amount_out"`
}

type SellAccounts struct {
	Pool                             solana.PublicKey
	User                             solana.PublicKey
	GlobalConfig                     solana.PublicKey
	BaseMint                         solana.PublicKey
	QuoteMint                        solana.PublicKey
	UserBaseTokenAccount             solana.PublicKey
	UserQuoteTokenAccount            solana.PublicKey
	PoolBaseTokenAccount             solana.PublicKey
	PoolQuoteTokenAccount            solana.PublicKey
	ProtocolFeeRecipient             solana.PublicKey
	ProtocolFeeRecipientTokenAccount solana.PublicKey
	BaseTokenProgram                 solana.PublicKey
	QuoteTokenProgram                solana.PublicKey
	SystemProgram                    solana.PublicKey
	AssociatedTokenProgram           solana.PublicKey
	EventAuthority                   solana.PublicKey
	Program                          solana.PublicKey
	CoinCreatorVaultAta              solana.PublicKey
	CoinCreatorVaultAuthority        solana.PublicKey
	FeeConfig                        solana.PublicKey
	FeeProgram                       solana.PublicKey
}

func (a SellAccounts) ToAccountMetas() []*solana.AccountMeta {
	metas := make([]*solana.AccountMeta, 0, 21)
	metas = append(metas, solana.NewAccountMeta(a.Pool, true, false))
	metas = append(metas, solana.NewAccountMeta(a.User, true, true))
	metas = append(metas, solana.NewAccountMeta(a.GlobalConfig, false, false))
	metas = append(metas, solana.NewAccountMeta(a.BaseMint, false, false))
	metas = append(metas, solana.NewAccountMeta(a.QuoteMint, false, false))
	metas = append(metas, solana.NewAccountMeta(a.UserBaseTokenAccount, true, false))
	metas = append(metas, solana.NewAccountMeta(a.UserQuoteTokenAccount, true, false))
	metas = append(metas, solana.NewAccountMeta(a.PoolBaseTokenAccount, true, false))
	metas = append(metas, solana.NewAccountMeta(a.PoolQuoteTokenAccount, true, false))
	metas = append(metas, solana.NewAccountMeta(a.ProtocolFeeRecipient, false, false))
	metas = append(metas, solana.NewAccountMeta(a.ProtocolFeeRecipientTokenAccount, true, false))
	metas = append(metas, solana.NewAccountMeta(a.BaseTokenProgram, false, false))
	metas = append(metas, solana.NewAccountMeta(a.QuoteTokenProgram, false, false))
	var defaultSellSystemProgram = func() solana.PublicKey {
		return solana.MustPublicKeyFromBase58("11111111111111111111111111111111")
	}

	metas = append(metas, solana.NewAccountMeta(defaultSellSystemProgram(), false, false))
	var defaultSellAssociatedTokenProgram = func() solana.PublicKey {
		return solana.MustPublicKeyFromBase58("ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL")
	}

	metas = append(metas, solana.NewAccountMeta(defaultSellAssociatedTokenProgram(), false, false))
	metas = append(metas, solana.NewAccountMeta(a.EventAuthority, false, false))
	var defaultSellProgram = func() solana.PublicKey {
		return solana.MustPublicKeyFromBase58("pAMMBay6oceH9fJKBRHGP5D4bD4sWpmSwMn52FMfXEA")
	}

	metas = append(metas, solana.NewAccountMeta(defaultSellProgram(), false, false))
	metas = append(metas, solana.NewAccountMeta(a.CoinCreatorVaultAta, true, false))
	metas = append(metas, solana.NewAccountMeta(a.CoinCreatorVaultAuthority, false, false))
	metas = append(metas, solana.NewAccountMeta(a.FeeConfig, false, false))
	var defaultSellFeeProgram = func() solana.PublicKey {
		return solana.MustPublicKeyFromBase58("pfeeUxB6jkeY1Hxd7CsFCAjcbHA9rWtchMGdZ6VojVZ")
	}

	metas = append(metas, solana.NewAccountMeta(defaultSellFeeProgram(), false, false))
	return metas
}

func BuildSell(accounts SellAccounts, args SellArgs) (solana.Instruction, error) {
	buf := bytes.NewBuffer(make([]byte, 0, 128))
	buf.Write(SellDiscriminator)
	if err := bin.NewBorshEncoder(buf).Encode(args); err != nil {
		return nil, fmt.Errorf("encode args: %w", err)
	}
	data := buf.Bytes()
	return solana.NewInstruction(ProgramKey, accounts.ToAccountMetas(), data), nil
}

func DeriveSellProtocolFeeRecipientTokenAccountPDA(accounts SellAccounts, args SellArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 3)
	seeds = append(seeds, accounts.ProtocolFeeRecipient[:])
	seeds = append(seeds, accounts.QuoteTokenProgram[:])
	seeds = append(seeds, accounts.QuoteMint[:])
	return solana.FindProgramAddress(seeds, solana.PublicKeyFromBytes([]byte{140, 151, 37, 143, 78, 36, 137, 241, 187, 61, 16, 41, 20, 142, 13, 131, 11, 90, 19, 153, 218, 255, 16, 132, 4, 142, 123, 216, 219, 233, 248, 89}))
}

func DeriveSellEventAuthorityPDA(accounts SellAccounts, args SellArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 1)
	seeds = append(seeds, []byte{95, 95, 101, 118, 101, 110, 116, 95, 97, 117, 116, 104, 111, 114, 105, 116, 121})
	return solana.FindProgramAddress(seeds, ProgramKey)
}

func DeriveSellCoinCreatorVaultAtaPDA(accounts SellAccounts, args SellArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 3)
	seeds = append(seeds, accounts.CoinCreatorVaultAuthority[:])
	seeds = append(seeds, accounts.QuoteTokenProgram[:])
	seeds = append(seeds, accounts.QuoteMint[:])
	return solana.FindProgramAddress(seeds, solana.PublicKeyFromBytes([]byte{140, 151, 37, 143, 78, 36, 137, 241, 187, 61, 16, 41, 20, 142, 13, 131, 11, 90, 19, 153, 218, 255, 16, 132, 4, 142, 123, 216, 219, 233, 248, 89}))
}

func DeriveSellCoinCreatorVaultAuthorityPDA(accounts SellAccounts, args SellArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 2)
	seeds = append(seeds, []byte{99, 114, 101, 97, 116, 111, 114, 95, 118, 97, 117, 108, 116})
	seeds = append(seeds, accounts.Pool[:])
	return solana.FindProgramAddress(seeds, ProgramKey)
}

func DeriveSellFeeConfigPDA(accounts SellAccounts, args SellArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 2)
	seeds = append(seeds, []byte{102, 101, 101, 95, 99, 111, 110, 102, 105, 103})
	seeds = append(seeds, []byte{12, 20, 222, 252, 130, 94, 198, 118, 148, 37, 8, 24, 187, 101, 64, 101, 244, 41, 141, 49, 86, 213, 113, 180, 212, 248, 9, 12, 24, 233, 168, 99})
	return solana.FindProgramAddress(seeds, accounts.FeeProgram)
}

var SetCoinCreatorDiscriminator = []byte{210, 149, 128, 45, 188, 58, 78, 175}

type SetCoinCreatorArgs struct{}

type SetCoinCreatorAccounts struct {
	Pool           solana.PublicKey
	Metadata       solana.PublicKey
	BondingCurve   solana.PublicKey
	EventAuthority solana.PublicKey
	Program        solana.PublicKey
}

func (a SetCoinCreatorAccounts) ToAccountMetas() []*solana.AccountMeta {
	metas := make([]*solana.AccountMeta, 0, 5)
	metas = append(metas, solana.NewAccountMeta(a.Pool, true, false))
	metas = append(metas, solana.NewAccountMeta(a.Metadata, false, false))
	metas = append(metas, solana.NewAccountMeta(a.BondingCurve, false, false))
	metas = append(metas, solana.NewAccountMeta(a.EventAuthority, false, false))
	metas = append(metas, solana.NewAccountMeta(a.Program, false, false))
	return metas
}

func BuildSetCoinCreator(accounts SetCoinCreatorAccounts, args SetCoinCreatorArgs) (solana.Instruction, error) {
	buf := bytes.NewBuffer(make([]byte, 0, 128))
	buf.Write(SetCoinCreatorDiscriminator)
	data := buf.Bytes()
	return solana.NewInstruction(ProgramKey, accounts.ToAccountMetas(), data), nil
}

func DeriveSetCoinCreatorMetadataPDA(accounts SetCoinCreatorAccounts, args SetCoinCreatorArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 3)
	seeds = append(seeds, []byte{109, 101, 116, 97, 100, 97, 116, 97})
	seeds = append(seeds, []byte{11, 112, 101, 177, 227, 209, 124, 69, 56, 157, 82, 127, 107, 4, 195, 205, 88, 184, 108, 115, 26, 160, 253, 181, 73, 182, 209, 188, 3, 248, 41, 70})
	seeds = append(seeds, accounts.Pool[:])
	return solana.FindProgramAddress(seeds, solana.PublicKeyFromBytes([]byte{11, 112, 101, 177, 227, 209, 124, 69, 56, 157, 82, 127, 107, 4, 195, 205, 88, 184, 108, 115, 26, 160, 253, 181, 73, 182, 209, 188, 3, 248, 41, 70}))
}

func DeriveSetCoinCreatorBondingCurvePDA(accounts SetCoinCreatorAccounts, args SetCoinCreatorArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 2)
	seeds = append(seeds, []byte{98, 111, 110, 100, 105, 110, 103, 45, 99, 117, 114, 118, 101})
	seeds = append(seeds, accounts.Pool[:])
	return solana.FindProgramAddress(seeds, solana.PublicKeyFromBytes([]byte{1, 86, 224, 246, 147, 102, 90, 207, 68, 219, 21, 104, 191, 23, 91, 170, 81, 137, 203, 151, 245, 210, 255, 59, 101, 93, 43, 182, 253, 109, 24, 176}))
}

func DeriveSetCoinCreatorEventAuthorityPDA(accounts SetCoinCreatorAccounts, args SetCoinCreatorArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 1)
	seeds = append(seeds, []byte{95, 95, 101, 118, 101, 110, 116, 95, 97, 117, 116, 104, 111, 114, 105, 116, 121})
	return solana.FindProgramAddress(seeds, ProgramKey)
}

var SetReservedFeeRecipientsDiscriminator = []byte{111, 172, 162, 232, 114, 89, 213, 142}

type SetReservedFeeRecipientsArgs struct {
	WhitelistPda solana.PublicKey `bin:"whitelist_pda"`
}

type SetReservedFeeRecipientsAccounts struct {
	GlobalConfig   solana.PublicKey
	Admin          solana.PublicKey
	EventAuthority solana.PublicKey
	Program        solana.PublicKey
}

func (a SetReservedFeeRecipientsAccounts) ToAccountMetas() []*solana.AccountMeta {
	metas := make([]*solana.AccountMeta, 0, 4)
	metas = append(metas, solana.NewAccountMeta(a.GlobalConfig, true, false))
	metas = append(metas, solana.NewAccountMeta(a.Admin, false, true))
	metas = append(metas, solana.NewAccountMeta(a.EventAuthority, false, false))
	metas = append(metas, solana.NewAccountMeta(a.Program, false, false))
	return metas
}

func BuildSetReservedFeeRecipients(accounts SetReservedFeeRecipientsAccounts, args SetReservedFeeRecipientsArgs) (solana.Instruction, error) {
	buf := bytes.NewBuffer(make([]byte, 0, 128))
	buf.Write(SetReservedFeeRecipientsDiscriminator)
	if err := bin.NewBorshEncoder(buf).Encode(args); err != nil {
		return nil, fmt.Errorf("encode args: %w", err)
	}
	data := buf.Bytes()
	return solana.NewInstruction(ProgramKey, accounts.ToAccountMetas(), data), nil
}

func DeriveSetReservedFeeRecipientsGlobalConfigPDA(accounts SetReservedFeeRecipientsAccounts, args SetReservedFeeRecipientsArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 1)
	seeds = append(seeds, []byte{103, 108, 111, 98, 97, 108, 95, 99, 111, 110, 102, 105, 103})
	return solana.FindProgramAddress(seeds, ProgramKey)
}

func DeriveSetReservedFeeRecipientsEventAuthorityPDA(accounts SetReservedFeeRecipientsAccounts, args SetReservedFeeRecipientsArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 1)
	seeds = append(seeds, []byte{95, 95, 101, 118, 101, 110, 116, 95, 97, 117, 116, 104, 111, 114, 105, 116, 121})
	return solana.FindProgramAddress(seeds, ProgramKey)
}

var SyncUserVolumeAccumulatorDiscriminator = []byte{86, 31, 192, 87, 163, 87, 79, 238}

type SyncUserVolumeAccumulatorArgs struct{}

type SyncUserVolumeAccumulatorAccounts struct {
	User                    solana.PublicKey
	GlobalVolumeAccumulator solana.PublicKey
	UserVolumeAccumulator   solana.PublicKey
	EventAuthority          solana.PublicKey
	Program                 solana.PublicKey
}

func (a SyncUserVolumeAccumulatorAccounts) ToAccountMetas() []*solana.AccountMeta {
	metas := make([]*solana.AccountMeta, 0, 5)
	metas = append(metas, solana.NewAccountMeta(a.User, false, false))
	metas = append(metas, solana.NewAccountMeta(a.GlobalVolumeAccumulator, false, false))
	metas = append(metas, solana.NewAccountMeta(a.UserVolumeAccumulator, true, false))
	metas = append(metas, solana.NewAccountMeta(a.EventAuthority, false, false))
	metas = append(metas, solana.NewAccountMeta(a.Program, false, false))
	return metas
}

func BuildSyncUserVolumeAccumulator(accounts SyncUserVolumeAccumulatorAccounts, args SyncUserVolumeAccumulatorArgs) (solana.Instruction, error) {
	buf := bytes.NewBuffer(make([]byte, 0, 128))
	buf.Write(SyncUserVolumeAccumulatorDiscriminator)
	data := buf.Bytes()
	return solana.NewInstruction(ProgramKey, accounts.ToAccountMetas(), data), nil
}

func DeriveSyncUserVolumeAccumulatorGlobalVolumeAccumulatorPDA(accounts SyncUserVolumeAccumulatorAccounts, args SyncUserVolumeAccumulatorArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 1)
	seeds = append(seeds, []byte{103, 108, 111, 98, 97, 108, 95, 118, 111, 108, 117, 109, 101, 95, 97, 99, 99, 117, 109, 117, 108, 97, 116, 111, 114})
	return solana.FindProgramAddress(seeds, ProgramKey)
}

func DeriveSyncUserVolumeAccumulatorUserVolumeAccumulatorPDA(accounts SyncUserVolumeAccumulatorAccounts, args SyncUserVolumeAccumulatorArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 2)
	seeds = append(seeds, []byte{117, 115, 101, 114, 95, 118, 111, 108, 117, 109, 101, 95, 97, 99, 99, 117, 109, 117, 108, 97, 116, 111, 114})
	seeds = append(seeds, accounts.User[:])
	return solana.FindProgramAddress(seeds, ProgramKey)
}

func DeriveSyncUserVolumeAccumulatorEventAuthorityPDA(accounts SyncUserVolumeAccumulatorAccounts, args SyncUserVolumeAccumulatorArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 1)
	seeds = append(seeds, []byte{95, 95, 101, 118, 101, 110, 116, 95, 97, 117, 116, 104, 111, 114, 105, 116, 121})
	return solana.FindProgramAddress(seeds, ProgramKey)
}

var ToggleMayhemModeDiscriminator = []byte{1, 9, 111, 208, 100, 31, 255, 163}

type ToggleMayhemModeArgs struct {
	Enabled bool `bin:"enabled"`
}

type ToggleMayhemModeAccounts struct {
	Admin          solana.PublicKey
	GlobalConfig   solana.PublicKey
	EventAuthority solana.PublicKey
	Program        solana.PublicKey
}

func (a ToggleMayhemModeAccounts) ToAccountMetas() []*solana.AccountMeta {
	metas := make([]*solana.AccountMeta, 0, 4)
	metas = append(metas, solana.NewAccountMeta(a.Admin, false, true))
	metas = append(metas, solana.NewAccountMeta(a.GlobalConfig, true, false))
	metas = append(metas, solana.NewAccountMeta(a.EventAuthority, false, false))
	metas = append(metas, solana.NewAccountMeta(a.Program, false, false))
	return metas
}

func BuildToggleMayhemMode(accounts ToggleMayhemModeAccounts, args ToggleMayhemModeArgs) (solana.Instruction, error) {
	buf := bytes.NewBuffer(make([]byte, 0, 128))
	buf.Write(ToggleMayhemModeDiscriminator)
	if err := bin.NewBorshEncoder(buf).Encode(args); err != nil {
		return nil, fmt.Errorf("encode args: %w", err)
	}
	data := buf.Bytes()
	return solana.NewInstruction(ProgramKey, accounts.ToAccountMetas(), data), nil
}

func DeriveToggleMayhemModeEventAuthorityPDA(accounts ToggleMayhemModeAccounts, args ToggleMayhemModeArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 1)
	seeds = append(seeds, []byte{95, 95, 101, 118, 101, 110, 116, 95, 97, 117, 116, 104, 111, 114, 105, 116, 121})
	return solana.FindProgramAddress(seeds, ProgramKey)
}

var UpdateAdminDiscriminator = []byte{161, 176, 40, 213, 60, 184, 179, 228}

type UpdateAdminArgs struct{}

type UpdateAdminAccounts struct {
	Admin          solana.PublicKey
	GlobalConfig   solana.PublicKey
	NewAdmin       solana.PublicKey
	EventAuthority solana.PublicKey
	Program        solana.PublicKey
}

func (a UpdateAdminAccounts) ToAccountMetas() []*solana.AccountMeta {
	metas := make([]*solana.AccountMeta, 0, 5)
	metas = append(metas, solana.NewAccountMeta(a.Admin, false, true))
	metas = append(metas, solana.NewAccountMeta(a.GlobalConfig, true, false))
	metas = append(metas, solana.NewAccountMeta(a.NewAdmin, false, false))
	metas = append(metas, solana.NewAccountMeta(a.EventAuthority, false, false))
	metas = append(metas, solana.NewAccountMeta(a.Program, false, false))
	return metas
}

func BuildUpdateAdmin(accounts UpdateAdminAccounts, args UpdateAdminArgs) (solana.Instruction, error) {
	buf := bytes.NewBuffer(make([]byte, 0, 128))
	buf.Write(UpdateAdminDiscriminator)
	data := buf.Bytes()
	return solana.NewInstruction(ProgramKey, accounts.ToAccountMetas(), data), nil
}

func DeriveUpdateAdminEventAuthorityPDA(accounts UpdateAdminAccounts, args UpdateAdminArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 1)
	seeds = append(seeds, []byte{95, 95, 101, 118, 101, 110, 116, 95, 97, 117, 116, 104, 111, 114, 105, 116, 121})
	return solana.FindProgramAddress(seeds, ProgramKey)
}

var UpdateFeeConfigDiscriminator = []byte{104, 184, 103, 242, 88, 151, 107, 20}

type UpdateFeeConfigArgs struct {
	LpFeeBasisPoints             uint64              `bin:"lp_fee_basis_points"`
	ProtocolFeeBasisPoints       uint64              `bin:"protocol_fee_basis_points"`
	ProtocolFeeRecipients        [8]solana.PublicKey `bin:"protocol_fee_recipients"`
	CoinCreatorFeeBasisPoints    uint64              `bin:"coin_creator_fee_basis_points"`
	AdminSetCoinCreatorAuthority solana.PublicKey    `bin:"admin_set_coin_creator_authority"`
}

type UpdateFeeConfigAccounts struct {
	Admin          solana.PublicKey
	GlobalConfig   solana.PublicKey
	EventAuthority solana.PublicKey
	Program        solana.PublicKey
}

func (a UpdateFeeConfigAccounts) ToAccountMetas() []*solana.AccountMeta {
	metas := make([]*solana.AccountMeta, 0, 4)
	metas = append(metas, solana.NewAccountMeta(a.Admin, false, true))
	metas = append(metas, solana.NewAccountMeta(a.GlobalConfig, true, false))
	metas = append(metas, solana.NewAccountMeta(a.EventAuthority, false, false))
	metas = append(metas, solana.NewAccountMeta(a.Program, false, false))
	return metas
}

func BuildUpdateFeeConfig(accounts UpdateFeeConfigAccounts, args UpdateFeeConfigArgs) (solana.Instruction, error) {
	buf := bytes.NewBuffer(make([]byte, 0, 128))
	buf.Write(UpdateFeeConfigDiscriminator)
	if err := bin.NewBorshEncoder(buf).Encode(args); err != nil {
		return nil, fmt.Errorf("encode args: %w", err)
	}
	data := buf.Bytes()
	return solana.NewInstruction(ProgramKey, accounts.ToAccountMetas(), data), nil
}

func DeriveUpdateFeeConfigEventAuthorityPDA(accounts UpdateFeeConfigAccounts, args UpdateFeeConfigArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 1)
	seeds = append(seeds, []byte{95, 95, 101, 118, 101, 110, 116, 95, 97, 117, 116, 104, 111, 114, 105, 116, 121})
	return solana.FindProgramAddress(seeds, ProgramKey)
}

var WithdrawDiscriminator = []byte{183, 18, 70, 156, 148, 109, 161, 34}

type WithdrawArgs struct {
	LpTokenAmountIn   uint64 `bin:"lp_token_amount_in"`
	MinBaseAmountOut  uint64 `bin:"min_base_amount_out"`
	MinQuoteAmountOut uint64 `bin:"min_quote_amount_out"`
}

type WithdrawAccounts struct {
	Pool                  solana.PublicKey
	GlobalConfig          solana.PublicKey
	User                  solana.PublicKey
	BaseMint              solana.PublicKey
	QuoteMint             solana.PublicKey
	LpMint                solana.PublicKey
	UserBaseTokenAccount  solana.PublicKey
	UserQuoteTokenAccount solana.PublicKey
	UserPoolTokenAccount  solana.PublicKey
	PoolBaseTokenAccount  solana.PublicKey
	PoolQuoteTokenAccount solana.PublicKey
	TokenProgram          solana.PublicKey
	Token2022Program      solana.PublicKey
	EventAuthority        solana.PublicKey
	Program               solana.PublicKey
}

func (a WithdrawAccounts) ToAccountMetas() []*solana.AccountMeta {
	metas := make([]*solana.AccountMeta, 0, 15)
	metas = append(metas, solana.NewAccountMeta(a.Pool, true, false))
	metas = append(metas, solana.NewAccountMeta(a.GlobalConfig, false, false))
	metas = append(metas, solana.NewAccountMeta(a.User, false, true))
	metas = append(metas, solana.NewAccountMeta(a.BaseMint, false, false))
	metas = append(metas, solana.NewAccountMeta(a.QuoteMint, false, false))
	metas = append(metas, solana.NewAccountMeta(a.LpMint, true, false))
	metas = append(metas, solana.NewAccountMeta(a.UserBaseTokenAccount, true, false))
	metas = append(metas, solana.NewAccountMeta(a.UserQuoteTokenAccount, true, false))
	metas = append(metas, solana.NewAccountMeta(a.UserPoolTokenAccount, true, false))
	metas = append(metas, solana.NewAccountMeta(a.PoolBaseTokenAccount, true, false))
	metas = append(metas, solana.NewAccountMeta(a.PoolQuoteTokenAccount, true, false))
	var defaultWithdrawTokenProgram = func() solana.PublicKey {
		return solana.MustPublicKeyFromBase58("TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA")
	}

	metas = append(metas, solana.NewAccountMeta(defaultWithdrawTokenProgram(), false, false))
	var defaultWithdrawToken2022Program = func() solana.PublicKey {
		return solana.MustPublicKeyFromBase58("TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb")
	}

	metas = append(metas, solana.NewAccountMeta(defaultWithdrawToken2022Program(), false, false))
	metas = append(metas, solana.NewAccountMeta(a.EventAuthority, false, false))
	metas = append(metas, solana.NewAccountMeta(a.Program, false, false))
	return metas
}

func BuildWithdraw(accounts WithdrawAccounts, args WithdrawArgs) (solana.Instruction, error) {
	buf := bytes.NewBuffer(make([]byte, 0, 128))
	buf.Write(WithdrawDiscriminator)
	if err := bin.NewBorshEncoder(buf).Encode(args); err != nil {
		return nil, fmt.Errorf("encode args: %w", err)
	}
	data := buf.Bytes()
	return solana.NewInstruction(ProgramKey, accounts.ToAccountMetas(), data), nil
}

func DeriveWithdrawEventAuthorityPDA(accounts WithdrawAccounts, args WithdrawArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 1)
	seeds = append(seeds, []byte{95, 95, 101, 118, 101, 110, 116, 95, 97, 117, 116, 104, 111, 114, 105, 116, 121})
	return solana.FindProgramAddress(seeds, ProgramKey)
}
