// Code generated by internal/gen; DO NOT EDIT.

package pumpamm

import (
	bin "github.com/gagliardetto/binary"
	"github.com/gagliardetto/solana-go"
)

type AdminSetCoinCreatorEvent struct {
	Timestamp                    int64            `bin:"timestamp"`
	AdminSetCoinCreatorAuthority solana.PublicKey `bin:"admin_set_coin_creator_authority"`
	BaseMint                     solana.PublicKey `bin:"base_mint"`
	Pool                         solana.PublicKey `bin:"pool"`
	OldCoinCreator               solana.PublicKey `bin:"old_coin_creator"`
	NewCoinCreator               solana.PublicKey `bin:"new_coin_creator"`
}

type AdminUpdateTokenIncentivesEvent struct {
	StartTime         int64            `bin:"start_time"`
	EndTime           int64            `bin:"end_time"`
	DayNumber         uint64           `bin:"day_number"`
	TokenSupplyPerDay uint64           `bin:"token_supply_per_day"`
	Mint              solana.PublicKey `bin:"mint"`
	SecondsInADay     int64            `bin:"seconds_in_a_day"`
	Timestamp         int64            `bin:"timestamp"`
}

type BondingCurve struct {
	VirtualTokenReserves uint64           `bin:"virtual_token_reserves"`
	VirtualSolReserves   uint64           `bin:"virtual_sol_reserves"`
	RealTokenReserves    uint64           `bin:"real_token_reserves"`
	RealSolReserves      uint64           `bin:"real_sol_reserves"`
	TokenTotalSupply     uint64           `bin:"token_total_supply"`
	Complete             bool             `bin:"complete"`
	Creator              solana.PublicKey `bin:"creator"`
	IsMayhemMode         bool             `bin:"is_mayhem_mode"`
	IsCashbackCoin       bool             `bin:"is_cashback_coin"`
}

type BoostBuyAndBurnEvent struct {
	Timestamp              int64            `bin:"timestamp"`
	Mint                   solana.PublicKey `bin:"mint"`
	BondingCurve           solana.PublicKey `bin:"bonding_curve"`
	Pool                   solana.PublicKey `bin:"pool"`
	Authority              solana.PublicKey `bin:"authority"`
	QuoteAmountInRequested uint64           `bin:"quote_amount_in_requested"`
	QuoteAmountInUsed      uint64           `bin:"quote_amount_in_used"`
	BaseAmountBurned       uint64           `bin:"base_amount_burned"`
	VirtualQuoteReserves   bin.Int128       `bin:"virtual_quote_reserves"`
	RealQuoteReservesAfter uint64           `bin:"real_quote_reserves_after"`
	BaseReservesAfter      uint64           `bin:"base_reserves_after"`
	BoostVaultRemaining    uint64           `bin:"boost_vault_remaining"`
}

type BuyEvent struct {
	Timestamp                        int64            `bin:"timestamp"`
	BaseAmountOut                    uint64           `bin:"base_amount_out"`
	MaxQuoteAmountIn                 uint64           `bin:"max_quote_amount_in"`
	UserBaseTokenReserves            uint64           `bin:"user_base_token_reserves"`
	UserQuoteTokenReserves           uint64           `bin:"user_quote_token_reserves"`
	PoolBaseTokenReserves            uint64           `bin:"pool_base_token_reserves"`
	PoolQuoteTokenReserves           uint64           `bin:"pool_quote_token_reserves"`
	QuoteAmountIn                    uint64           `bin:"quote_amount_in"`
	LpFeeBasisPoints                 uint64           `bin:"lp_fee_basis_points"`
	LpFee                            uint64           `bin:"lp_fee"`
	ProtocolFeeBasisPoints           uint64           `bin:"protocol_fee_basis_points"`
	ProtocolFee                      uint64           `bin:"protocol_fee"`
	QuoteAmountInWithLpFee           uint64           `bin:"quote_amount_in_with_lp_fee"`
	UserQuoteAmountIn                uint64           `bin:"user_quote_amount_in"`
	Pool                             solana.PublicKey `bin:"pool"`
	User                             solana.PublicKey `bin:"user"`
	UserBaseTokenAccount             solana.PublicKey `bin:"user_base_token_account"`
	UserQuoteTokenAccount            solana.PublicKey `bin:"user_quote_token_account"`
	ProtocolFeeRecipient             solana.PublicKey `bin:"protocol_fee_recipient"`
	ProtocolFeeRecipientTokenAccount solana.PublicKey `bin:"protocol_fee_recipient_token_account"`
	CoinCreator                      solana.PublicKey `bin:"coin_creator"`
	CoinCreatorFeeBasisPoints        uint64           `bin:"coin_creator_fee_basis_points"`
	CoinCreatorFee                   uint64           `bin:"coin_creator_fee"`
	TrackVolume                      bool             `bin:"track_volume"`
	TotalUnclaimedTokens             uint64           `bin:"total_unclaimed_tokens"`
	TotalClaimedTokens               uint64           `bin:"total_claimed_tokens"`
	CurrentSolVolume                 uint64           `bin:"current_sol_volume"`
	LastUpdateTimestamp              int64            `bin:"last_update_timestamp"`
	MinBaseAmountOut                 uint64           `bin:"min_base_amount_out"`
	IxName                           string           `bin:"ix_name"`
	CashbackFeeBasisPoints           uint64           `bin:"cashback_fee_basis_points"`
	Cashback                         uint64           `bin:"cashback"`
	BuybackFeeBasisPoints            uint64           `bin:"buyback_fee_basis_points"`
	BuybackFee                       uint64           `bin:"buyback_fee"`
	VirtualQuoteReserves             bin.Int128       `bin:"virtual_quote_reserves"`
	CanBoost                         bool             `bin:"can_boost"`
	BaseSupply                       uint64           `bin:"base_supply"`
}

type ClaimCashbackEvent struct {
	User                solana.PublicKey `bin:"user"`
	Amount              uint64           `bin:"amount"`
	Timestamp           int64            `bin:"timestamp"`
	TotalClaimed        uint64           `bin:"total_claimed"`
	TotalCashbackEarned uint64           `bin:"total_cashback_earned"`
}

type ClaimTokenIncentivesEvent struct {
	User               solana.PublicKey `bin:"user"`
	Mint               solana.PublicKey `bin:"mint"`
	Amount             uint64           `bin:"amount"`
	Timestamp          int64            `bin:"timestamp"`
	TotalClaimedTokens uint64           `bin:"total_claimed_tokens"`
	CurrentSolVolume   uint64           `bin:"current_sol_volume"`
}

type CloseUserVolumeAccumulatorEvent struct {
	User                 solana.PublicKey `bin:"user"`
	Timestamp            int64            `bin:"timestamp"`
	TotalUnclaimedTokens uint64           `bin:"total_unclaimed_tokens"`
	TotalClaimedTokens   uint64           `bin:"total_claimed_tokens"`
	CurrentSolVolume     uint64           `bin:"current_sol_volume"`
	LastUpdateTimestamp  int64            `bin:"last_update_timestamp"`
}

type CollectCoinCreatorFeeEvent struct {
	Timestamp               int64            `bin:"timestamp"`
	CoinCreator             solana.PublicKey `bin:"coin_creator"`
	CoinCreatorFee          uint64           `bin:"coin_creator_fee"`
	CoinCreatorVaultAta     solana.PublicKey `bin:"coin_creator_vault_ata"`
	CoinCreatorTokenAccount solana.PublicKey `bin:"coin_creator_token_account"`
}

type ConfigStatus uint8

const (
	ConfigStatusPaused ConfigStatus = iota
	ConfigStatusActive
)

type CreateConfigEvent struct {
	Timestamp                    int64               `bin:"timestamp"`
	Admin                        solana.PublicKey    `bin:"admin"`
	LpFeeBasisPoints             uint64              `bin:"lp_fee_basis_points"`
	ProtocolFeeBasisPoints       uint64              `bin:"protocol_fee_basis_points"`
	ProtocolFeeRecipients        [8]solana.PublicKey `bin:"protocol_fee_recipients"`
	CoinCreatorFeeBasisPoints    uint64              `bin:"coin_creator_fee_basis_points"`
	AdminSetCoinCreatorAuthority solana.PublicKey    `bin:"admin_set_coin_creator_authority"`
}

type CreatePoolEvent struct {
	Timestamp             int64            `bin:"timestamp"`
	Index                 uint16           `bin:"index"`
	Creator               solana.PublicKey `bin:"creator"`
	BaseMint              solana.PublicKey `bin:"base_mint"`
	QuoteMint             solana.PublicKey `bin:"quote_mint"`
	BaseMintDecimals      uint8            `bin:"base_mint_decimals"`
	QuoteMintDecimals     uint8            `bin:"quote_mint_decimals"`
	BaseAmountIn          uint64           `bin:"base_amount_in"`
	QuoteAmountIn         uint64           `bin:"quote_amount_in"`
	PoolBaseAmount        uint64           `bin:"pool_base_amount"`
	PoolQuoteAmount       uint64           `bin:"pool_quote_amount"`
	MinimumLiquidity      uint64           `bin:"minimum_liquidity"`
	InitialLiquidity      uint64           `bin:"initial_liquidity"`
	LpTokenAmountOut      uint64           `bin:"lp_token_amount_out"`
	PoolBump              uint8            `bin:"pool_bump"`
	Pool                  solana.PublicKey `bin:"pool"`
	LpMint                solana.PublicKey `bin:"lp_mint"`
	UserBaseTokenAccount  solana.PublicKey `bin:"user_base_token_account"`
	UserQuoteTokenAccount solana.PublicKey `bin:"user_quote_token_account"`
	CoinCreator           solana.PublicKey `bin:"coin_creator"`
	IsMayhemMode          bool             `bin:"is_mayhem_mode"`
}

type DepositEvent struct {
	Timestamp              int64            `bin:"timestamp"`
	LpTokenAmountOut       uint64           `bin:"lp_token_amount_out"`
	MaxBaseAmountIn        uint64           `bin:"max_base_amount_in"`
	MaxQuoteAmountIn       uint64           `bin:"max_quote_amount_in"`
	UserBaseTokenReserves  uint64           `bin:"user_base_token_reserves"`
	UserQuoteTokenReserves uint64           `bin:"user_quote_token_reserves"`
	PoolBaseTokenReserves  uint64           `bin:"pool_base_token_reserves"`
	PoolQuoteTokenReserves uint64           `bin:"pool_quote_token_reserves"`
	BaseAmountIn           uint64           `bin:"base_amount_in"`
	QuoteAmountIn          uint64           `bin:"quote_amount_in"`
	LpMintSupply           uint64           `bin:"lp_mint_supply"`
	Pool                   solana.PublicKey `bin:"pool"`
	User                   solana.PublicKey `bin:"user"`
	UserBaseTokenAccount   solana.PublicKey `bin:"user_base_token_account"`
	UserQuoteTokenAccount  solana.PublicKey `bin:"user_quote_token_account"`
	UserPoolTokenAccount   solana.PublicKey `bin:"user_pool_token_account"`
}

type DisableEvent struct {
	Timestamp         int64            `bin:"timestamp"`
	Admin             solana.PublicKey `bin:"admin"`
	DisableCreatePool bool             `bin:"disable_create_pool"`
	DisableDeposit    bool             `bin:"disable_deposit"`
	DisableWithdraw   bool             `bin:"disable_withdraw"`
	DisableBuy        bool             `bin:"disable_buy"`
	DisableSell       bool             `bin:"disable_sell"`
}

type ExtendAccountEvent struct {
	Timestamp   int64            `bin:"timestamp"`
	Account     solana.PublicKey `bin:"account"`
	User        solana.PublicKey `bin:"user"`
	CurrentSize uint64           `bin:"current_size"`
	NewSize     uint64           `bin:"new_size"`
}

type FeeConfig struct {
	Bump           uint8            `bin:"bump"`
	Admin          solana.PublicKey `bin:"admin"`
	FlatFees       Fees             `bin:"flat_fees"`
	FeeTiers       []FeeTier        `bin:"fee_tiers"`
	StableFeeTiers []FeeTier        `bin:"stable_fee_tiers"`
}

type FeeTier struct {
	MarketCapLamportsThreshold bin.Uint128 `bin:"market_cap_lamports_threshold"`
	Fees                       Fees        `bin:"fees"`
}

type Fees struct {
	LpFeeBps       uint64 `bin:"lp_fee_bps"`
	ProtocolFeeBps uint64 `bin:"protocol_fee_bps"`
	CreatorFeeBps  uint64 `bin:"creator_fee_bps"`
}

type GlobalConfig struct {
	Admin                        solana.PublicKey    `bin:"admin"`
	LpFeeBasisPoints             uint64              `bin:"lp_fee_basis_points"`
	ProtocolFeeBasisPoints       uint64              `bin:"protocol_fee_basis_points"`
	DisableFlags                 uint8               `bin:"disable_flags"`
	ProtocolFeeRecipients        [8]solana.PublicKey `bin:"protocol_fee_recipients"`
	CoinCreatorFeeBasisPoints    uint64              `bin:"coin_creator_fee_basis_points"`
	AdminSetCoinCreatorAuthority solana.PublicKey    `bin:"admin_set_coin_creator_authority"`
	WhitelistPda                 solana.PublicKey    `bin:"whitelist_pda"`
	ReservedFeeRecipient         solana.PublicKey    `bin:"reserved_fee_recipient"`
	MayhemModeEnabled            bool                `bin:"mayhem_mode_enabled"`
	ReservedFeeRecipients        [7]solana.PublicKey `bin:"reserved_fee_recipients"`
	IsCashbackEnabled            bool                `bin:"is_cashback_enabled"`
	BuybackFeeRecipients         [8]solana.PublicKey `bin:"buyback_fee_recipients"`
	BuybackBasisPoints           uint64              `bin:"buyback_basis_points"`
	BoostAuthority               solana.PublicKey    `bin:"boost_authority"`
	BoostEnabled                 bool                `bin:"boost_enabled"`
}

type GlobalVolumeAccumulator struct {
	StartTime        int64            `bin:"start_time"`
	EndTime          int64            `bin:"end_time"`
	SecondsInADay    int64            `bin:"seconds_in_a_day"`
	Mint             solana.PublicKey `bin:"mint"`
	TotalTokenSupply [30]uint64       `bin:"total_token_supply"`
	SolVolumes       [30]uint64       `bin:"sol_volumes"`
}

type InitBoostEvent struct {
	Timestamp              int64            `bin:"timestamp"`
	Mint                   solana.PublicKey `bin:"mint"`
	BondingCurve           solana.PublicKey `bin:"bonding_curve"`
	Pool                   solana.PublicKey `bin:"pool"`
	VirtualQuoteReserves   bin.Int128       `bin:"virtual_quote_reserves"`
	RealQuoteReservesAfter uint64           `bin:"real_quote_reserves_after"`
}

type InitUserVolumeAccumulatorEvent struct {
	Payer     solana.PublicKey `bin:"payer"`
	User      solana.PublicKey `bin:"user"`
	Timestamp int64            `bin:"timestamp"`
}

type MigratePoolCoinCreatorEvent struct {
	Timestamp      int64            `bin:"timestamp"`
	BaseMint       solana.PublicKey `bin:"base_mint"`
	Pool           solana.PublicKey `bin:"pool"`
	SharingConfig  solana.PublicKey `bin:"sharing_config"`
	OldCoinCreator solana.PublicKey `bin:"old_coin_creator"`
	NewCoinCreator solana.PublicKey `bin:"new_coin_creator"`
}

type OptionBool struct {
	Field0 bool `bin:"Field0"`
}

type Pool struct {
	PoolBump              uint8            `bin:"pool_bump"`
	Index                 uint16           `bin:"index"`
	Creator               solana.PublicKey `bin:"creator"`
	BaseMint              solana.PublicKey `bin:"base_mint"`
	QuoteMint             solana.PublicKey `bin:"quote_mint"`
	LpMint                solana.PublicKey `bin:"lp_mint"`
	PoolBaseTokenAccount  solana.PublicKey `bin:"pool_base_token_account"`
	PoolQuoteTokenAccount solana.PublicKey `bin:"pool_quote_token_account"`
	LpSupply              uint64           `bin:"lp_supply"`
	CoinCreator           solana.PublicKey `bin:"coin_creator"`
	IsMayhemMode          bool             `bin:"is_mayhem_mode"`
	IsCashbackCoin        bool             `bin:"is_cashback_coin"`
	VirtualQuoteReserves  bin.Int128       `bin:"virtual_quote_reserves"`
}

type ReservedFeeRecipientsEvent struct {
	Timestamp             int64               `bin:"timestamp"`
	ReservedFeeRecipient  solana.PublicKey    `bin:"reserved_fee_recipient"`
	ReservedFeeRecipients [7]solana.PublicKey `bin:"reserved_fee_recipients"`
}

type SellEvent struct {
	Timestamp                        int64            `bin:"timestamp"`
	BaseAmountIn                     uint64           `bin:"base_amount_in"`
	MinQuoteAmountOut                uint64           `bin:"min_quote_amount_out"`
	UserBaseTokenReserves            uint64           `bin:"user_base_token_reserves"`
	UserQuoteTokenReserves           uint64           `bin:"user_quote_token_reserves"`
	PoolBaseTokenReserves            uint64           `bin:"pool_base_token_reserves"`
	PoolQuoteTokenReserves           uint64           `bin:"pool_quote_token_reserves"`
	QuoteAmountOut                   uint64           `bin:"quote_amount_out"`
	LpFeeBasisPoints                 uint64           `bin:"lp_fee_basis_points"`
	LpFee                            uint64           `bin:"lp_fee"`
	ProtocolFeeBasisPoints           uint64           `bin:"protocol_fee_basis_points"`
	ProtocolFee                      uint64           `bin:"protocol_fee"`
	QuoteAmountOutWithoutLpFee       uint64           `bin:"quote_amount_out_without_lp_fee"`
	UserQuoteAmountOut               uint64           `bin:"user_quote_amount_out"`
	Pool                             solana.PublicKey `bin:"pool"`
	User                             solana.PublicKey `bin:"user"`
	UserBaseTokenAccount             solana.PublicKey `bin:"user_base_token_account"`
	UserQuoteTokenAccount            solana.PublicKey `bin:"user_quote_token_account"`
	ProtocolFeeRecipient             solana.PublicKey `bin:"protocol_fee_recipient"`
	ProtocolFeeRecipientTokenAccount solana.PublicKey `bin:"protocol_fee_recipient_token_account"`
	CoinCreator                      solana.PublicKey `bin:"coin_creator"`
	CoinCreatorFeeBasisPoints        uint64           `bin:"coin_creator_fee_basis_points"`
	CoinCreatorFee                   uint64           `bin:"coin_creator_fee"`
	CashbackFeeBasisPoints           uint64           `bin:"cashback_fee_basis_points"`
	Cashback                         uint64           `bin:"cashback"`
	BuybackFeeBasisPoints            uint64           `bin:"buyback_fee_basis_points"`
	BuybackFee                       uint64           `bin:"buyback_fee"`
	VirtualQuoteReserves             bin.Int128       `bin:"virtual_quote_reserves"`
	CanBoost                         bool             `bin:"can_boost"`
	BaseSupply                       uint64           `bin:"base_supply"`
}

type SetBondingCurveCoinCreatorEvent struct {
	Timestamp    int64            `bin:"timestamp"`
	BaseMint     solana.PublicKey `bin:"base_mint"`
	Pool         solana.PublicKey `bin:"pool"`
	BondingCurve solana.PublicKey `bin:"bonding_curve"`
	CoinCreator  solana.PublicKey `bin:"coin_creator"`
}

type SetBoostAuthorityEvent struct {
	Timestamp         int64            `bin:"timestamp"`
	Admin             solana.PublicKey `bin:"admin"`
	OldBoostAuthority solana.PublicKey `bin:"old_boost_authority"`
	NewBoostAuthority solana.PublicKey `bin:"new_boost_authority"`
}

type SetMetaplexCoinCreatorEvent struct {
	Timestamp   int64            `bin:"timestamp"`
	BaseMint    solana.PublicKey `bin:"base_mint"`
	Pool        solana.PublicKey `bin:"pool"`
	Metadata    solana.PublicKey `bin:"metadata"`
	CoinCreator solana.PublicKey `bin:"coin_creator"`
}

type Shareholder struct {
	Address  solana.PublicKey `bin:"address"`
	ShareBps uint16           `bin:"share_bps"`
}

type SharingConfig struct {
	Bump         uint8            `bin:"bump"`
	Version      uint8            `bin:"version"`
	Status       ConfigStatus     `bin:"status"`
	Mint         solana.PublicKey `bin:"mint"`
	Admin        solana.PublicKey `bin:"admin"`
	AdminRevoked bool             `bin:"admin_revoked"`
	Shareholders []Shareholder    `bin:"shareholders"`
}

type SyncUserVolumeAccumulatorEvent struct {
	User                     solana.PublicKey `bin:"user"`
	TotalClaimedTokensBefore uint64           `bin:"total_claimed_tokens_before"`
	TotalClaimedTokensAfter  uint64           `bin:"total_claimed_tokens_after"`
	Timestamp                int64            `bin:"timestamp"`
}

type UpdateAdminEvent struct {
	Timestamp int64            `bin:"timestamp"`
	Admin     solana.PublicKey `bin:"admin"`
	NewAdmin  solana.PublicKey `bin:"new_admin"`
}

type UpdateFeeConfigEvent struct {
	Timestamp                    int64               `bin:"timestamp"`
	Admin                        solana.PublicKey    `bin:"admin"`
	LpFeeBasisPoints             uint64              `bin:"lp_fee_basis_points"`
	ProtocolFeeBasisPoints       uint64              `bin:"protocol_fee_basis_points"`
	ProtocolFeeRecipients        [8]solana.PublicKey `bin:"protocol_fee_recipients"`
	CoinCreatorFeeBasisPoints    uint64              `bin:"coin_creator_fee_basis_points"`
	AdminSetCoinCreatorAuthority solana.PublicKey    `bin:"admin_set_coin_creator_authority"`
}

type UserVolumeAccumulator struct {
	User                  solana.PublicKey `bin:"user"`
	NeedsClaim            bool             `bin:"needs_claim"`
	TotalUnclaimedTokens  uint64           `bin:"total_unclaimed_tokens"`
	TotalClaimedTokens    uint64           `bin:"total_claimed_tokens"`
	CurrentSolVolume      uint64           `bin:"current_sol_volume"`
	LastUpdateTimestamp   int64            `bin:"last_update_timestamp"`
	HasTotalClaimedTokens bool             `bin:"has_total_claimed_tokens"`
	CashbackEarned        uint64           `bin:"cashback_earned"`
	TotalCashbackClaimed  uint64           `bin:"total_cashback_claimed"`
}

type WithdrawEvent struct {
	Timestamp              int64            `bin:"timestamp"`
	LpTokenAmountIn        uint64           `bin:"lp_token_amount_in"`
	MinBaseAmountOut       uint64           `bin:"min_base_amount_out"`
	MinQuoteAmountOut      uint64           `bin:"min_quote_amount_out"`
	UserBaseTokenReserves  uint64           `bin:"user_base_token_reserves"`
	UserQuoteTokenReserves uint64           `bin:"user_quote_token_reserves"`
	PoolBaseTokenReserves  uint64           `bin:"pool_base_token_reserves"`
	PoolQuoteTokenReserves uint64           `bin:"pool_quote_token_reserves"`
	BaseAmountOut          uint64           `bin:"base_amount_out"`
	QuoteAmountOut         uint64           `bin:"quote_amount_out"`
	LpMintSupply           uint64           `bin:"lp_mint_supply"`
	Pool                   solana.PublicKey `bin:"pool"`
	User                   solana.PublicKey `bin:"user"`
	UserBaseTokenAccount   solana.PublicKey `bin:"user_base_token_account"`
	UserQuoteTokenAccount  solana.PublicKey `bin:"user_quote_token_account"`
	UserPoolTokenAccount   solana.PublicKey `bin:"user_pool_token_account"`
}
