// Code generated by internal/gen; DO NOT EDIT.
// Generated at 2025-12-07T17:54:48Z

package pump

type ProgramError struct {
	Code uint32
	Name string
	Msg  string
}

var Errors = map[uint32]ProgramError{
	6000: {Code: 6000, Name: "NotAuthorized", Msg: "The given account is not authorized to execute this instruction."},
	6001: {Code: 6001, Name: "AlreadyInitialized", Msg: "The program is already initialized."},
	6002: {Code: 6002, Name: "TooMuchSolRequired", Msg: "slippage: Too much SOL required to buy the given amount of tokens."},
	6003: {Code: 6003, Name: "TooLittleSolReceived", Msg: "slippage: Too little SOL received to sell the given amount of tokens."},
	6004: {Code: 6004, Name: "MintDoesNotMatchBondingCurve", Msg: "The mint does not match the bonding curve."},
	6005: {Code: 6005, Name: "BondingCurveComplete", Msg: "The bonding curve has completed and liquidity migrated to raydium."},
	6006: {Code: 6006, Name: "BondingCurveNotComplete", Msg: "The bonding curve has not completed."},
	6007: {Code: 6007, Name: "NotInitialized", Msg: "The program is not initialized."},
	6008: {Code: 6008, Name: "WithdrawTooFrequent", Msg: "Withdraw too frequent"},
	6009: {Code: 6009, Name: "NewSizeShouldBeGreaterThanCurrentSize", Msg: "new_size should be > current_size"},
	6010: {Code: 6010, Name: "AccountTypeNotSupported", Msg: "Account type not supported"},
	6011: {Code: 6011, Name: "InitialRealTokenReservesShouldBeLessThanTokenTotalSupply", Msg: "initial_real_token_reserves should be less than token_total_supply"},
	6012: {Code: 6012, Name: "InitialVirtualTokenReservesShouldBeGreaterThanInitialRealTokenReserves", Msg: "initial_virtual_token_reserves should be greater than initial_real_token_reserves"},
	6013: {Code: 6013, Name: "FeeBasisPointsGreaterThanMaximum", Msg: "fee_basis_points greater than maximum"},
	6014: {Code: 6014, Name: "AllZerosWithdrawAuthority", Msg: "Withdraw authority cannot be set to System Program ID"},
	6015: {Code: 6015, Name: "PoolMigrationFeeShouldBeLessThanFinalRealSolReserves", Msg: "pool_migration_fee should be less than final_real_sol_reserves"},
	6016: {Code: 6016, Name: "PoolMigrationFeeShouldBeGreaterThanCreatorFeePlusMaxMigrateFees", Msg: "pool_migration_fee should be greater than creator_fee + MAX_MIGRATE_FEES"},
	6017: {Code: 6017, Name: "DisabledWithdraw", Msg: "Migrate instruction is disabled"},
	6018: {Code: 6018, Name: "DisabledMigrate", Msg: "Migrate instruction is disabled"},
	6019: {Code: 6019, Name: "InvalidCreator", Msg: "Invalid creator pubkey"},
	6020: {Code: 6020, Name: "BuyZeroAmount", Msg: "Buy zero amount"},
	6021: {Code: 6021, Name: "NotEnoughTokensToBuy", Msg: "Not enough tokens to buy"},
	6022: {Code: 6022, Name: "SellZeroAmount", Msg: "Sell zero amount"},
	6023: {Code: 6023, Name: "NotEnoughTokensToSell", Msg: "Not enough tokens to sell"},
	6024: {Code: 6024, Name: "Overflow", Msg: "Overflow"},
	6025: {Code: 6025, Name: "Truncation", Msg: "Truncation"},
	6026: {Code: 6026, Name: "DivisionByZero", Msg: "Division by zero"},
	6027: {Code: 6027, Name: "NotEnoughRemainingAccounts", Msg: "Not enough remaining accounts"},
	6028: {Code: 6028, Name: "AllFeeRecipientsShouldBeNonZero", Msg: "All fee recipients should be non-zero"},
	6029: {Code: 6029, Name: "UnsortedNotUniqueFeeRecipients", Msg: "Unsorted or not unique fee recipients"},
	6030: {Code: 6030, Name: "CreatorShouldNotBeZero", Msg: "Creator should not be zero"},
	6031: {Code: 6031, Name: "StartTimeInThePast", Msg: ""},
	6032: {Code: 6032, Name: "EndTimeInThePast", Msg: ""},
	6033: {Code: 6033, Name: "EndTimeBeforeStartTime", Msg: ""},
	6034: {Code: 6034, Name: "TimeRangeTooLarge", Msg: ""},
	6035: {Code: 6035, Name: "EndTimeBeforeCurrentDay", Msg: ""},
	6036: {Code: 6036, Name: "SupplyUpdateForFinishedRange", Msg: ""},
	6037: {Code: 6037, Name: "DayIndexAfterEndIndex", Msg: ""},
	6038: {Code: 6038, Name: "DayInActiveRange", Msg: ""},
	6039: {Code: 6039, Name: "InvalidIncentiveMint", Msg: ""},
	6040: {Code: 6040, Name: "BuyNotEnoughSolToCoverRent", Msg: "Buy: Not enough SOL to cover for rent exemption."},
	6041: {Code: 6041, Name: "BuyNotEnoughSolToCoverFees", Msg: "Buy: Not enough SOL to cover for fees."},
	6042: {Code: 6042, Name: "BuySlippageBelowMinTokensOut", Msg: "Slippage: Would buy less tokens than expected min_tokens_out"},
	6043: {Code: 6043, Name: "NameTooLong", Msg: ""},
	6044: {Code: 6044, Name: "SymbolTooLong", Msg: ""},
	6045: {Code: 6045, Name: "UriTooLong", Msg: ""},
	6046: {Code: 6046, Name: "CreateV2Disabled", Msg: ""},
	6047: {Code: 6047, Name: "CpitializeMayhemFailed", Msg: ""},
	6048: {Code: 6048, Name: "MayhemModeDisabled", Msg: ""},
}

func ErrorFromCode(code uint32) (ProgramError, bool) {
	err, ok := Errors[code]
	return err, ok
}
