// Code generated by internal/gen; DO NOT EDIT.

package pump

type ProgramError struct {
	Code uint32
	Name string
	Msg  string
}

var Errors = map[uint32]ProgramError{
	6000: {Code: 6000, Name: "NotAuthorized", Msg: "The given account is not authorized to execute this instruction."},
	6001: {Code: 6001, Name: "AlreadyInitialized", Msg: "The program is already initialized."},
	6002: {Code: 6002, Name: "TooMuchSolRequired", Msg: "slippage: Too much SOL required to buy the given amount of tokens."},
	6003: {Code: 6003, Name: "TooLittleSolReceived", Msg: "slippage: Too little SOL received to sell the given amount of tokens."},
	6004: {Code: 6004, Name: "MintDoesNotMatchBondingCurve", Msg: "The mint does not match the bonding curve."},
	6005: {Code: 6005, Name: "BondingCurveComplete", Msg: "The bonding curve has completed and liquidity migrated to raydium."},
	6006: {Code: 6006, Name: "BondingCurveNotComplete", Msg: "The bonding curve has not completed."},
	6007: {Code: 6007, Name: "NotInitialized", Msg: "The program is not initialized."},
	6008: {Code: 6008, Name: "WithdrawTooFrequent", Msg: "Withdraw too frequent"},
	6009: {Code: 6009, Name: "NewSizeShouldBeGreaterThanCurrentSize", Msg: "new_size should be > current_size"},
	6010: {Code: 6010, Name: "AccountTypeNotSupported", Msg: "Account type not supported"},
	6011: {Code: 6011, Name: "InitialRealTokenReservesShouldBeLessThanTokenTotalSupply", Msg: "initial_real_token_reserves should be less than token_total_supply"},
	6012: {Code: 6012, Name: "InitialVirtualTokenReservesShouldBeGreaterThanInitialRealTokenReserves", Msg: "initial_virtual_token_reserves should be greater than initial_real_token_reserves"},
	6013: {Code: 6013, Name: "FeeBasisPointsGreaterThanMaximum", Msg: "fee_basis_points greater than maximum"},
	6014: {Code: 6014, Name: "AllZerosWithdrawAuthority", Msg: "Withdraw authority cannot be set to System Program ID"},
	6015: {Code: 6015, Name: "PoolMigrationFeeShouldBeLessThanFinalRealSolReserves", Msg: "pool_migration_fee should be less than final_real_sol_reserves"},
	6016: {Code: 6016, Name: "PoolMigrationFeeShouldBeGreaterThanCreatorFeePlusMaxMigrateFees", Msg: "pool_migration_fee should be greater than creator_fee + MAX_MIGRATE_FEES"},
	6017: {Code: 6017, Name: "DisabledWithdraw", Msg: "Migrate instruction is disabled"},
	6018: {Code: 6018, Name: "DisabledMigrate", Msg: "Migrate instruction is disabled"},
	6019: {Code: 6019, Name: "InvalidCreator", Msg: "Invalid creator pubkey"},
	6020: {Code: 6020, Name: "BuyZeroAmount", Msg: "Buy zero amount"},
	6021: {Code: 6021, Name: "NotEnoughTokensToBuy", Msg: "Not enough tokens to buy"},
	6022: {Code: 6022, Name: "SellZeroAmount", Msg: "Sell zero amount"},
	6023: {Code: 6023, Name: "NotEnoughTokensToSell", Msg: "Not enough tokens to sell"},
	6024: {Code: 6024, Name: "Overflow", Msg: "Overflow"},
	6025: {Code: 6025, Name: "Truncation", Msg: "Truncation"},
	6026: {Code: 6026, Name: "DivisionByZero", Msg: "Division by zero"},
	6027: {Code: 6027, Name: "NotEnoughRemainingAccounts", Msg: "Not enough remaining accounts"},
	6028: {Code: 6028, Name: "AllFeeRecipientsShouldBeNonZero", Msg: "All fee recipients should be non-zero"},
	6029: {Code: 6029, Name: "UnsortedNotUniqueFeeRecipients", Msg: "Unsorted or not unique fee recipients"},
	6030: {Code: 6030, Name: "CreatorShouldNotBeZero", Msg: "Creator should not be zero"},
	6031: {Code: 6031, Name: "StartTimeInThePast", Msg: ""},
	6032: {Code: 6032, Name: "EndTimeInThePast", Msg: ""},
	6033: {Code: 6033, Name: "EndTimeBeforeStartTime", Msg: ""},
	6034: {Code: 6034, Name: "TimeRangeTooLarge", Msg: ""},
	6035: {Code: 6035, Name: "EndTimeBeforeCurrentDay", Msg: ""},
	6036: {Code: 6036, Name: "SupplyUpdateForFinishedRange", Msg: ""},
	6037: {Code: 6037, Name: "DayIndexAfterEndIndex", Msg: ""},
	6038: {Code: 6038, Name: "DayInActiveRange", Msg: ""},
	6039: {Code: 6039, Name: "InvalidIncentiveMint", Msg: ""},
	6040: {Code: 6040, Name: "BuyNotEnoughSolToCoverRent", Msg: "Buy: Not enough SOL to cover for rent exemption."},
	6041: {Code: 6041, Name: "BuyNotEnoughSolToCoverFees", Msg: "Buy: Not enough SOL to cover for fees."},
	6042: {Code: 6042, Name: "BuySlippageBelowMinTokensOut", Msg: "Slippage: Would buy less tokens than expected min_tokens_out"},
	6043: {Code: 6043, Name: "NameTooLong", Msg: ""},
	6044: {Code: 6044, Name: "SymbolTooLong", Msg: ""},
	6045: {Code: 6045, Name: "UriTooLong", Msg: ""},
	6046: {Code: 6046, Name: "CreateV2Disabled", Msg: ""},
	6047: {Code: 6047, Name: "CpitializeMayhemFailed", Msg: ""},
	6048: {Code: 6048, Name: "MayhemModeDisabled", Msg: ""},
	6049: {Code: 6049, Name: "CreatorMigratedToSharingConfig", Msg: "creator has been migrated to sharing config, use pump_fees::reset_fee_sharing_config instead"},
	6050: {Code: 6050, Name: "UnableToDistributeCreatorVaultMigratedToSharingConfig", Msg: "creator_vault has been migrated to sharing config, use pump:distribute_creator_fees instead"},
	6051: {Code: 6051, Name: "SharingConfigNotActive", Msg: "Sharing config is not active"},
	6052: {Code: 6052, Name: "UnableToDistributeCreatorFeesToExecutableRecipient", Msg: "The recipient account is executable, so it cannot receive lamports, remove it from the team first"},
	6053: {Code: 6053, Name: "BondingCurveAndSharingConfigCreatorMismatch", Msg: "Bonding curve creator does not match sharing config"},
	6054: {Code: 6054, Name: "ShareholdersAndRemainingAccountsMismatch", Msg: "Remaining accounts do not match shareholders, make sure to pass exactly the same pubkeys in the same order"},
	6055: {Code: 6055, Name: "InvalidShareBps", Msg: "Share bps must be greater than 0"},
	6056: {Code: 6056, Name: "CashbackNotEnabled", Msg: "Cashback is not enabled"},
	6057: {Code: 6057, Name: "BuybackFeeRecipientNotAuthorized", Msg: "Buyback fee recipient not authorized"},
	6058: {Code: 6058, Name: "AllBuybackFeeRecipientsShouldBeNonZero", Msg: ""},
	6059: {Code: 6059, Name: "NotUniqueBuybackFeeRecipients", Msg: ""},
	6060: {Code: 6060, Name: "BuybackBasisPointsOutOfRange", Msg: "buyback_basis_points must be <= 10_000"},
	6061: {Code: 6061, Name: "WrongBuybackFeeRecipientsCount", Msg: "buyback fee recipients require exactly 8 remaining accounts (or none)"},
	6062: {Code: 6062, Name: "BuybackFeeRecipientMissing", Msg: ""},
	6063: {Code: 6063, Name: "UnsupportedQuoteMint", Msg: "Unsupported quote mint"},
	6064: {Code: 6064, Name: "InvalidQuoteTokenProgram", Msg: "Create v2: quote token program must be legacy SPL Token"},
	6065: {Code: 6065, Name: "InvalidAssociatedQuoteBondingCurve", Msg: "Create v2: associated quote bonding curve address does not match derivation"},
	6066: {Code: 6066, Name: "QuoteMintWhitelistFull", Msg: "Quote mint whitelist is full"},
	6067: {Code: 6067, Name: "QuoteMintAlreadyWhitelisted", Msg: "Quote mint is already whitelisted"},
	6068: {Code: 6068, Name: "QuoteMintNotWhitelisted", Msg: "Quote mint is not in the whitelist"},
	6069: {Code: 6069, Name: "QuoteMintNotEligibleForWhitelist", Msg: "Quote mint cannot be added or removed via whitelist (default or native SOL mint)"},
	6070: {Code: 6070, Name: "UnableToDistributeCreatorFeesToUninitializedAccount", Msg: "Unable to distribute creator fees to uninitialized account"},
	6071: {Code: 6071, Name: "MayhemModeQuoteMintNotAllowed", Msg: "Mayhem mode quote mint not allowed"},
}

func ErrorFromCode(code uint32) (ProgramError, bool) {
	err, ok := Errors[code]
	return err, ok
}
