// Code generated by internal/gen; DO NOT EDIT.
// Generated at 2025-12-07T17:54:48Z

package pump

import (
	"bytes"
	"fmt"

	bin "github.com/gagliardetto/binary"
	"github.com/gagliardetto/solana-go"
)

var AdminSetCreatorDiscriminator = []byte{69, 25, 171, 142, 57, 239, 13, 4}

type AdminSetCreatorArgs struct {
	Creator solana.PublicKey `bin:"creator"`
}

type AdminSetCreatorAccounts struct {
	AdminSetCreatorAuthority solana.PublicKey
	Global                   solana.PublicKey
	Mint                     solana.PublicKey
	BondingCurve             solana.PublicKey
	EventAuthority           solana.PublicKey
	Program                  solana.PublicKey
}

func (a AdminSetCreatorAccounts) ToAccountMetas() []*solana.AccountMeta {
	metas := make([]*solana.AccountMeta, 0, 6)
	metas = append(metas, solana.NewAccountMeta(a.AdminSetCreatorAuthority, false, true))
	metas = append(metas, solana.NewAccountMeta(a.Global, false, false))
	metas = append(metas, solana.NewAccountMeta(a.Mint, false, false))
	metas = append(metas, solana.NewAccountMeta(a.BondingCurve, true, false))
	metas = append(metas, solana.NewAccountMeta(a.EventAuthority, false, false))
	metas = append(metas, solana.NewAccountMeta(a.Program, false, false))
	return metas
}

func BuildAdminSetCreator(accounts AdminSetCreatorAccounts, args AdminSetCreatorArgs) (solana.Instruction, error) {
	buf := bytes.NewBuffer(make([]byte, 0, 128))
	buf.Write(AdminSetCreatorDiscriminator)
	if err := bin.NewBorshEncoder(buf).Encode(args); err != nil {
		return nil, fmt.Errorf("encode args: %w", err)
	}
	data := buf.Bytes()
	return solana.NewInstruction(ProgramKey, accounts.ToAccountMetas(), data), nil
}

func DeriveAdminSetCreatorGlobalPDA(accounts AdminSetCreatorAccounts, args AdminSetCreatorArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 1)
	seeds = append(seeds, []byte{103, 108, 111, 98, 97, 108})
	return solana.FindProgramAddress(seeds, ProgramKey)
}

func DeriveAdminSetCreatorBondingCurvePDA(accounts AdminSetCreatorAccounts, args AdminSetCreatorArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 2)
	seeds = append(seeds, []byte{98, 111, 110, 100, 105, 110, 103, 45, 99, 117, 114, 118, 101})
	seeds = append(seeds, accounts.Mint[:])
	return solana.FindProgramAddress(seeds, ProgramKey)
}

func DeriveAdminSetCreatorEventAuthorityPDA(accounts AdminSetCreatorAccounts, args AdminSetCreatorArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 1)
	seeds = append(seeds, []byte{95, 95, 101, 118, 101, 110, 116, 95, 97, 117, 116, 104, 111, 114, 105, 116, 121})
	return solana.FindProgramAddress(seeds, ProgramKey)
}

var AdminSetIdlAuthorityDiscriminator = []byte{8, 217, 96, 231, 144, 104, 192, 5}

type AdminSetIdlAuthorityArgs struct {
	IdlAuthority solana.PublicKey `bin:"idl_authority"`
}

type AdminSetIdlAuthorityAccounts struct {
	Authority      solana.PublicKey
	Global         solana.PublicKey
	IdlAccount     solana.PublicKey
	SystemProgram  solana.PublicKey
	ProgramSigner  solana.PublicKey
	EventAuthority solana.PublicKey
	Program        solana.PublicKey
}

func (a AdminSetIdlAuthorityAccounts) ToAccountMetas() []*solana.AccountMeta {
	metas := make([]*solana.AccountMeta, 0, 7)
	metas = append(metas, solana.NewAccountMeta(a.Authority, false, true))
	metas = append(metas, solana.NewAccountMeta(a.Global, false, false))
	metas = append(metas, solana.NewAccountMeta(a.IdlAccount, true, false))
	var defaultAdminSetIdlAuthoritySystemProgram = func() solana.PublicKey {
		return solana.MustPublicKeyFromBase58("11111111111111111111111111111111")
	}

	metas = append(metas, solana.NewAccountMeta(defaultAdminSetIdlAuthoritySystemProgram(), false, false))
	metas = append(metas, solana.NewAccountMeta(a.ProgramSigner, false, false))
	metas = append(metas, solana.NewAccountMeta(a.EventAuthority, false, false))
	metas = append(metas, solana.NewAccountMeta(a.Program, false, false))
	return metas
}

func BuildAdminSetIdlAuthority(accounts AdminSetIdlAuthorityAccounts, args AdminSetIdlAuthorityArgs) (solana.Instruction, error) {
	buf := bytes.NewBuffer(make([]byte, 0, 128))
	buf.Write(AdminSetIdlAuthorityDiscriminator)
	if err := bin.NewBorshEncoder(buf).Encode(args); err != nil {
		return nil, fmt.Errorf("encode args: %w", err)
	}
	data := buf.Bytes()
	return solana.NewInstruction(ProgramKey, accounts.ToAccountMetas(), data), nil
}

func DeriveAdminSetIdlAuthorityGlobalPDA(accounts AdminSetIdlAuthorityAccounts, args AdminSetIdlAuthorityArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 1)
	seeds = append(seeds, []byte{103, 108, 111, 98, 97, 108})
	return solana.FindProgramAddress(seeds, ProgramKey)
}

func DeriveAdminSetIdlAuthorityEventAuthorityPDA(accounts AdminSetIdlAuthorityAccounts, args AdminSetIdlAuthorityArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 1)
	seeds = append(seeds, []byte{95, 95, 101, 118, 101, 110, 116, 95, 97, 117, 116, 104, 111, 114, 105, 116, 121})
	return solana.FindProgramAddress(seeds, ProgramKey)
}

var AdminUpdateTokenIncentivesDiscriminator = []byte{209, 11, 115, 87, 213, 23, 124, 204}

type AdminUpdateTokenIncentivesArgs struct {
	StartTime             int64  `bin:"start_time"`
	EndTime               int64  `bin:"end_time"`
	SecondsInADay         int64  `bin:"seconds_in_a_day"`
	DayNumber             uint64 `bin:"day_number"`
	PumpTokenSupplyPerDay uint64 `bin:"pump_token_supply_per_day"`
}

type AdminUpdateTokenIncentivesAccounts struct {
	Authority                   solana.PublicKey
	Global                      solana.PublicKey
	GlobalVolumeAccumulator     solana.PublicKey
	Mint                        solana.PublicKey
	GlobalIncentiveTokenAccount solana.PublicKey
	AssociatedTokenProgram      solana.PublicKey
	SystemProgram               solana.PublicKey
	TokenProgram                solana.PublicKey
	EventAuthority              solana.PublicKey
	Program                     solana.PublicKey
}

func (a AdminUpdateTokenIncentivesAccounts) ToAccountMetas() []*solana.AccountMeta {
	metas := make([]*solana.AccountMeta, 0, 10)
	metas = append(metas, solana.NewAccountMeta(a.Authority, true, true))
	metas = append(metas, solana.NewAccountMeta(a.Global, false, false))
	metas = append(metas, solana.NewAccountMeta(a.GlobalVolumeAccumulator, true, false))
	metas = append(metas, solana.NewAccountMeta(a.Mint, false, false))
	metas = append(metas, solana.NewAccountMeta(a.GlobalIncentiveTokenAccount, true, false))
	var defaultAdminUpdateTokenIncentivesAssociatedTokenProgram = func() solana.PublicKey {
		return solana.MustPublicKeyFromBase58("ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL")
	}

	metas = append(metas, solana.NewAccountMeta(defaultAdminUpdateTokenIncentivesAssociatedTokenProgram(), false, false))
	var defaultAdminUpdateTokenIncentivesSystemProgram = func() solana.PublicKey {
		return solana.MustPublicKeyFromBase58("11111111111111111111111111111111")
	}

	metas = append(metas, solana.NewAccountMeta(defaultAdminUpdateTokenIncentivesSystemProgram(), false, false))
	metas = append(metas, solana.NewAccountMeta(a.TokenProgram, false, false))
	metas = append(metas, solana.NewAccountMeta(a.EventAuthority, false, false))
	metas = append(metas, solana.NewAccountMeta(a.Program, false, false))
	return metas
}

func BuildAdminUpdateTokenIncentives(accounts AdminUpdateTokenIncentivesAccounts, args AdminUpdateTokenIncentivesArgs) (solana.Instruction, error) {
	buf := bytes.NewBuffer(make([]byte, 0, 128))
	buf.Write(AdminUpdateTokenIncentivesDiscriminator)
	if err := bin.NewBorshEncoder(buf).Encode(args); err != nil {
		return nil, fmt.Errorf("encode args: %w", err)
	}
	data := buf.Bytes()
	return solana.NewInstruction(ProgramKey, accounts.ToAccountMetas(), data), nil
}

func DeriveAdminUpdateTokenIncentivesGlobalPDA(accounts AdminUpdateTokenIncentivesAccounts, args AdminUpdateTokenIncentivesArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 1)
	seeds = append(seeds, []byte{103, 108, 111, 98, 97, 108})
	return solana.FindProgramAddress(seeds, ProgramKey)
}

func DeriveAdminUpdateTokenIncentivesGlobalVolumeAccumulatorPDA(accounts AdminUpdateTokenIncentivesAccounts, args AdminUpdateTokenIncentivesArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 1)
	seeds = append(seeds, []byte{103, 108, 111, 98, 97, 108, 95, 118, 111, 108, 117, 109, 101, 95, 97, 99, 99, 117, 109, 117, 108, 97, 116, 111, 114})
	return solana.FindProgramAddress(seeds, ProgramKey)
}

func DeriveAdminUpdateTokenIncentivesGlobalIncentiveTokenAccountPDA(accounts AdminUpdateTokenIncentivesAccounts, args AdminUpdateTokenIncentivesArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 3)
	seeds = append(seeds, accounts.GlobalVolumeAccumulator[:])
	seeds = append(seeds, accounts.TokenProgram[:])
	seeds = append(seeds, accounts.Mint[:])
	return solana.FindProgramAddress(seeds, solana.PublicKeyFromBytes([]byte{140, 151, 37, 143, 78, 36, 137, 241, 187, 61, 16, 41, 20, 142, 13, 131, 11, 90, 19, 153, 218, 255, 16, 132, 4, 142, 123, 216, 219, 233, 248, 89}))
}

func DeriveAdminUpdateTokenIncentivesEventAuthorityPDA(accounts AdminUpdateTokenIncentivesAccounts, args AdminUpdateTokenIncentivesArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 1)
	seeds = append(seeds, []byte{95, 95, 101, 118, 101, 110, 116, 95, 97, 117, 116, 104, 111, 114, 105, 116, 121})
	return solana.FindProgramAddress(seeds, ProgramKey)
}

var BuyDiscriminator = []byte{102, 6, 61, 18, 1, 218, 235, 234}

type BuyArgs struct {
	Amount      uint64     `bin:"amount"`
	MaxSolCost  uint64     `bin:"max_sol_cost"`
	TrackVolume OptionBool `bin:"track_volume"`
}

type BuyAccounts struct {
	Global                  solana.PublicKey
	FeeRecipient            solana.PublicKey
	Mint                    solana.PublicKey
	BondingCurve            solana.PublicKey
	AssociatedBondingCurve  solana.PublicKey
	AssociatedUser          solana.PublicKey
	User                    solana.PublicKey
	SystemProgram           solana.PublicKey
	TokenProgram            solana.PublicKey
	CreatorVault            solana.PublicKey
	EventAuthority          solana.PublicKey
	Program                 solana.PublicKey
	GlobalVolumeAccumulator solana.PublicKey
	UserVolumeAccumulator   solana.PublicKey
	FeeConfig               solana.PublicKey
	FeeProgram              solana.PublicKey
}

func (a BuyAccounts) ToAccountMetas() []*solana.AccountMeta {
	metas := make([]*solana.AccountMeta, 0, 16)
	metas = append(metas, solana.NewAccountMeta(a.Global, false, false))
	metas = append(metas, solana.NewAccountMeta(a.FeeRecipient, true, false))
	metas = append(metas, solana.NewAccountMeta(a.Mint, false, false))
	metas = append(metas, solana.NewAccountMeta(a.BondingCurve, true, false))
	metas = append(metas, solana.NewAccountMeta(a.AssociatedBondingCurve, true, false))
	metas = append(metas, solana.NewAccountMeta(a.AssociatedUser, true, false))
	metas = append(metas, solana.NewAccountMeta(a.User, true, true))
	var defaultBuySystemProgram = func() solana.PublicKey {
		return solana.MustPublicKeyFromBase58("11111111111111111111111111111111")
	}

	metas = append(metas, solana.NewAccountMeta(defaultBuySystemProgram(), false, false))
	metas = append(metas, solana.NewAccountMeta(a.TokenProgram, false, false))
	metas = append(metas, solana.NewAccountMeta(a.CreatorVault, true, false))
	metas = append(metas, solana.NewAccountMeta(a.EventAuthority, false, false))
	var defaultBuyProgram = func() solana.PublicKey {
		return solana.MustPublicKeyFromBase58("6EF8rrecthR5Dkzon8Nwu78hRvfCKubJ14M5uBEwF6P")
	}

	metas = append(metas, solana.NewAccountMeta(defaultBuyProgram(), false, false))
	metas = append(metas, solana.NewAccountMeta(a.GlobalVolumeAccumulator, false, false))
	metas = append(metas, solana.NewAccountMeta(a.UserVolumeAccumulator, true, false))
	metas = append(metas, solana.NewAccountMeta(a.FeeConfig, false, false))
	var defaultBuyFeeProgram = func() solana.PublicKey {
		return solana.MustPublicKeyFromBase58("pfeeUxB6jkeY1Hxd7CsFCAjcbHA9rWtchMGdZ6VojVZ")
	}

	metas = append(metas, solana.NewAccountMeta(defaultBuyFeeProgram(), false, false))
	return metas
}

func BuildBuy(accounts BuyAccounts, args BuyArgs) (solana.Instruction, error) {
	buf := bytes.NewBuffer(make([]byte, 0, 128))
	buf.Write(BuyDiscriminator)
	if err := bin.NewBorshEncoder(buf).Encode(args); err != nil {
		return nil, fmt.Errorf("encode args: %w", err)
	}
	data := buf.Bytes()
	return solana.NewInstruction(ProgramKey, accounts.ToAccountMetas(), data), nil
}

func DeriveBuyGlobalPDA(accounts BuyAccounts, args BuyArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 1)
	seeds = append(seeds, []byte{103, 108, 111, 98, 97, 108})
	return solana.FindProgramAddress(seeds, ProgramKey)
}

func DeriveBuyBondingCurvePDA(accounts BuyAccounts, args BuyArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 2)
	seeds = append(seeds, []byte{98, 111, 110, 100, 105, 110, 103, 45, 99, 117, 114, 118, 101})
	seeds = append(seeds, accounts.Mint[:])
	return solana.FindProgramAddress(seeds, ProgramKey)
}

func DeriveBuyAssociatedBondingCurvePDA(accounts BuyAccounts, args BuyArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 3)
	seeds = append(seeds, accounts.BondingCurve[:])
	seeds = append(seeds, accounts.TokenProgram[:])
	seeds = append(seeds, accounts.Mint[:])
	return solana.FindProgramAddress(seeds, solana.PublicKeyFromBytes([]byte{140, 151, 37, 143, 78, 36, 137, 241, 187, 61, 16, 41, 20, 142, 13, 131, 11, 90, 19, 153, 218, 255, 16, 132, 4, 142, 123, 216, 219, 233, 248, 89}))
}

func DeriveBuyCreatorVaultPDA(accounts BuyAccounts, args BuyArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 2)
	seeds = append(seeds, []byte{99, 114, 101, 97, 116, 111, 114, 45, 118, 97, 117, 108, 116})
	seeds = append(seeds, accounts.BondingCurve[:])
	return solana.FindProgramAddress(seeds, ProgramKey)
}

func DeriveBuyEventAuthorityPDA(accounts BuyAccounts, args BuyArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 1)
	seeds = append(seeds, []byte{95, 95, 101, 118, 101, 110, 116, 95, 97, 117, 116, 104, 111, 114, 105, 116, 121})
	return solana.FindProgramAddress(seeds, ProgramKey)
}

func DeriveBuyGlobalVolumeAccumulatorPDA(accounts BuyAccounts, args BuyArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 1)
	seeds = append(seeds, []byte{103, 108, 111, 98, 97, 108, 95, 118, 111, 108, 117, 109, 101, 95, 97, 99, 99, 117, 109, 117, 108, 97, 116, 111, 114})
	return solana.FindProgramAddress(seeds, ProgramKey)
}

func DeriveBuyUserVolumeAccumulatorPDA(accounts BuyAccounts, args BuyArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 2)
	seeds = append(seeds, []byte{117, 115, 101, 114, 95, 118, 111, 108, 117, 109, 101, 95, 97, 99, 99, 117, 109, 117, 108, 97, 116, 111, 114})
	seeds = append(seeds, accounts.User[:])
	return solana.FindProgramAddress(seeds, ProgramKey)
}

func DeriveBuyFeeConfigPDA(accounts BuyAccounts, args BuyArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 2)
	seeds = append(seeds, []byte{102, 101, 101, 95, 99, 111, 110, 102, 105, 103})
	seeds = append(seeds, []byte{1, 86, 224, 246, 147, 102, 90, 207, 68, 219, 21, 104, 191, 23, 91, 170, 81, 137, 203, 151, 245, 210, 255, 59, 101, 93, 43, 182, 253, 109, 24, 176})
	return solana.FindProgramAddress(seeds, accounts.FeeProgram)
}

var BuyExactSolInDiscriminator = []byte{56, 252, 116, 8, 158, 223, 205, 95}

type BuyExactSolInArgs struct {
	SpendableSolIn uint64     `bin:"spendable_sol_in"`
	MinTokensOut   uint64     `bin:"min_tokens_out"`
	TrackVolume    OptionBool `bin:"track_volume"`
}

type BuyExactSolInAccounts struct {
	Global                  solana.PublicKey
	FeeRecipient            solana.PublicKey
	Mint                    solana.PublicKey
	BondingCurve            solana.PublicKey
	AssociatedBondingCurve  solana.PublicKey
	AssociatedUser          solana.PublicKey
	User                    solana.PublicKey
	SystemProgram           solana.PublicKey
	TokenProgram            solana.PublicKey
	CreatorVault            solana.PublicKey
	EventAuthority          solana.PublicKey
	Program                 solana.PublicKey
	GlobalVolumeAccumulator solana.PublicKey
	UserVolumeAccumulator   solana.PublicKey
	FeeConfig               solana.PublicKey
	FeeProgram              solana.PublicKey
}

func (a BuyExactSolInAccounts) ToAccountMetas() []*solana.AccountMeta {
	metas := make([]*solana.AccountMeta, 0, 16)
	metas = append(metas, solana.NewAccountMeta(a.Global, false, false))
	metas = append(metas, solana.NewAccountMeta(a.FeeRecipient, true, false))
	metas = append(metas, solana.NewAccountMeta(a.Mint, false, false))
	metas = append(metas, solana.NewAccountMeta(a.BondingCurve, true, false))
	metas = append(metas, solana.NewAccountMeta(a.AssociatedBondingCurve, true, false))
	metas = append(metas, solana.NewAccountMeta(a.AssociatedUser, true, false))
	metas = append(metas, solana.NewAccountMeta(a.User, true, true))
	var defaultBuyExactSolInSystemProgram = func() solana.PublicKey {
		return solana.MustPublicKeyFromBase58("11111111111111111111111111111111")
	}

	metas = append(metas, solana.NewAccountMeta(defaultBuyExactSolInSystemProgram(), false, false))
	metas = append(metas, solana.NewAccountMeta(a.TokenProgram, false, false))
	metas = append(metas, solana.NewAccountMeta(a.CreatorVault, true, false))
	metas = append(metas, solana.NewAccountMeta(a.EventAuthority, false, false))
	var defaultBuyExactSolInProgram = func() solana.PublicKey {
		return solana.MustPublicKeyFromBase58("6EF8rrecthR5Dkzon8Nwu78hRvfCKubJ14M5uBEwF6P")
	}

	metas = append(metas, solana.NewAccountMeta(defaultBuyExactSolInProgram(), false, false))
	metas = append(metas, solana.NewAccountMeta(a.GlobalVolumeAccumulator, false, false))
	metas = append(metas, solana.NewAccountMeta(a.UserVolumeAccumulator, true, false))
	metas = append(metas, solana.NewAccountMeta(a.FeeConfig, false, false))
	var defaultBuyExactSolInFeeProgram = func() solana.PublicKey {
		return solana.MustPublicKeyFromBase58("pfeeUxB6jkeY1Hxd7CsFCAjcbHA9rWtchMGdZ6VojVZ")
	}

	metas = append(metas, solana.NewAccountMeta(defaultBuyExactSolInFeeProgram(), false, false))
	return metas
}

func BuildBuyExactSolIn(accounts BuyExactSolInAccounts, args BuyExactSolInArgs) (solana.Instruction, error) {
	buf := bytes.NewBuffer(make([]byte, 0, 128))
	buf.Write(BuyExactSolInDiscriminator)
	if err := bin.NewBorshEncoder(buf).Encode(args); err != nil {
		return nil, fmt.Errorf("encode args: %w", err)
	}
	data := buf.Bytes()
	return solana.NewInstruction(ProgramKey, accounts.ToAccountMetas(), data), nil
}

func DeriveBuyExactSolInGlobalPDA(accounts BuyExactSolInAccounts, args BuyExactSolInArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 1)
	seeds = append(seeds, []byte{103, 108, 111, 98, 97, 108})
	return solana.FindProgramAddress(seeds, ProgramKey)
}

func DeriveBuyExactSolInBondingCurvePDA(accounts BuyExactSolInAccounts, args BuyExactSolInArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 2)
	seeds = append(seeds, []byte{98, 111, 110, 100, 105, 110, 103, 45, 99, 117, 114, 118, 101})
	seeds = append(seeds, accounts.Mint[:])
	return solana.FindProgramAddress(seeds, ProgramKey)
}

func DeriveBuyExactSolInAssociatedBondingCurvePDA(accounts BuyExactSolInAccounts, args BuyExactSolInArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 3)
	seeds = append(seeds, accounts.BondingCurve[:])
	seeds = append(seeds, accounts.TokenProgram[:])
	seeds = append(seeds, accounts.Mint[:])
	return solana.FindProgramAddress(seeds, solana.PublicKeyFromBytes([]byte{140, 151, 37, 143, 78, 36, 137, 241, 187, 61, 16, 41, 20, 142, 13, 131, 11, 90, 19, 153, 218, 255, 16, 132, 4, 142, 123, 216, 219, 233, 248, 89}))
}

func DeriveBuyExactSolInCreatorVaultPDA(accounts BuyExactSolInAccounts, args BuyExactSolInArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 2)
	seeds = append(seeds, []byte{99, 114, 101, 97, 116, 111, 114, 45, 118, 97, 117, 108, 116})
	seeds = append(seeds, accounts.BondingCurve[:])
	return solana.FindProgramAddress(seeds, ProgramKey)
}

func DeriveBuyExactSolInEventAuthorityPDA(accounts BuyExactSolInAccounts, args BuyExactSolInArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 1)
	seeds = append(seeds, []byte{95, 95, 101, 118, 101, 110, 116, 95, 97, 117, 116, 104, 111, 114, 105, 116, 121})
	return solana.FindProgramAddress(seeds, ProgramKey)
}

func DeriveBuyExactSolInGlobalVolumeAccumulatorPDA(accounts BuyExactSolInAccounts, args BuyExactSolInArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 1)
	seeds = append(seeds, []byte{103, 108, 111, 98, 97, 108, 95, 118, 111, 108, 117, 109, 101, 95, 97, 99, 99, 117, 109, 117, 108, 97, 116, 111, 114})
	return solana.FindProgramAddress(seeds, ProgramKey)
}

func DeriveBuyExactSolInUserVolumeAccumulatorPDA(accounts BuyExactSolInAccounts, args BuyExactSolInArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 2)
	seeds = append(seeds, []byte{117, 115, 101, 114, 95, 118, 111, 108, 117, 109, 101, 95, 97, 99, 99, 117, 109, 117, 108, 97, 116, 111, 114})
	seeds = append(seeds, accounts.User[:])
	return solana.FindProgramAddress(seeds, ProgramKey)
}

func DeriveBuyExactSolInFeeConfigPDA(accounts BuyExactSolInAccounts, args BuyExactSolInArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 2)
	seeds = append(seeds, []byte{102, 101, 101, 95, 99, 111, 110, 102, 105, 103})
	seeds = append(seeds, []byte{1, 86, 224, 246, 147, 102, 90, 207, 68, 219, 21, 104, 191, 23, 91, 170, 81, 137, 203, 151, 245, 210, 255, 59, 101, 93, 43, 182, 253, 109, 24, 176})
	return solana.FindProgramAddress(seeds, accounts.FeeProgram)
}

var ClaimTokenIncentivesDiscriminator = []byte{16, 4, 71, 28, 204, 1, 40, 27}

type ClaimTokenIncentivesArgs struct{}

type ClaimTokenIncentivesAccounts struct {
	User                        solana.PublicKey
	UserAta                     solana.PublicKey
	GlobalVolumeAccumulator     solana.PublicKey
	GlobalIncentiveTokenAccount solana.PublicKey
	UserVolumeAccumulator       solana.PublicKey
	Mint                        solana.PublicKey
	TokenProgram                solana.PublicKey
	SystemProgram               solana.PublicKey
	AssociatedTokenProgram      solana.PublicKey
	EventAuthority              solana.PublicKey
	Program                     solana.PublicKey
	Payer                       solana.PublicKey
}

func (a ClaimTokenIncentivesAccounts) ToAccountMetas() []*solana.AccountMeta {
	metas := make([]*solana.AccountMeta, 0, 12)
	metas = append(metas, solana.NewAccountMeta(a.User, false, false))
	metas = append(metas, solana.NewAccountMeta(a.UserAta, true, false))
	metas = append(metas, solana.NewAccountMeta(a.GlobalVolumeAccumulator, false, false))
	metas = append(metas, solana.NewAccountMeta(a.GlobalIncentiveTokenAccount, true, false))
	metas = append(metas, solana.NewAccountMeta(a.UserVolumeAccumulator, true, false))
	metas = append(metas, solana.NewAccountMeta(a.Mint, false, false))
	metas = append(metas, solana.NewAccountMeta(a.TokenProgram, false, false))
	var defaultClaimTokenIncentivesSystemProgram = func() solana.PublicKey {
		return solana.MustPublicKeyFromBase58("11111111111111111111111111111111")
	}

	metas = append(metas, solana.NewAccountMeta(defaultClaimTokenIncentivesSystemProgram(), false, false))
	var defaultClaimTokenIncentivesAssociatedTokenProgram = func() solana.PublicKey {
		return solana.MustPublicKeyFromBase58("ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL")
	}

	metas = append(metas, solana.NewAccountMeta(defaultClaimTokenIncentivesAssociatedTokenProgram(), false, false))
	metas = append(metas, solana.NewAccountMeta(a.EventAuthority, false, false))
	var defaultClaimTokenIncentivesProgram = func() solana.PublicKey {
		return solana.MustPublicKeyFromBase58("6EF8rrecthR5Dkzon8Nwu78hRvfCKubJ14M5uBEwF6P")
	}

	metas = append(metas, solana.NewAccountMeta(defaultClaimTokenIncentivesProgram(), false, false))
	metas = append(metas, solana.NewAccountMeta(a.Payer, true, true))
	return metas
}

func BuildClaimTokenIncentives(accounts ClaimTokenIncentivesAccounts, args ClaimTokenIncentivesArgs) (solana.Instruction, error) {
	buf := bytes.NewBuffer(make([]byte, 0, 128))
	buf.Write(ClaimTokenIncentivesDiscriminator)
	data := buf.Bytes()
	return solana.NewInstruction(ProgramKey, accounts.ToAccountMetas(), data), nil
}

func DeriveClaimTokenIncentivesUserAtaPDA(accounts ClaimTokenIncentivesAccounts, args ClaimTokenIncentivesArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 3)
	seeds = append(seeds, accounts.User[:])
	seeds = append(seeds, accounts.TokenProgram[:])
	seeds = append(seeds, accounts.Mint[:])
	return solana.FindProgramAddress(seeds, solana.PublicKeyFromBytes([]byte{140, 151, 37, 143, 78, 36, 137, 241, 187, 61, 16, 41, 20, 142, 13, 131, 11, 90, 19, 153, 218, 255, 16, 132, 4, 142, 123, 216, 219, 233, 248, 89}))
}

func DeriveClaimTokenIncentivesGlobalVolumeAccumulatorPDA(accounts ClaimTokenIncentivesAccounts, args ClaimTokenIncentivesArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 1)
	seeds = append(seeds, []byte{103, 108, 111, 98, 97, 108, 95, 118, 111, 108, 117, 109, 101, 95, 97, 99, 99, 117, 109, 117, 108, 97, 116, 111, 114})
	return solana.FindProgramAddress(seeds, ProgramKey)
}

func DeriveClaimTokenIncentivesGlobalIncentiveTokenAccountPDA(accounts ClaimTokenIncentivesAccounts, args ClaimTokenIncentivesArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 3)
	seeds = append(seeds, accounts.GlobalVolumeAccumulator[:])
	seeds = append(seeds, accounts.TokenProgram[:])
	seeds = append(seeds, accounts.Mint[:])
	return solana.FindProgramAddress(seeds, solana.PublicKeyFromBytes([]byte{140, 151, 37, 143, 78, 36, 137, 241, 187, 61, 16, 41, 20, 142, 13, 131, 11, 90, 19, 153, 218, 255, 16, 132, 4, 142, 123, 216, 219, 233, 248, 89}))
}

func DeriveClaimTokenIncentivesUserVolumeAccumulatorPDA(accounts ClaimTokenIncentivesAccounts, args ClaimTokenIncentivesArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 2)
	seeds = append(seeds, []byte{117, 115, 101, 114, 95, 118, 111, 108, 117, 109, 101, 95, 97, 99, 99, 117, 109, 117, 108, 97, 116, 111, 114})
	seeds = append(seeds, accounts.User[:])
	return solana.FindProgramAddress(seeds, ProgramKey)
}

func DeriveClaimTokenIncentivesEventAuthorityPDA(accounts ClaimTokenIncentivesAccounts, args ClaimTokenIncentivesArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 1)
	seeds = append(seeds, []byte{95, 95, 101, 118, 101, 110, 116, 95, 97, 117, 116, 104, 111, 114, 105, 116, 121})
	return solana.FindProgramAddress(seeds, ProgramKey)
}

var CloseUserVolumeAccumulatorDiscriminator = []byte{249, 69, 164, 218, 150, 103, 84, 138}

type CloseUserVolumeAccumulatorArgs struct{}

type CloseUserVolumeAccumulatorAccounts struct {
	User                  solana.PublicKey
	UserVolumeAccumulator solana.PublicKey
	EventAuthority        solana.PublicKey
	Program               solana.PublicKey
}

func (a CloseUserVolumeAccumulatorAccounts) ToAccountMetas() []*solana.AccountMeta {
	metas := make([]*solana.AccountMeta, 0, 4)
	metas = append(metas, solana.NewAccountMeta(a.User, true, true))
	metas = append(metas, solana.NewAccountMeta(a.UserVolumeAccumulator, true, false))
	metas = append(metas, solana.NewAccountMeta(a.EventAuthority, false, false))
	metas = append(metas, solana.NewAccountMeta(a.Program, false, false))
	return metas
}

func BuildCloseUserVolumeAccumulator(accounts CloseUserVolumeAccumulatorAccounts, args CloseUserVolumeAccumulatorArgs) (solana.Instruction, error) {
	buf := bytes.NewBuffer(make([]byte, 0, 128))
	buf.Write(CloseUserVolumeAccumulatorDiscriminator)
	data := buf.Bytes()
	return solana.NewInstruction(ProgramKey, accounts.ToAccountMetas(), data), nil
}

func DeriveCloseUserVolumeAccumulatorUserVolumeAccumulatorPDA(accounts CloseUserVolumeAccumulatorAccounts, args CloseUserVolumeAccumulatorArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 2)
	seeds = append(seeds, []byte{117, 115, 101, 114, 95, 118, 111, 108, 117, 109, 101, 95, 97, 99, 99, 117, 109, 117, 108, 97, 116, 111, 114})
	seeds = append(seeds, accounts.User[:])
	return solana.FindProgramAddress(seeds, ProgramKey)
}

func DeriveCloseUserVolumeAccumulatorEventAuthorityPDA(accounts CloseUserVolumeAccumulatorAccounts, args CloseUserVolumeAccumulatorArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 1)
	seeds = append(seeds, []byte{95, 95, 101, 118, 101, 110, 116, 95, 97, 117, 116, 104, 111, 114, 105, 116, 121})
	return solana.FindProgramAddress(seeds, ProgramKey)
}

var CollectCreatorFeeDiscriminator = []byte{20, 22, 86, 123, 198, 28, 219, 132}

type CollectCreatorFeeArgs struct{}

type CollectCreatorFeeAccounts struct {
	Creator        solana.PublicKey
	CreatorVault   solana.PublicKey
	SystemProgram  solana.PublicKey
	EventAuthority solana.PublicKey
	Program        solana.PublicKey
}

func (a CollectCreatorFeeAccounts) ToAccountMetas() []*solana.AccountMeta {
	metas := make([]*solana.AccountMeta, 0, 5)
	metas = append(metas, solana.NewAccountMeta(a.Creator, true, false))
	metas = append(metas, solana.NewAccountMeta(a.CreatorVault, true, false))
	var defaultCollectCreatorFeeSystemProgram = func() solana.PublicKey {
		return solana.MustPublicKeyFromBase58("11111111111111111111111111111111")
	}

	metas = append(metas, solana.NewAccountMeta(defaultCollectCreatorFeeSystemProgram(), false, false))
	metas = append(metas, solana.NewAccountMeta(a.EventAuthority, false, false))
	metas = append(metas, solana.NewAccountMeta(a.Program, false, false))
	return metas
}

func BuildCollectCreatorFee(accounts CollectCreatorFeeAccounts, args CollectCreatorFeeArgs) (solana.Instruction, error) {
	buf := bytes.NewBuffer(make([]byte, 0, 128))
	buf.Write(CollectCreatorFeeDiscriminator)
	data := buf.Bytes()
	return solana.NewInstruction(ProgramKey, accounts.ToAccountMetas(), data), nil
}

func DeriveCollectCreatorFeeCreatorVaultPDA(accounts CollectCreatorFeeAccounts, args CollectCreatorFeeArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 2)
	seeds = append(seeds, []byte{99, 114, 101, 97, 116, 111, 114, 45, 118, 97, 117, 108, 116})
	seeds = append(seeds, accounts.Creator[:])
	return solana.FindProgramAddress(seeds, ProgramKey)
}

func DeriveCollectCreatorFeeEventAuthorityPDA(accounts CollectCreatorFeeAccounts, args CollectCreatorFeeArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 1)
	seeds = append(seeds, []byte{95, 95, 101, 118, 101, 110, 116, 95, 97, 117, 116, 104, 111, 114, 105, 116, 121})
	return solana.FindProgramAddress(seeds, ProgramKey)
}

var CreateDiscriminator = []byte{24, 30, 200, 40, 5, 28, 7, 119}

type CreateArgs struct {
	Name    string           `bin:"name"`
	Symbol  string           `bin:"symbol"`
	Uri     string           `bin:"uri"`
	Creator solana.PublicKey `bin:"creator"`
}

type CreateAccounts struct {
	Mint                   solana.PublicKey
	MintAuthority          solana.PublicKey
	BondingCurve           solana.PublicKey
	AssociatedBondingCurve solana.PublicKey
	Global                 solana.PublicKey
	MplTokenMetadata       solana.PublicKey
	Metadata               solana.PublicKey
	User                   solana.PublicKey
	SystemProgram          solana.PublicKey
	TokenProgram           solana.PublicKey
	AssociatedTokenProgram solana.PublicKey
	Rent                   solana.PublicKey
	EventAuthority         solana.PublicKey
	Program                solana.PublicKey
}

func (a CreateAccounts) ToAccountMetas() []*solana.AccountMeta {
	metas := make([]*solana.AccountMeta, 0, 14)
	metas = append(metas, solana.NewAccountMeta(a.Mint, true, true))
	metas = append(metas, solana.NewAccountMeta(a.MintAuthority, false, false))
	metas = append(metas, solana.NewAccountMeta(a.BondingCurve, true, false))
	metas = append(metas, solana.NewAccountMeta(a.AssociatedBondingCurve, true, false))
	metas = append(metas, solana.NewAccountMeta(a.Global, false, false))
	var defaultCreateMplTokenMetadata = func() solana.PublicKey {
		return solana.MustPublicKeyFromBase58("metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s")
	}

	metas = append(metas, solana.NewAccountMeta(defaultCreateMplTokenMetadata(), false, false))
	metas = append(metas, solana.NewAccountMeta(a.Metadata, true, false))
	metas = append(metas, solana.NewAccountMeta(a.User, true, true))
	var defaultCreateSystemProgram = func() solana.PublicKey {
		return solana.MustPublicKeyFromBase58("11111111111111111111111111111111")
	}

	metas = append(metas, solana.NewAccountMeta(defaultCreateSystemProgram(), false, false))
	var defaultCreateTokenProgram = func() solana.PublicKey {
		return solana.MustPublicKeyFromBase58("TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA")
	}

	metas = append(metas, solana.NewAccountMeta(defaultCreateTokenProgram(), false, false))
	var defaultCreateAssociatedTokenProgram = func() solana.PublicKey {
		return solana.MustPublicKeyFromBase58("ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL")
	}

	metas = append(metas, solana.NewAccountMeta(defaultCreateAssociatedTokenProgram(), false, false))
	var defaultCreateRent = func() solana.PublicKey {
		return solana.MustPublicKeyFromBase58("SysvarRent111111111111111111111111111111111")
	}

	metas = append(metas, solana.NewAccountMeta(defaultCreateRent(), false, false))
	metas = append(metas, solana.NewAccountMeta(a.EventAuthority, false, false))
	metas = append(metas, solana.NewAccountMeta(a.Program, false, false))
	return metas
}

func BuildCreate(accounts CreateAccounts, args CreateArgs) (solana.Instruction, error) {
	buf := bytes.NewBuffer(make([]byte, 0, 128))
	buf.Write(CreateDiscriminator)
	if err := bin.NewBorshEncoder(buf).Encode(args); err != nil {
		return nil, fmt.Errorf("encode args: %w", err)
	}
	data := buf.Bytes()
	return solana.NewInstruction(ProgramKey, accounts.ToAccountMetas(), data), nil
}

func DeriveCreateMintAuthorityPDA(accounts CreateAccounts, args CreateArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 1)
	seeds = append(seeds, []byte{109, 105, 110, 116, 45, 97, 117, 116, 104, 111, 114, 105, 116, 121})
	return solana.FindProgramAddress(seeds, ProgramKey)
}

func DeriveCreateBondingCurvePDA(accounts CreateAccounts, args CreateArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 2)
	seeds = append(seeds, []byte{98, 111, 110, 100, 105, 110, 103, 45, 99, 117, 114, 118, 101})
	seeds = append(seeds, accounts.Mint[:])
	return solana.FindProgramAddress(seeds, ProgramKey)
}

func DeriveCreateAssociatedBondingCurvePDA(accounts CreateAccounts, args CreateArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 3)
	seeds = append(seeds, accounts.BondingCurve[:])
	seeds = append(seeds, []byte{6, 221, 246, 225, 215, 101, 161, 147, 217, 203, 225, 70, 206, 235, 121, 172, 28, 180, 133, 237, 95, 91, 55, 145, 58, 140, 245, 133, 126, 255, 0, 169})
	seeds = append(seeds, accounts.Mint[:])
	return solana.FindProgramAddress(seeds, solana.PublicKeyFromBytes([]byte{140, 151, 37, 143, 78, 36, 137, 241, 187, 61, 16, 41, 20, 142, 13, 131, 11, 90, 19, 153, 218, 255, 16, 132, 4, 142, 123, 216, 219, 233, 248, 89}))
}

func DeriveCreateGlobalPDA(accounts CreateAccounts, args CreateArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 1)
	seeds = append(seeds, []byte{103, 108, 111, 98, 97, 108})
	return solana.FindProgramAddress(seeds, ProgramKey)
}

func DeriveCreateMetadataPDA(accounts CreateAccounts, args CreateArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 3)
	seeds = append(seeds, []byte{109, 101, 116, 97, 100, 97, 116, 97})
	seeds = append(seeds, []byte{11, 112, 101, 177, 227, 209, 124, 69, 56, 157, 82, 127, 107, 4, 195, 205, 88, 184, 108, 115, 26, 160, 253, 181, 73, 182, 209, 188, 3, 248, 41, 70})
	seeds = append(seeds, accounts.Mint[:])
	return solana.FindProgramAddress(seeds, accounts.MplTokenMetadata)
}

func DeriveCreateEventAuthorityPDA(accounts CreateAccounts, args CreateArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 1)
	seeds = append(seeds, []byte{95, 95, 101, 118, 101, 110, 116, 95, 97, 117, 116, 104, 111, 114, 105, 116, 121})
	return solana.FindProgramAddress(seeds, ProgramKey)
}

var CreateV2Discriminator = []byte{214, 144, 76, 236, 95, 139, 49, 180}

type CreateV2Args struct {
	Name         string           `bin:"name"`
	Symbol       string           `bin:"symbol"`
	Uri          string           `bin:"uri"`
	Creator      solana.PublicKey `bin:"creator"`
	IsMayhemMode bool             `bin:"is_mayhem_mode"`
}

type CreateV2Accounts struct {
	Mint                   solana.PublicKey
	MintAuthority          solana.PublicKey
	BondingCurve           solana.PublicKey
	AssociatedBondingCurve solana.PublicKey
	Global                 solana.PublicKey
	User                   solana.PublicKey
	SystemProgram          solana.PublicKey
	TokenProgram           solana.PublicKey
	AssociatedTokenProgram solana.PublicKey
	MayhemProgramId        solana.PublicKey
	GlobalParams           solana.PublicKey
	SolVault               solana.PublicKey
	MayhemState            solana.PublicKey
	MayhemTokenVault       solana.PublicKey
	EventAuthority         solana.PublicKey
	Program                solana.PublicKey
}

func (a CreateV2Accounts) ToAccountMetas() []*solana.AccountMeta {
	metas := make([]*solana.AccountMeta, 0, 16)
	metas = append(metas, solana.NewAccountMeta(a.Mint, true, true))
	metas = append(metas, solana.NewAccountMeta(a.MintAuthority, false, false))
	metas = append(metas, solana.NewAccountMeta(a.BondingCurve, true, false))
	metas = append(metas, solana.NewAccountMeta(a.AssociatedBondingCurve, true, false))
	metas = append(metas, solana.NewAccountMeta(a.Global, false, false))
	metas = append(metas, solana.NewAccountMeta(a.User, true, true))
	var defaultCreateV2SystemProgram = func() solana.PublicKey {
		return solana.MustPublicKeyFromBase58("11111111111111111111111111111111")
	}

	metas = append(metas, solana.NewAccountMeta(defaultCreateV2SystemProgram(), false, false))
	var defaultCreateV2TokenProgram = func() solana.PublicKey {
		return solana.MustPublicKeyFromBase58("TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb")
	}

	metas = append(metas, solana.NewAccountMeta(defaultCreateV2TokenProgram(), false, false))
	var defaultCreateV2AssociatedTokenProgram = func() solana.PublicKey {
		return solana.MustPublicKeyFromBase58("ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL")
	}

	metas = append(metas, solana.NewAccountMeta(defaultCreateV2AssociatedTokenProgram(), false, false))
	var defaultCreateV2MayhemProgramId = func() solana.PublicKey {
		return solana.MustPublicKeyFromBase58("MAyhSmzXzV1pTf7LsNkrNwkWKTo4ougAJ1PPg47MD4e")
	}

	metas = append(metas, solana.NewAccountMeta(defaultCreateV2MayhemProgramId(), true, false))
	metas = append(metas, solana.NewAccountMeta(a.GlobalParams, false, false))
	metas = append(metas, solana.NewAccountMeta(a.SolVault, true, false))
	metas = append(metas, solana.NewAccountMeta(a.MayhemState, true, false))
	metas = append(metas, solana.NewAccountMeta(a.MayhemTokenVault, true, false))
	metas = append(metas, solana.NewAccountMeta(a.EventAuthority, false, false))
	metas = append(metas, solana.NewAccountMeta(a.Program, false, false))
	return metas
}

func BuildCreateV2(accounts CreateV2Accounts, args CreateV2Args) (solana.Instruction, error) {
	buf := bytes.NewBuffer(make([]byte, 0, 128))
	buf.Write(CreateV2Discriminator)
	if err := bin.NewBorshEncoder(buf).Encode(args); err != nil {
		return nil, fmt.Errorf("encode args: %w", err)
	}
	data := buf.Bytes()
	return solana.NewInstruction(ProgramKey, accounts.ToAccountMetas(), data), nil
}

func DeriveCreateV2MintAuthorityPDA(accounts CreateV2Accounts, args CreateV2Args) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 1)
	seeds = append(seeds, []byte{109, 105, 110, 116, 45, 97, 117, 116, 104, 111, 114, 105, 116, 121})
	return solana.FindProgramAddress(seeds, ProgramKey)
}

func DeriveCreateV2BondingCurvePDA(accounts CreateV2Accounts, args CreateV2Args) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 2)
	seeds = append(seeds, []byte{98, 111, 110, 100, 105, 110, 103, 45, 99, 117, 114, 118, 101})
	seeds = append(seeds, accounts.Mint[:])
	return solana.FindProgramAddress(seeds, ProgramKey)
}

func DeriveCreateV2AssociatedBondingCurvePDA(accounts CreateV2Accounts, args CreateV2Args) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 3)
	seeds = append(seeds, accounts.BondingCurve[:])
	seeds = append(seeds, accounts.TokenProgram[:])
	seeds = append(seeds, accounts.Mint[:])
	return solana.FindProgramAddress(seeds, solana.PublicKeyFromBytes([]byte{140, 151, 37, 143, 78, 36, 137, 241, 187, 61, 16, 41, 20, 142, 13, 131, 11, 90, 19, 153, 218, 255, 16, 132, 4, 142, 123, 216, 219, 233, 248, 89}))
}

func DeriveCreateV2GlobalPDA(accounts CreateV2Accounts, args CreateV2Args) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 1)
	seeds = append(seeds, []byte{103, 108, 111, 98, 97, 108})
	return solana.FindProgramAddress(seeds, ProgramKey)
}

func DeriveCreateV2GlobalParamsPDA(accounts CreateV2Accounts, args CreateV2Args) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 1)
	seeds = append(seeds, []byte{103, 108, 111, 98, 97, 108, 45, 112, 97, 114, 97, 109, 115})
	return solana.FindProgramAddress(seeds, solana.PublicKeyFromBytes([]byte{5, 42, 229, 215, 167, 218, 167, 36, 166, 234, 176, 167, 41, 84, 145, 133, 90, 212, 160, 103, 22, 96, 103, 76, 78, 3, 69, 89, 128, 61, 101, 163}))
}

func DeriveCreateV2SolVaultPDA(accounts CreateV2Accounts, args CreateV2Args) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 1)
	seeds = append(seeds, []byte{115, 111, 108, 45, 118, 97, 117, 108, 116})
	return solana.FindProgramAddress(seeds, solana.PublicKeyFromBytes([]byte{5, 42, 229, 215, 167, 218, 167, 36, 166, 234, 176, 167, 41, 84, 145, 133, 90, 212, 160, 103, 22, 96, 103, 76, 78, 3, 69, 89, 128, 61, 101, 163}))
}

func DeriveCreateV2MayhemStatePDA(accounts CreateV2Accounts, args CreateV2Args) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 2)
	seeds = append(seeds, []byte{109, 97, 121, 104, 101, 109, 45, 115, 116, 97, 116, 101})
	seeds = append(seeds, accounts.Mint[:])
	return solana.FindProgramAddress(seeds, solana.PublicKeyFromBytes([]byte{5, 42, 229, 215, 167, 218, 167, 36, 166, 234, 176, 167, 41, 84, 145, 133, 90, 212, 160, 103, 22, 96, 103, 76, 78, 3, 69, 89, 128, 61, 101, 163}))
}

func DeriveCreateV2MayhemTokenVaultPDA(accounts CreateV2Accounts, args CreateV2Args) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 3)
	seeds = append(seeds, accounts.SolVault[:])
	seeds = append(seeds, accounts.TokenProgram[:])
	seeds = append(seeds, accounts.Mint[:])
	return solana.FindProgramAddress(seeds, solana.PublicKeyFromBytes([]byte{140, 151, 37, 143, 78, 36, 137, 241, 187, 61, 16, 41, 20, 142, 13, 131, 11, 90, 19, 153, 218, 255, 16, 132, 4, 142, 123, 216, 219, 233, 248, 89}))
}

func DeriveCreateV2EventAuthorityPDA(accounts CreateV2Accounts, args CreateV2Args) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 1)
	seeds = append(seeds, []byte{95, 95, 101, 118, 101, 110, 116, 95, 97, 117, 116, 104, 111, 114, 105, 116, 121})
	return solana.FindProgramAddress(seeds, ProgramKey)
}

var ExtendAccountDiscriminator = []byte{234, 102, 194, 203, 150, 72, 62, 229}

type ExtendAccountArgs struct{}

type ExtendAccountAccounts struct {
	Account        solana.PublicKey
	User           solana.PublicKey
	SystemProgram  solana.PublicKey
	EventAuthority solana.PublicKey
	Program        solana.PublicKey
}

func (a ExtendAccountAccounts) ToAccountMetas() []*solana.AccountMeta {
	metas := make([]*solana.AccountMeta, 0, 5)
	metas = append(metas, solana.NewAccountMeta(a.Account, true, false))
	metas = append(metas, solana.NewAccountMeta(a.User, false, true))
	var defaultExtendAccountSystemProgram = func() solana.PublicKey {
		return solana.MustPublicKeyFromBase58("11111111111111111111111111111111")
	}

	metas = append(metas, solana.NewAccountMeta(defaultExtendAccountSystemProgram(), false, false))
	metas = append(metas, solana.NewAccountMeta(a.EventAuthority, false, false))
	metas = append(metas, solana.NewAccountMeta(a.Program, false, false))
	return metas
}

func BuildExtendAccount(accounts ExtendAccountAccounts, args ExtendAccountArgs) (solana.Instruction, error) {
	buf := bytes.NewBuffer(make([]byte, 0, 128))
	buf.Write(ExtendAccountDiscriminator)
	data := buf.Bytes()
	return solana.NewInstruction(ProgramKey, accounts.ToAccountMetas(), data), nil
}

func DeriveExtendAccountEventAuthorityPDA(accounts ExtendAccountAccounts, args ExtendAccountArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 1)
	seeds = append(seeds, []byte{95, 95, 101, 118, 101, 110, 116, 95, 97, 117, 116, 104, 111, 114, 105, 116, 121})
	return solana.FindProgramAddress(seeds, ProgramKey)
}

var InitUserVolumeAccumulatorDiscriminator = []byte{94, 6, 202, 115, 255, 96, 232, 183}

type InitUserVolumeAccumulatorArgs struct{}

type InitUserVolumeAccumulatorAccounts struct {
	Payer                 solana.PublicKey
	User                  solana.PublicKey
	UserVolumeAccumulator solana.PublicKey
	SystemProgram         solana.PublicKey
	EventAuthority        solana.PublicKey
	Program               solana.PublicKey
}

func (a InitUserVolumeAccumulatorAccounts) ToAccountMetas() []*solana.AccountMeta {
	metas := make([]*solana.AccountMeta, 0, 6)
	metas = append(metas, solana.NewAccountMeta(a.Payer, true, true))
	metas = append(metas, solana.NewAccountMeta(a.User, false, false))
	metas = append(metas, solana.NewAccountMeta(a.UserVolumeAccumulator, true, false))
	var defaultInitUserVolumeAccumulatorSystemProgram = func() solana.PublicKey {
		return solana.MustPublicKeyFromBase58("11111111111111111111111111111111")
	}

	metas = append(metas, solana.NewAccountMeta(defaultInitUserVolumeAccumulatorSystemProgram(), false, false))
	metas = append(metas, solana.NewAccountMeta(a.EventAuthority, false, false))
	metas = append(metas, solana.NewAccountMeta(a.Program, false, false))
	return metas
}

func BuildInitUserVolumeAccumulator(accounts InitUserVolumeAccumulatorAccounts, args InitUserVolumeAccumulatorArgs) (solana.Instruction, error) {
	buf := bytes.NewBuffer(make([]byte, 0, 128))
	buf.Write(InitUserVolumeAccumulatorDiscriminator)
	data := buf.Bytes()
	return solana.NewInstruction(ProgramKey, accounts.ToAccountMetas(), data), nil
}

func DeriveInitUserVolumeAccumulatorUserVolumeAccumulatorPDA(accounts InitUserVolumeAccumulatorAccounts, args InitUserVolumeAccumulatorArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 2)
	seeds = append(seeds, []byte{117, 115, 101, 114, 95, 118, 111, 108, 117, 109, 101, 95, 97, 99, 99, 117, 109, 117, 108, 97, 116, 111, 114})
	seeds = append(seeds, accounts.User[:])
	return solana.FindProgramAddress(seeds, ProgramKey)
}

func DeriveInitUserVolumeAccumulatorEventAuthorityPDA(accounts InitUserVolumeAccumulatorAccounts, args InitUserVolumeAccumulatorArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 1)
	seeds = append(seeds, []byte{95, 95, 101, 118, 101, 110, 116, 95, 97, 117, 116, 104, 111, 114, 105, 116, 121})
	return solana.FindProgramAddress(seeds, ProgramKey)
}

var InitializeDiscriminator = []byte{175, 175, 109, 31, 13, 152, 155, 237}

type InitializeArgs struct{}

type InitializeAccounts struct {
	Global        solana.PublicKey
	User          solana.PublicKey
	SystemProgram solana.PublicKey
}

func (a InitializeAccounts) ToAccountMetas() []*solana.AccountMeta {
	metas := make([]*solana.AccountMeta, 0, 3)
	metas = append(metas, solana.NewAccountMeta(a.Global, true, false))
	metas = append(metas, solana.NewAccountMeta(a.User, true, true))
	var defaultInitializeSystemProgram = func() solana.PublicKey {
		return solana.MustPublicKeyFromBase58("11111111111111111111111111111111")
	}

	metas = append(metas, solana.NewAccountMeta(defaultInitializeSystemProgram(), false, false))
	return metas
}

func BuildInitialize(accounts InitializeAccounts, args InitializeArgs) (solana.Instruction, error) {
	buf := bytes.NewBuffer(make([]byte, 0, 128))
	buf.Write(InitializeDiscriminator)
	data := buf.Bytes()
	return solana.NewInstruction(ProgramKey, accounts.ToAccountMetas(), data), nil
}

func DeriveInitializeGlobalPDA(accounts InitializeAccounts, args InitializeArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 1)
	seeds = append(seeds, []byte{103, 108, 111, 98, 97, 108})
	return solana.FindProgramAddress(seeds, ProgramKey)
}

var MigrateDiscriminator = []byte{155, 234, 231, 146, 236, 158, 162, 30}

type MigrateArgs struct{}

type MigrateAccounts struct {
	Global                   solana.PublicKey
	WithdrawAuthority        solana.PublicKey
	Mint                     solana.PublicKey
	BondingCurve             solana.PublicKey
	AssociatedBondingCurve   solana.PublicKey
	User                     solana.PublicKey
	SystemProgram            solana.PublicKey
	TokenProgram             solana.PublicKey
	PumpAmm                  solana.PublicKey
	Pool                     solana.PublicKey
	PoolAuthority            solana.PublicKey
	PoolAuthorityMintAccount solana.PublicKey
	PoolAuthorityWsolAccount solana.PublicKey
	AmmGlobalConfig          solana.PublicKey
	WsolMint                 solana.PublicKey
	LpMint                   solana.PublicKey
	UserPoolTokenAccount     solana.PublicKey
	PoolBaseTokenAccount     solana.PublicKey
	PoolQuoteTokenAccount    solana.PublicKey
	Token2022Program         solana.PublicKey
	AssociatedTokenProgram   solana.PublicKey
	PumpAmmEventAuthority    solana.PublicKey
	EventAuthority           solana.PublicKey
	Program                  solana.PublicKey
}

func (a MigrateAccounts) ToAccountMetas() []*solana.AccountMeta {
	metas := make([]*solana.AccountMeta, 0, 24)
	metas = append(metas, solana.NewAccountMeta(a.Global, false, false))
	metas = append(metas, solana.NewAccountMeta(a.WithdrawAuthority, true, false))
	metas = append(metas, solana.NewAccountMeta(a.Mint, false, false))
	metas = append(metas, solana.NewAccountMeta(a.BondingCurve, true, false))
	metas = append(metas, solana.NewAccountMeta(a.AssociatedBondingCurve, true, false))
	metas = append(metas, solana.NewAccountMeta(a.User, false, true))
	var defaultMigrateSystemProgram = func() solana.PublicKey {
		return solana.MustPublicKeyFromBase58("11111111111111111111111111111111")
	}

	metas = append(metas, solana.NewAccountMeta(defaultMigrateSystemProgram(), false, false))
	var defaultMigrateTokenProgram = func() solana.PublicKey {
		return solana.MustPublicKeyFromBase58("TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA")
	}

	metas = append(metas, solana.NewAccountMeta(defaultMigrateTokenProgram(), false, false))
	var defaultMigratePumpAmm = func() solana.PublicKey {
		return solana.MustPublicKeyFromBase58("pAMMBay6oceH9fJKBRHGP5D4bD4sWpmSwMn52FMfXEA")
	}

	metas = append(metas, solana.NewAccountMeta(defaultMigratePumpAmm(), false, false))
	metas = append(metas, solana.NewAccountMeta(a.Pool, true, false))
	metas = append(metas, solana.NewAccountMeta(a.PoolAuthority, true, false))
	metas = append(metas, solana.NewAccountMeta(a.PoolAuthorityMintAccount, true, false))
	metas = append(metas, solana.NewAccountMeta(a.PoolAuthorityWsolAccount, true, false))
	metas = append(metas, solana.NewAccountMeta(a.AmmGlobalConfig, false, false))
	var defaultMigrateWsolMint = func() solana.PublicKey {
		return solana.MustPublicKeyFromBase58("So11111111111111111111111111111111111111112")
	}

	metas = append(metas, solana.NewAccountMeta(defaultMigrateWsolMint(), false, false))
	metas = append(metas, solana.NewAccountMeta(a.LpMint, true, false))
	metas = append(metas, solana.NewAccountMeta(a.UserPoolTokenAccount, true, false))
	metas = append(metas, solana.NewAccountMeta(a.PoolBaseTokenAccount, true, false))
	metas = append(metas, solana.NewAccountMeta(a.PoolQuoteTokenAccount, true, false))
	var defaultMigrateToken2022Program = func() solana.PublicKey {
		return solana.MustPublicKeyFromBase58("TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb")
	}

	metas = append(metas, solana.NewAccountMeta(defaultMigrateToken2022Program(), false, false))
	var defaultMigrateAssociatedTokenProgram = func() solana.PublicKey {
		return solana.MustPublicKeyFromBase58("ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL")
	}

	metas = append(metas, solana.NewAccountMeta(defaultMigrateAssociatedTokenProgram(), false, false))
	metas = append(metas, solana.NewAccountMeta(a.PumpAmmEventAuthority, false, false))
	metas = append(metas, solana.NewAccountMeta(a.EventAuthority, false, false))
	metas = append(metas, solana.NewAccountMeta(a.Program, false, false))
	return metas
}

func BuildMigrate(accounts MigrateAccounts, args MigrateArgs) (solana.Instruction, error) {
	buf := bytes.NewBuffer(make([]byte, 0, 128))
	buf.Write(MigrateDiscriminator)
	data := buf.Bytes()
	return solana.NewInstruction(ProgramKey, accounts.ToAccountMetas(), data), nil
}

func DeriveMigrateGlobalPDA(accounts MigrateAccounts, args MigrateArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 1)
	seeds = append(seeds, []byte{103, 108, 111, 98, 97, 108})
	return solana.FindProgramAddress(seeds, ProgramKey)
}

func DeriveMigrateBondingCurvePDA(accounts MigrateAccounts, args MigrateArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 2)
	seeds = append(seeds, []byte{98, 111, 110, 100, 105, 110, 103, 45, 99, 117, 114, 118, 101})
	seeds = append(seeds, accounts.Mint[:])
	return solana.FindProgramAddress(seeds, ProgramKey)
}

func DeriveMigrateAssociatedBondingCurvePDA(accounts MigrateAccounts, args MigrateArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 3)
	seeds = append(seeds, accounts.BondingCurve[:])
	seeds = append(seeds, accounts.Mint[:])
	seeds = append(seeds, accounts.Mint[:])
	return solana.FindProgramAddress(seeds, solana.PublicKeyFromBytes([]byte{140, 151, 37, 143, 78, 36, 137, 241, 187, 61, 16, 41, 20, 142, 13, 131, 11, 90, 19, 153, 218, 255, 16, 132, 4, 142, 123, 216, 219, 233, 248, 89}))
}

func DeriveMigratePoolPDA(accounts MigrateAccounts, args MigrateArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 5)
	seeds = append(seeds, []byte{112, 111, 111, 108})
	seeds = append(seeds, []byte{0, 0})
	seeds = append(seeds, accounts.PoolAuthority[:])
	seeds = append(seeds, accounts.Mint[:])
	seeds = append(seeds, accounts.WsolMint[:])
	return solana.FindProgramAddress(seeds, accounts.PumpAmm)
}

func DeriveMigratePoolAuthorityPDA(accounts MigrateAccounts, args MigrateArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 2)
	seeds = append(seeds, []byte{112, 111, 111, 108, 45, 97, 117, 116, 104, 111, 114, 105, 116, 121})
	seeds = append(seeds, accounts.Mint[:])
	return solana.FindProgramAddress(seeds, ProgramKey)
}

func DeriveMigratePoolAuthorityMintAccountPDA(accounts MigrateAccounts, args MigrateArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 3)
	seeds = append(seeds, accounts.PoolAuthority[:])
	seeds = append(seeds, accounts.Mint[:])
	seeds = append(seeds, accounts.Mint[:])
	return solana.FindProgramAddress(seeds, accounts.AssociatedTokenProgram)
}

func DeriveMigratePoolAuthorityWsolAccountPDA(accounts MigrateAccounts, args MigrateArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 3)
	seeds = append(seeds, accounts.PoolAuthority[:])
	seeds = append(seeds, accounts.TokenProgram[:])
	seeds = append(seeds, accounts.WsolMint[:])
	return solana.FindProgramAddress(seeds, accounts.AssociatedTokenProgram)
}

func DeriveMigrateAmmGlobalConfigPDA(accounts MigrateAccounts, args MigrateArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 1)
	seeds = append(seeds, []byte{103, 108, 111, 98, 97, 108, 95, 99, 111, 110, 102, 105, 103})
	return solana.FindProgramAddress(seeds, accounts.PumpAmm)
}

func DeriveMigrateLpMintPDA(accounts MigrateAccounts, args MigrateArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 2)
	seeds = append(seeds, []byte{112, 111, 111, 108, 95, 108, 112, 95, 109, 105, 110, 116})
	seeds = append(seeds, accounts.Pool[:])
	return solana.FindProgramAddress(seeds, accounts.PumpAmm)
}

func DeriveMigrateUserPoolTokenAccountPDA(accounts MigrateAccounts, args MigrateArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 3)
	seeds = append(seeds, accounts.PoolAuthority[:])
	seeds = append(seeds, accounts.Token2022Program[:])
	seeds = append(seeds, accounts.LpMint[:])
	return solana.FindProgramAddress(seeds, accounts.AssociatedTokenProgram)
}

func DeriveMigratePoolBaseTokenAccountPDA(accounts MigrateAccounts, args MigrateArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 3)
	seeds = append(seeds, accounts.Pool[:])
	seeds = append(seeds, accounts.Mint[:])
	seeds = append(seeds, accounts.Mint[:])
	return solana.FindProgramAddress(seeds, accounts.AssociatedTokenProgram)
}

func DeriveMigratePoolQuoteTokenAccountPDA(accounts MigrateAccounts, args MigrateArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 3)
	seeds = append(seeds, accounts.Pool[:])
	seeds = append(seeds, accounts.TokenProgram[:])
	seeds = append(seeds, accounts.WsolMint[:])
	return solana.FindProgramAddress(seeds, accounts.AssociatedTokenProgram)
}

func DeriveMigratePumpAmmEventAuthorityPDA(accounts MigrateAccounts, args MigrateArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 1)
	seeds = append(seeds, []byte{95, 95, 101, 118, 101, 110, 116, 95, 97, 117, 116, 104, 111, 114, 105, 116, 121})
	return solana.FindProgramAddress(seeds, accounts.PumpAmm)
}

func DeriveMigrateEventAuthorityPDA(accounts MigrateAccounts, args MigrateArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 1)
	seeds = append(seeds, []byte{95, 95, 101, 118, 101, 110, 116, 95, 97, 117, 116, 104, 111, 114, 105, 116, 121})
	return solana.FindProgramAddress(seeds, ProgramKey)
}

var SellDiscriminator = []byte{51, 230, 133, 164, 1, 127, 131, 173}

type SellArgs struct {
	Amount       uint64 `bin:"amount"`
	MinSolOutput uint64 `bin:"min_sol_output"`
}

type SellAccounts struct {
	Global                 solana.PublicKey
	FeeRecipient           solana.PublicKey
	Mint                   solana.PublicKey
	BondingCurve           solana.PublicKey
	AssociatedBondingCurve solana.PublicKey
	AssociatedUser         solana.PublicKey
	User                   solana.PublicKey
	SystemProgram          solana.PublicKey
	CreatorVault           solana.PublicKey
	TokenProgram           solana.PublicKey
	EventAuthority         solana.PublicKey
	Program                solana.PublicKey
	FeeConfig              solana.PublicKey
	FeeProgram             solana.PublicKey
}

func (a SellAccounts) ToAccountMetas() []*solana.AccountMeta {
	metas := make([]*solana.AccountMeta, 0, 14)
	metas = append(metas, solana.NewAccountMeta(a.Global, false, false))
	metas = append(metas, solana.NewAccountMeta(a.FeeRecipient, true, false))
	metas = append(metas, solana.NewAccountMeta(a.Mint, false, false))
	metas = append(metas, solana.NewAccountMeta(a.BondingCurve, true, false))
	metas = append(metas, solana.NewAccountMeta(a.AssociatedBondingCurve, true, false))
	metas = append(metas, solana.NewAccountMeta(a.AssociatedUser, true, false))
	metas = append(metas, solana.NewAccountMeta(a.User, true, true))
	var defaultSellSystemProgram = func() solana.PublicKey {
		return solana.MustPublicKeyFromBase58("11111111111111111111111111111111")
	}

	metas = append(metas, solana.NewAccountMeta(defaultSellSystemProgram(), false, false))
	metas = append(metas, solana.NewAccountMeta(a.CreatorVault, true, false))
	metas = append(metas, solana.NewAccountMeta(a.TokenProgram, false, false))
	metas = append(metas, solana.NewAccountMeta(a.EventAuthority, false, false))
	var defaultSellProgram = func() solana.PublicKey {
		return solana.MustPublicKeyFromBase58("6EF8rrecthR5Dkzon8Nwu78hRvfCKubJ14M5uBEwF6P")
	}

	metas = append(metas, solana.NewAccountMeta(defaultSellProgram(), false, false))
	metas = append(metas, solana.NewAccountMeta(a.FeeConfig, false, false))
	var defaultSellFeeProgram = func() solana.PublicKey {
		return solana.MustPublicKeyFromBase58("pfeeUxB6jkeY1Hxd7CsFCAjcbHA9rWtchMGdZ6VojVZ")
	}

	metas = append(metas, solana.NewAccountMeta(defaultSellFeeProgram(), false, false))
	return metas
}

func BuildSell(accounts SellAccounts, args SellArgs) (solana.Instruction, error) {
	buf := bytes.NewBuffer(make([]byte, 0, 128))
	buf.Write(SellDiscriminator)
	if err := bin.NewBorshEncoder(buf).Encode(args); err != nil {
		return nil, fmt.Errorf("encode args: %w", err)
	}
	data := buf.Bytes()
	return solana.NewInstruction(ProgramKey, accounts.ToAccountMetas(), data), nil
}

func DeriveSellGlobalPDA(accounts SellAccounts, args SellArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 1)
	seeds = append(seeds, []byte{103, 108, 111, 98, 97, 108})
	return solana.FindProgramAddress(seeds, ProgramKey)
}

func DeriveSellBondingCurvePDA(accounts SellAccounts, args SellArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 2)
	seeds = append(seeds, []byte{98, 111, 110, 100, 105, 110, 103, 45, 99, 117, 114, 118, 101})
	seeds = append(seeds, accounts.Mint[:])
	return solana.FindProgramAddress(seeds, ProgramKey)
}

func DeriveSellAssociatedBondingCurvePDA(accounts SellAccounts, args SellArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 3)
	seeds = append(seeds, accounts.BondingCurve[:])
	seeds = append(seeds, accounts.TokenProgram[:])
	seeds = append(seeds, accounts.Mint[:])
	return solana.FindProgramAddress(seeds, solana.PublicKeyFromBytes([]byte{140, 151, 37, 143, 78, 36, 137, 241, 187, 61, 16, 41, 20, 142, 13, 131, 11, 90, 19, 153, 218, 255, 16, 132, 4, 142, 123, 216, 219, 233, 248, 89}))
}

func DeriveSellCreatorVaultPDA(accounts SellAccounts, args SellArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 2)
	seeds = append(seeds, []byte{99, 114, 101, 97, 116, 111, 114, 45, 118, 97, 117, 108, 116})
	seeds = append(seeds, accounts.BondingCurve[:])
	return solana.FindProgramAddress(seeds, ProgramKey)
}

func DeriveSellEventAuthorityPDA(accounts SellAccounts, args SellArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 1)
	seeds = append(seeds, []byte{95, 95, 101, 118, 101, 110, 116, 95, 97, 117, 116, 104, 111, 114, 105, 116, 121})
	return solana.FindProgramAddress(seeds, ProgramKey)
}

func DeriveSellFeeConfigPDA(accounts SellAccounts, args SellArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 2)
	seeds = append(seeds, []byte{102, 101, 101, 95, 99, 111, 110, 102, 105, 103})
	seeds = append(seeds, []byte{1, 86, 224, 246, 147, 102, 90, 207, 68, 219, 21, 104, 191, 23, 91, 170, 81, 137, 203, 151, 245, 210, 255, 59, 101, 93, 43, 182, 253, 109, 24, 176})
	return solana.FindProgramAddress(seeds, accounts.FeeProgram)
}

var SetCreatorDiscriminator = []byte{254, 148, 255, 112, 207, 142, 170, 165}

type SetCreatorArgs struct {
	Creator solana.PublicKey `bin:"creator"`
}

type SetCreatorAccounts struct {
	SetCreatorAuthority solana.PublicKey
	Global              solana.PublicKey
	Mint                solana.PublicKey
	Metadata            solana.PublicKey
	BondingCurve        solana.PublicKey
	EventAuthority      solana.PublicKey
	Program             solana.PublicKey
}

func (a SetCreatorAccounts) ToAccountMetas() []*solana.AccountMeta {
	metas := make([]*solana.AccountMeta, 0, 7)
	metas = append(metas, solana.NewAccountMeta(a.SetCreatorAuthority, false, true))
	metas = append(metas, solana.NewAccountMeta(a.Global, false, false))
	metas = append(metas, solana.NewAccountMeta(a.Mint, false, false))
	metas = append(metas, solana.NewAccountMeta(a.Metadata, false, false))
	metas = append(metas, solana.NewAccountMeta(a.BondingCurve, true, false))
	metas = append(metas, solana.NewAccountMeta(a.EventAuthority, false, false))
	metas = append(metas, solana.NewAccountMeta(a.Program, false, false))
	return metas
}

func BuildSetCreator(accounts SetCreatorAccounts, args SetCreatorArgs) (solana.Instruction, error) {
	buf := bytes.NewBuffer(make([]byte, 0, 128))
	buf.Write(SetCreatorDiscriminator)
	if err := bin.NewBorshEncoder(buf).Encode(args); err != nil {
		return nil, fmt.Errorf("encode args: %w", err)
	}
	data := buf.Bytes()
	return solana.NewInstruction(ProgramKey, accounts.ToAccountMetas(), data), nil
}

func DeriveSetCreatorGlobalPDA(accounts SetCreatorAccounts, args SetCreatorArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 1)
	seeds = append(seeds, []byte{103, 108, 111, 98, 97, 108})
	return solana.FindProgramAddress(seeds, ProgramKey)
}

func DeriveSetCreatorMetadataPDA(accounts SetCreatorAccounts, args SetCreatorArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 3)
	seeds = append(seeds, []byte{109, 101, 116, 97, 100, 97, 116, 97})
	seeds = append(seeds, []byte{11, 112, 101, 177, 227, 209, 124, 69, 56, 157, 82, 127, 107, 4, 195, 205, 88, 184, 108, 115, 26, 160, 253, 181, 73, 182, 209, 188, 3, 248, 41, 70})
	seeds = append(seeds, accounts.Mint[:])
	return solana.FindProgramAddress(seeds, solana.PublicKeyFromBytes([]byte{11, 112, 101, 177, 227, 209, 124, 69, 56, 157, 82, 127, 107, 4, 195, 205, 88, 184, 108, 115, 26, 160, 253, 181, 73, 182, 209, 188, 3, 248, 41, 70}))
}

func DeriveSetCreatorBondingCurvePDA(accounts SetCreatorAccounts, args SetCreatorArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 2)
	seeds = append(seeds, []byte{98, 111, 110, 100, 105, 110, 103, 45, 99, 117, 114, 118, 101})
	seeds = append(seeds, accounts.Mint[:])
	return solana.FindProgramAddress(seeds, ProgramKey)
}

func DeriveSetCreatorEventAuthorityPDA(accounts SetCreatorAccounts, args SetCreatorArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 1)
	seeds = append(seeds, []byte{95, 95, 101, 118, 101, 110, 116, 95, 97, 117, 116, 104, 111, 114, 105, 116, 121})
	return solana.FindProgramAddress(seeds, ProgramKey)
}

var SetMetaplexCreatorDiscriminator = []byte{138, 96, 174, 217, 48, 85, 197, 246}

type SetMetaplexCreatorArgs struct{}

type SetMetaplexCreatorAccounts struct {
	Mint           solana.PublicKey
	Metadata       solana.PublicKey
	BondingCurve   solana.PublicKey
	EventAuthority solana.PublicKey
	Program        solana.PublicKey
}

func (a SetMetaplexCreatorAccounts) ToAccountMetas() []*solana.AccountMeta {
	metas := make([]*solana.AccountMeta, 0, 5)
	metas = append(metas, solana.NewAccountMeta(a.Mint, false, false))
	metas = append(metas, solana.NewAccountMeta(a.Metadata, false, false))
	metas = append(metas, solana.NewAccountMeta(a.BondingCurve, true, false))
	metas = append(metas, solana.NewAccountMeta(a.EventAuthority, false, false))
	metas = append(metas, solana.NewAccountMeta(a.Program, false, false))
	return metas
}

func BuildSetMetaplexCreator(accounts SetMetaplexCreatorAccounts, args SetMetaplexCreatorArgs) (solana.Instruction, error) {
	buf := bytes.NewBuffer(make([]byte, 0, 128))
	buf.Write(SetMetaplexCreatorDiscriminator)
	data := buf.Bytes()
	return solana.NewInstruction(ProgramKey, accounts.ToAccountMetas(), data), nil
}

func DeriveSetMetaplexCreatorMetadataPDA(accounts SetMetaplexCreatorAccounts, args SetMetaplexCreatorArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 3)
	seeds = append(seeds, []byte{109, 101, 116, 97, 100, 97, 116, 97})
	seeds = append(seeds, []byte{11, 112, 101, 177, 227, 209, 124, 69, 56, 157, 82, 127, 107, 4, 195, 205, 88, 184, 108, 115, 26, 160, 253, 181, 73, 182, 209, 188, 3, 248, 41, 70})
	seeds = append(seeds, accounts.Mint[:])
	return solana.FindProgramAddress(seeds, solana.PublicKeyFromBytes([]byte{11, 112, 101, 177, 227, 209, 124, 69, 56, 157, 82, 127, 107, 4, 195, 205, 88, 184, 108, 115, 26, 160, 253, 181, 73, 182, 209, 188, 3, 248, 41, 70}))
}

func DeriveSetMetaplexCreatorBondingCurvePDA(accounts SetMetaplexCreatorAccounts, args SetMetaplexCreatorArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 2)
	seeds = append(seeds, []byte{98, 111, 110, 100, 105, 110, 103, 45, 99, 117, 114, 118, 101})
	seeds = append(seeds, accounts.Mint[:])
	return solana.FindProgramAddress(seeds, ProgramKey)
}

func DeriveSetMetaplexCreatorEventAuthorityPDA(accounts SetMetaplexCreatorAccounts, args SetMetaplexCreatorArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 1)
	seeds = append(seeds, []byte{95, 95, 101, 118, 101, 110, 116, 95, 97, 117, 116, 104, 111, 114, 105, 116, 121})
	return solana.FindProgramAddress(seeds, ProgramKey)
}

var SetParamsDiscriminator = []byte{27, 234, 178, 52, 147, 2, 187, 141}

type SetParamsArgs struct {
	InitialVirtualTokenReserves uint64           `bin:"initial_virtual_token_reserves"`
	InitialVirtualSolReserves   uint64           `bin:"initial_virtual_sol_reserves"`
	InitialRealTokenReserves    uint64           `bin:"initial_real_token_reserves"`
	TokenTotalSupply            uint64           `bin:"token_total_supply"`
	FeeBasisPoints              uint64           `bin:"fee_basis_points"`
	WithdrawAuthority           solana.PublicKey `bin:"withdraw_authority"`
	EnableMigrate               bool             `bin:"enable_migrate"`
	PoolMigrationFee            uint64           `bin:"pool_migration_fee"`
	CreatorFeeBasisPoints       uint64           `bin:"creator_fee_basis_points"`
	SetCreatorAuthority         solana.PublicKey `bin:"set_creator_authority"`
	AdminSetCreatorAuthority    solana.PublicKey `bin:"admin_set_creator_authority"`
}

type SetParamsAccounts struct {
	Global         solana.PublicKey
	Authority      solana.PublicKey
	EventAuthority solana.PublicKey
	Program        solana.PublicKey
}

func (a SetParamsAccounts) ToAccountMetas() []*solana.AccountMeta {
	metas := make([]*solana.AccountMeta, 0, 4)
	metas = append(metas, solana.NewAccountMeta(a.Global, true, false))
	metas = append(metas, solana.NewAccountMeta(a.Authority, true, true))
	metas = append(metas, solana.NewAccountMeta(a.EventAuthority, false, false))
	metas = append(metas, solana.NewAccountMeta(a.Program, false, false))
	return metas
}

func BuildSetParams(accounts SetParamsAccounts, args SetParamsArgs) (solana.Instruction, error) {
	buf := bytes.NewBuffer(make([]byte, 0, 128))
	buf.Write(SetParamsDiscriminator)
	if err := bin.NewBorshEncoder(buf).Encode(args); err != nil {
		return nil, fmt.Errorf("encode args: %w", err)
	}
	data := buf.Bytes()
	return solana.NewInstruction(ProgramKey, accounts.ToAccountMetas(), data), nil
}

func DeriveSetParamsGlobalPDA(accounts SetParamsAccounts, args SetParamsArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 1)
	seeds = append(seeds, []byte{103, 108, 111, 98, 97, 108})
	return solana.FindProgramAddress(seeds, ProgramKey)
}

func DeriveSetParamsEventAuthorityPDA(accounts SetParamsAccounts, args SetParamsArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 1)
	seeds = append(seeds, []byte{95, 95, 101, 118, 101, 110, 116, 95, 97, 117, 116, 104, 111, 114, 105, 116, 121})
	return solana.FindProgramAddress(seeds, ProgramKey)
}

var SetReservedFeeRecipientsDiscriminator = []byte{111, 172, 162, 232, 114, 89, 213, 142}

type SetReservedFeeRecipientsArgs struct {
	WhitelistPda solana.PublicKey `bin:"whitelist_pda"`
}

type SetReservedFeeRecipientsAccounts struct {
	Global         solana.PublicKey
	Authority      solana.PublicKey
	EventAuthority solana.PublicKey
	Program        solana.PublicKey
}

func (a SetReservedFeeRecipientsAccounts) ToAccountMetas() []*solana.AccountMeta {
	metas := make([]*solana.AccountMeta, 0, 4)
	metas = append(metas, solana.NewAccountMeta(a.Global, true, false))
	metas = append(metas, solana.NewAccountMeta(a.Authority, false, true))
	metas = append(metas, solana.NewAccountMeta(a.EventAuthority, false, false))
	metas = append(metas, solana.NewAccountMeta(a.Program, false, false))
	return metas
}

func BuildSetReservedFeeRecipients(accounts SetReservedFeeRecipientsAccounts, args SetReservedFeeRecipientsArgs) (solana.Instruction, error) {
	buf := bytes.NewBuffer(make([]byte, 0, 128))
	buf.Write(SetReservedFeeRecipientsDiscriminator)
	if err := bin.NewBorshEncoder(buf).Encode(args); err != nil {
		return nil, fmt.Errorf("encode args: %w", err)
	}
	data := buf.Bytes()
	return solana.NewInstruction(ProgramKey, accounts.ToAccountMetas(), data), nil
}

func DeriveSetReservedFeeRecipientsGlobalPDA(accounts SetReservedFeeRecipientsAccounts, args SetReservedFeeRecipientsArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 1)
	seeds = append(seeds, []byte{103, 108, 111, 98, 97, 108})
	return solana.FindProgramAddress(seeds, ProgramKey)
}

func DeriveSetReservedFeeRecipientsEventAuthorityPDA(accounts SetReservedFeeRecipientsAccounts, args SetReservedFeeRecipientsArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 1)
	seeds = append(seeds, []byte{95, 95, 101, 118, 101, 110, 116, 95, 97, 117, 116, 104, 111, 114, 105, 116, 121})
	return solana.FindProgramAddress(seeds, ProgramKey)
}

var SyncUserVolumeAccumulatorDiscriminator = []byte{86, 31, 192, 87, 163, 87, 79, 238}

type SyncUserVolumeAccumulatorArgs struct{}

type SyncUserVolumeAccumulatorAccounts struct {
	User                    solana.PublicKey
	GlobalVolumeAccumulator solana.PublicKey
	UserVolumeAccumulator   solana.PublicKey
	EventAuthority          solana.PublicKey
	Program                 solana.PublicKey
}

func (a SyncUserVolumeAccumulatorAccounts) ToAccountMetas() []*solana.AccountMeta {
	metas := make([]*solana.AccountMeta, 0, 5)
	metas = append(metas, solana.NewAccountMeta(a.User, false, false))
	metas = append(metas, solana.NewAccountMeta(a.GlobalVolumeAccumulator, false, false))
	metas = append(metas, solana.NewAccountMeta(a.UserVolumeAccumulator, true, false))
	metas = append(metas, solana.NewAccountMeta(a.EventAuthority, false, false))
	metas = append(metas, solana.NewAccountMeta(a.Program, false, false))
	return metas
}

func BuildSyncUserVolumeAccumulator(accounts SyncUserVolumeAccumulatorAccounts, args SyncUserVolumeAccumulatorArgs) (solana.Instruction, error) {
	buf := bytes.NewBuffer(make([]byte, 0, 128))
	buf.Write(SyncUserVolumeAccumulatorDiscriminator)
	data := buf.Bytes()
	return solana.NewInstruction(ProgramKey, accounts.ToAccountMetas(), data), nil
}

func DeriveSyncUserVolumeAccumulatorGlobalVolumeAccumulatorPDA(accounts SyncUserVolumeAccumulatorAccounts, args SyncUserVolumeAccumulatorArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 1)
	seeds = append(seeds, []byte{103, 108, 111, 98, 97, 108, 95, 118, 111, 108, 117, 109, 101, 95, 97, 99, 99, 117, 109, 117, 108, 97, 116, 111, 114})
	return solana.FindProgramAddress(seeds, ProgramKey)
}

func DeriveSyncUserVolumeAccumulatorUserVolumeAccumulatorPDA(accounts SyncUserVolumeAccumulatorAccounts, args SyncUserVolumeAccumulatorArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 2)
	seeds = append(seeds, []byte{117, 115, 101, 114, 95, 118, 111, 108, 117, 109, 101, 95, 97, 99, 99, 117, 109, 117, 108, 97, 116, 111, 114})
	seeds = append(seeds, accounts.User[:])
	return solana.FindProgramAddress(seeds, ProgramKey)
}

func DeriveSyncUserVolumeAccumulatorEventAuthorityPDA(accounts SyncUserVolumeAccumulatorAccounts, args SyncUserVolumeAccumulatorArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 1)
	seeds = append(seeds, []byte{95, 95, 101, 118, 101, 110, 116, 95, 97, 117, 116, 104, 111, 114, 105, 116, 121})
	return solana.FindProgramAddress(seeds, ProgramKey)
}

var ToggleCreateV2Discriminator = []byte{28, 255, 230, 240, 172, 107, 203, 171}

type ToggleCreateV2Args struct {
	Enabled bool `bin:"enabled"`
}

type ToggleCreateV2Accounts struct {
	Global         solana.PublicKey
	Authority      solana.PublicKey
	EventAuthority solana.PublicKey
	Program        solana.PublicKey
}

func (a ToggleCreateV2Accounts) ToAccountMetas() []*solana.AccountMeta {
	metas := make([]*solana.AccountMeta, 0, 4)
	metas = append(metas, solana.NewAccountMeta(a.Global, true, false))
	metas = append(metas, solana.NewAccountMeta(a.Authority, true, true))
	metas = append(metas, solana.NewAccountMeta(a.EventAuthority, false, false))
	metas = append(metas, solana.NewAccountMeta(a.Program, false, false))
	return metas
}

func BuildToggleCreateV2(accounts ToggleCreateV2Accounts, args ToggleCreateV2Args) (solana.Instruction, error) {
	buf := bytes.NewBuffer(make([]byte, 0, 128))
	buf.Write(ToggleCreateV2Discriminator)
	if err := bin.NewBorshEncoder(buf).Encode(args); err != nil {
		return nil, fmt.Errorf("encode args: %w", err)
	}
	data := buf.Bytes()
	return solana.NewInstruction(ProgramKey, accounts.ToAccountMetas(), data), nil
}

func DeriveToggleCreateV2GlobalPDA(accounts ToggleCreateV2Accounts, args ToggleCreateV2Args) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 1)
	seeds = append(seeds, []byte{103, 108, 111, 98, 97, 108})
	return solana.FindProgramAddress(seeds, ProgramKey)
}

func DeriveToggleCreateV2EventAuthorityPDA(accounts ToggleCreateV2Accounts, args ToggleCreateV2Args) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 1)
	seeds = append(seeds, []byte{95, 95, 101, 118, 101, 110, 116, 95, 97, 117, 116, 104, 111, 114, 105, 116, 121})
	return solana.FindProgramAddress(seeds, ProgramKey)
}

var ToggleMayhemModeDiscriminator = []byte{1, 9, 111, 208, 100, 31, 255, 163}

type ToggleMayhemModeArgs struct {
	Enabled bool `bin:"enabled"`
}

type ToggleMayhemModeAccounts struct {
	Global         solana.PublicKey
	Authority      solana.PublicKey
	EventAuthority solana.PublicKey
	Program        solana.PublicKey
}

func (a ToggleMayhemModeAccounts) ToAccountMetas() []*solana.AccountMeta {
	metas := make([]*solana.AccountMeta, 0, 4)
	metas = append(metas, solana.NewAccountMeta(a.Global, true, false))
	metas = append(metas, solana.NewAccountMeta(a.Authority, true, true))
	metas = append(metas, solana.NewAccountMeta(a.EventAuthority, false, false))
	metas = append(metas, solana.NewAccountMeta(a.Program, false, false))
	return metas
}

func BuildToggleMayhemMode(accounts ToggleMayhemModeAccounts, args ToggleMayhemModeArgs) (solana.Instruction, error) {
	buf := bytes.NewBuffer(make([]byte, 0, 128))
	buf.Write(ToggleMayhemModeDiscriminator)
	if err := bin.NewBorshEncoder(buf).Encode(args); err != nil {
		return nil, fmt.Errorf("encode args: %w", err)
	}
	data := buf.Bytes()
	return solana.NewInstruction(ProgramKey, accounts.ToAccountMetas(), data), nil
}

func DeriveToggleMayhemModeGlobalPDA(accounts ToggleMayhemModeAccounts, args ToggleMayhemModeArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 1)
	seeds = append(seeds, []byte{103, 108, 111, 98, 97, 108})
	return solana.FindProgramAddress(seeds, ProgramKey)
}

func DeriveToggleMayhemModeEventAuthorityPDA(accounts ToggleMayhemModeAccounts, args ToggleMayhemModeArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 1)
	seeds = append(seeds, []byte{95, 95, 101, 118, 101, 110, 116, 95, 97, 117, 116, 104, 111, 114, 105, 116, 121})
	return solana.FindProgramAddress(seeds, ProgramKey)
}

var UpdateGlobalAuthorityDiscriminator = []byte{227, 181, 74, 196, 208, 21, 97, 213}

type UpdateGlobalAuthorityArgs struct{}

type UpdateGlobalAuthorityAccounts struct {
	Global         solana.PublicKey
	Authority      solana.PublicKey
	NewAuthority   solana.PublicKey
	EventAuthority solana.PublicKey
	Program        solana.PublicKey
}

func (a UpdateGlobalAuthorityAccounts) ToAccountMetas() []*solana.AccountMeta {
	metas := make([]*solana.AccountMeta, 0, 5)
	metas = append(metas, solana.NewAccountMeta(a.Global, true, false))
	metas = append(metas, solana.NewAccountMeta(a.Authority, false, true))
	metas = append(metas, solana.NewAccountMeta(a.NewAuthority, false, false))
	metas = append(metas, solana.NewAccountMeta(a.EventAuthority, false, false))
	metas = append(metas, solana.NewAccountMeta(a.Program, false, false))
	return metas
}

func BuildUpdateGlobalAuthority(accounts UpdateGlobalAuthorityAccounts, args UpdateGlobalAuthorityArgs) (solana.Instruction, error) {
	buf := bytes.NewBuffer(make([]byte, 0, 128))
	buf.Write(UpdateGlobalAuthorityDiscriminator)
	data := buf.Bytes()
	return solana.NewInstruction(ProgramKey, accounts.ToAccountMetas(), data), nil
}

func DeriveUpdateGlobalAuthorityGlobalPDA(accounts UpdateGlobalAuthorityAccounts, args UpdateGlobalAuthorityArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 1)
	seeds = append(seeds, []byte{103, 108, 111, 98, 97, 108})
	return solana.FindProgramAddress(seeds, ProgramKey)
}

func DeriveUpdateGlobalAuthorityEventAuthorityPDA(accounts UpdateGlobalAuthorityAccounts, args UpdateGlobalAuthorityArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 1)
	seeds = append(seeds, []byte{95, 95, 101, 118, 101, 110, 116, 95, 97, 117, 116, 104, 111, 114, 105, 116, 121})
	return solana.FindProgramAddress(seeds, ProgramKey)
}
