// Code generated by internal/gen; DO NOT EDIT.

package pump

import (
	bin "github.com/gagliardetto/binary"
	"github.com/gagliardetto/solana-go"
)

type AdminSetCreatorEvent struct {
	Timestamp                int64            `bin:"timestamp"`
	AdminSetCreatorAuthority solana.PublicKey `bin:"admin_set_creator_authority"`
	Mint                     solana.PublicKey `bin:"mint"`
	BondingCurve             solana.PublicKey `bin:"bonding_curve"`
	OldCreator               solana.PublicKey `bin:"old_creator"`
	NewCreator               solana.PublicKey `bin:"new_creator"`
}

type AdminSetIdlAuthorityEvent struct {
	IdlAuthority solana.PublicKey `bin:"idl_authority"`
}

type AdminUpdateTokenIncentivesEvent struct {
	StartTime         int64            `bin:"start_time"`
	EndTime           int64            `bin:"end_time"`
	DayNumber         uint64           `bin:"day_number"`
	TokenSupplyPerDay uint64           `bin:"token_supply_per_day"`
	Mint              solana.PublicKey `bin:"mint"`
	SecondsInADay     int64            `bin:"seconds_in_a_day"`
	Timestamp         int64            `bin:"timestamp"`
}

type BondingCurve struct {
	VirtualTokenReserves uint64           `bin:"virtual_token_reserves"`
	VirtualQuoteReserves uint64           `bin:"virtual_quote_reserves"`
	RealTokenReserves    uint64           `bin:"real_token_reserves"`
	RealQuoteReserves    uint64           `bin:"real_quote_reserves"`
	TokenTotalSupply     uint64           `bin:"token_total_supply"`
	Complete             bool             `bin:"complete"`
	Creator              solana.PublicKey `bin:"creator"`
	IsMayhemMode         bool             `bin:"is_mayhem_mode"`
	IsCashbackCoin       bool             `bin:"is_cashback_coin"`
	QuoteMint            solana.PublicKey `bin:"quote_mint"`
}

type ClaimCashbackEvent struct {
	User                solana.PublicKey `bin:"user"`
	Amount              uint64           `bin:"amount"`
	Timestamp           int64            `bin:"timestamp"`
	TotalClaimed        uint64           `bin:"total_claimed"`
	TotalCashbackEarned uint64           `bin:"total_cashback_earned"`
}

type ClaimTokenIncentivesEvent struct {
	User               solana.PublicKey `bin:"user"`
	Mint               solana.PublicKey `bin:"mint"`
	Amount             uint64           `bin:"amount"`
	Timestamp          int64            `bin:"timestamp"`
	TotalClaimedTokens uint64           `bin:"total_claimed_tokens"`
	CurrentSolVolume   uint64           `bin:"current_sol_volume"`
}

type CloseUserVolumeAccumulatorEvent struct {
	User                 solana.PublicKey `bin:"user"`
	Timestamp            int64            `bin:"timestamp"`
	TotalUnclaimedTokens uint64           `bin:"total_unclaimed_tokens"`
	TotalClaimedTokens   uint64           `bin:"total_claimed_tokens"`
	CurrentSolVolume     uint64           `bin:"current_sol_volume"`
	LastUpdateTimestamp  int64            `bin:"last_update_timestamp"`
}

type CollectCreatorFeeEvent struct {
	Timestamp  int64            `bin:"timestamp"`
	Creator    solana.PublicKey `bin:"creator"`
	CreatorFee uint64           `bin:"creator_fee"`
	QuoteMint  solana.PublicKey `bin:"quote_mint"`
}

type CompleteEvent struct {
	User         solana.PublicKey `bin:"user"`
	Mint         solana.PublicKey `bin:"mint"`
	BondingCurve solana.PublicKey `bin:"bonding_curve"`
	Timestamp    int64            `bin:"timestamp"`
	QuoteMint    solana.PublicKey `bin:"quote_mint"`
}

type CompletePumpAmmMigrationEvent struct {
	User             solana.PublicKey `bin:"user"`
	Mint             solana.PublicKey `bin:"mint"`
	MintAmount       uint64           `bin:"mint_amount"`
	SolAmount        uint64           `bin:"sol_amount"`
	PoolMigrationFee uint64           `bin:"pool_migration_fee"`
	BondingCurve     solana.PublicKey `bin:"bonding_curve"`
	Timestamp        int64            `bin:"timestamp"`
	Pool             solana.PublicKey `bin:"pool"`
	QuoteMint        solana.PublicKey `bin:"quote_mint"`
}

type ConfigStatus uint8

const (
	ConfigStatusPaused ConfigStatus = iota
	ConfigStatusActive
)

type CreateEvent struct {
	Name                 string           `bin:"name"`
	Symbol               string           `bin:"symbol"`
	Uri                  string           `bin:"uri"`
	Mint                 solana.PublicKey `bin:"mint"`
	BondingCurve         solana.PublicKey `bin:"bonding_curve"`
	User                 solana.PublicKey `bin:"user"`
	Creator              solana.PublicKey `bin:"creator"`
	Timestamp            int64            `bin:"timestamp"`
	VirtualTokenReserves uint64           `bin:"virtual_token_reserves"`
	VirtualSolReserves   uint64           `bin:"virtual_sol_reserves"`
	RealTokenReserves    uint64           `bin:"real_token_reserves"`
	TokenTotalSupply     uint64           `bin:"token_total_supply"`
	TokenProgram         solana.PublicKey `bin:"token_program"`
	IsMayhemMode         bool             `bin:"is_mayhem_mode"`
	IsCashbackEnabled    bool             `bin:"is_cashback_enabled"`
	QuoteMint            solana.PublicKey `bin:"quote_mint"`
	VirtualQuoteReserves uint64           `bin:"virtual_quote_reserves"`
}

type DistributeCreatorFeesEvent struct {
	Timestamp     int64            `bin:"timestamp"`
	Mint          solana.PublicKey `bin:"mint"`
	BondingCurve  solana.PublicKey `bin:"bonding_curve"`
	SharingConfig solana.PublicKey `bin:"sharing_config"`
	Admin         solana.PublicKey `bin:"admin"`
	Shareholders  []Shareholder    `bin:"shareholders"`
	Distributed   uint64           `bin:"distributed"`
	QuoteMint     solana.PublicKey `bin:"quote_mint"`
}

type ExtendAccountEvent struct {
	Account     solana.PublicKey `bin:"account"`
	User        solana.PublicKey `bin:"user"`
	CurrentSize uint64           `bin:"current_size"`
	NewSize     uint64           `bin:"new_size"`
	Timestamp   int64            `bin:"timestamp"`
}

type FeeConfig struct {
	Bump           uint8            `bin:"bump"`
	Admin          solana.PublicKey `bin:"admin"`
	FlatFees       Fees             `bin:"flat_fees"`
	FeeTiers       []FeeTier        `bin:"fee_tiers"`
	StableFeeTiers []FeeTier        `bin:"stable_fee_tiers"`
}

type FeeTier struct {
	MarketCapLamportsThreshold bin.Uint128 `bin:"market_cap_lamports_threshold"`
	Fees                       Fees        `bin:"fees"`
}

type Fees struct {
	LpFeeBps       uint64 `bin:"lp_fee_bps"`
	ProtocolFeeBps uint64 `bin:"protocol_fee_bps"`
	CreatorFeeBps  uint64 `bin:"creator_fee_bps"`
}

type Global struct {
	Initialized                 bool                `bin:"initialized"`
	Authority                   solana.PublicKey    `bin:"authority"`
	FeeRecipient                solana.PublicKey    `bin:"fee_recipient"`
	InitialVirtualTokenReserves uint64              `bin:"initial_virtual_token_reserves"`
	InitialVirtualSolReserves   uint64              `bin:"initial_virtual_sol_reserves"`
	InitialRealTokenReserves    uint64              `bin:"initial_real_token_reserves"`
	TokenTotalSupply            uint64              `bin:"token_total_supply"`
	FeeBasisPoints              uint64              `bin:"fee_basis_points"`
	WithdrawAuthority           solana.PublicKey    `bin:"withdraw_authority"`
	EnableMigrate               bool                `bin:"enable_migrate"`
	PoolMigrationFee            uint64              `bin:"pool_migration_fee"`
	CreatorFeeBasisPoints       uint64              `bin:"creator_fee_basis_points"`
	FeeRecipients               [7]solana.PublicKey `bin:"fee_recipients"`
	SetCreatorAuthority         solana.PublicKey    `bin:"set_creator_authority"`
	AdminSetCreatorAuthority    solana.PublicKey    `bin:"admin_set_creator_authority"`
	CreateV2Enabled             bool                `bin:"create_v2_enabled"`
	WhitelistPda                solana.PublicKey    `bin:"whitelist_pda"`
	ReservedFeeRecipient        solana.PublicKey    `bin:"reserved_fee_recipient"`
	MayhemModeEnabled           bool                `bin:"mayhem_mode_enabled"`
	ReservedFeeRecipients       [7]solana.PublicKey `bin:"reserved_fee_recipients"`
	IsCashbackEnabled           bool                `bin:"is_cashback_enabled"`
	BuybackFeeRecipients        [8]solana.PublicKey `bin:"buyback_fee_recipients"`
	BuybackBasisPoints          uint64              `bin:"buyback_basis_points"`
	InitialVirtualQuoteReserves uint64              `bin:"initial_virtual_quote_reserves"`
	WhitelistedQuoteMints       [1]solana.PublicKey `bin:"whitelisted_quote_mints"`
}

type GlobalVolumeAccumulator struct {
	StartTime        int64            `bin:"start_time"`
	EndTime          int64            `bin:"end_time"`
	SecondsInADay    int64            `bin:"seconds_in_a_day"`
	Mint             solana.PublicKey `bin:"mint"`
	TotalTokenSupply [30]uint64       `bin:"total_token_supply"`
	SolVolumes       [30]uint64       `bin:"sol_volumes"`
}

type InitUserVolumeAccumulatorEvent struct {
	Payer     solana.PublicKey `bin:"payer"`
	User      solana.PublicKey `bin:"user"`
	Timestamp int64            `bin:"timestamp"`
}

type MigrateBondingCurveCreatorEvent struct {
	Timestamp     int64            `bin:"timestamp"`
	Mint          solana.PublicKey `bin:"mint"`
	BondingCurve  solana.PublicKey `bin:"bonding_curve"`
	SharingConfig solana.PublicKey `bin:"sharing_config"`
	OldCreator    solana.PublicKey `bin:"old_creator"`
	NewCreator    solana.PublicKey `bin:"new_creator"`
}

type MinimumDistributableFeeEvent struct {
	MinimumRequired   uint64 `bin:"minimum_required"`
	DistributableFees uint64 `bin:"distributable_fees"`
	CanDistribute     bool   `bin:"can_distribute"`
}

type OptionBool struct {
	Field0 bool `bin:"Field0"`
}

type ReservedFeeRecipientsEvent struct {
	Timestamp             int64               `bin:"timestamp"`
	ReservedFeeRecipient  solana.PublicKey    `bin:"reserved_fee_recipient"`
	ReservedFeeRecipients [7]solana.PublicKey `bin:"reserved_fee_recipients"`
}

type SetCreatorEvent struct {
	Timestamp    int64            `bin:"timestamp"`
	Mint         solana.PublicKey `bin:"mint"`
	BondingCurve solana.PublicKey `bin:"bonding_curve"`
	Creator      solana.PublicKey `bin:"creator"`
}

type SetMetaplexCreatorEvent struct {
	Timestamp    int64            `bin:"timestamp"`
	Mint         solana.PublicKey `bin:"mint"`
	BondingCurve solana.PublicKey `bin:"bonding_curve"`
	Metadata     solana.PublicKey `bin:"metadata"`
	Creator      solana.PublicKey `bin:"creator"`
}

type SetParamsEvent struct {
	InitialVirtualTokenReserves uint64              `bin:"initial_virtual_token_reserves"`
	InitialVirtualSolReserves   uint64              `bin:"initial_virtual_sol_reserves"`
	InitialRealTokenReserves    uint64              `bin:"initial_real_token_reserves"`
	FinalRealSolReserves        uint64              `bin:"final_real_sol_reserves"`
	TokenTotalSupply            uint64              `bin:"token_total_supply"`
	FeeBasisPoints              uint64              `bin:"fee_basis_points"`
	WithdrawAuthority           solana.PublicKey    `bin:"withdraw_authority"`
	EnableMigrate               bool                `bin:"enable_migrate"`
	PoolMigrationFee            uint64              `bin:"pool_migration_fee"`
	CreatorFeeBasisPoints       uint64              `bin:"creator_fee_basis_points"`
	FeeRecipients               [8]solana.PublicKey `bin:"fee_recipients"`
	Timestamp                   int64               `bin:"timestamp"`
	SetCreatorAuthority         solana.PublicKey    `bin:"set_creator_authority"`
	AdminSetCreatorAuthority    solana.PublicKey    `bin:"admin_set_creator_authority"`
}

type Shareholder struct {
	Address  solana.PublicKey `bin:"address"`
	ShareBps uint16           `bin:"share_bps"`
}

type SharingConfig struct {
	Bump         uint8            `bin:"bump"`
	Version      uint8            `bin:"version"`
	Status       ConfigStatus     `bin:"status"`
	Mint         solana.PublicKey `bin:"mint"`
	Admin        solana.PublicKey `bin:"admin"`
	AdminRevoked bool             `bin:"admin_revoked"`
	Shareholders []Shareholder    `bin:"shareholders"`
}

type SyncUserVolumeAccumulatorEvent struct {
	User                     solana.PublicKey `bin:"user"`
	TotalClaimedTokensBefore uint64           `bin:"total_claimed_tokens_before"`
	TotalClaimedTokensAfter  uint64           `bin:"total_claimed_tokens_after"`
	Timestamp                int64            `bin:"timestamp"`
}

type TradeEvent struct {
	Mint                   solana.PublicKey `bin:"mint"`
	SolAmount              uint64           `bin:"sol_amount"`
	TokenAmount            uint64           `bin:"token_amount"`
	IsBuy                  bool             `bin:"is_buy"`
	User                   solana.PublicKey `bin:"user"`
	Timestamp              int64            `bin:"timestamp"`
	VirtualSolReserves     uint64           `bin:"virtual_sol_reserves"`
	VirtualTokenReserves   uint64           `bin:"virtual_token_reserves"`
	RealSolReserves        uint64           `bin:"real_sol_reserves"`
	RealTokenReserves      uint64           `bin:"real_token_reserves"`
	FeeRecipient           solana.PublicKey `bin:"fee_recipient"`
	FeeBasisPoints         uint64           `bin:"fee_basis_points"`
	Fee                    uint64           `bin:"fee"`
	Creator                solana.PublicKey `bin:"creator"`
	CreatorFeeBasisPoints  uint64           `bin:"creator_fee_basis_points"`
	CreatorFee             uint64           `bin:"creator_fee"`
	TrackVolume            bool             `bin:"track_volume"`
	TotalUnclaimedTokens   uint64           `bin:"total_unclaimed_tokens"`
	TotalClaimedTokens     uint64           `bin:"total_claimed_tokens"`
	CurrentSolVolume       uint64           `bin:"current_sol_volume"`
	LastUpdateTimestamp    int64            `bin:"last_update_timestamp"`
	IxName                 string           `bin:"ix_name"`
	MayhemMode             bool             `bin:"mayhem_mode"`
	CashbackFeeBasisPoints uint64           `bin:"cashback_fee_basis_points"`
	Cashback               uint64           `bin:"cashback"`
	BuybackFeeBasisPoints  uint64           `bin:"buyback_fee_basis_points"`
	BuybackFee             uint64           `bin:"buyback_fee"`
	Shareholders           []Shareholder    `bin:"shareholders"`
	QuoteMint              solana.PublicKey `bin:"quote_mint"`
	QuoteAmount            uint64           `bin:"quote_amount"`
	VirtualQuoteReserves   uint64           `bin:"virtual_quote_reserves"`
	RealQuoteReserves      uint64           `bin:"real_quote_reserves"`
}

type UpdateGlobalAuthorityEvent struct {
	Global       solana.PublicKey `bin:"global"`
	Authority    solana.PublicKey `bin:"authority"`
	NewAuthority solana.PublicKey `bin:"new_authority"`
	Timestamp    int64            `bin:"timestamp"`
}

type UpdateMayhemVirtualParamsEvent struct {
	Timestamp               int64            `bin:"timestamp"`
	Mint                    solana.PublicKey `bin:"mint"`
	VirtualTokenReserves    uint64           `bin:"virtual_token_reserves"`
	VirtualSolReserves      uint64           `bin:"virtual_sol_reserves"`
	NewVirtualTokenReserves uint64           `bin:"new_virtual_token_reserves"`
	NewVirtualSolReserves   uint64           `bin:"new_virtual_sol_reserves"`
	RealTokenReserves       uint64           `bin:"real_token_reserves"`
	RealSolReserves         uint64           `bin:"real_sol_reserves"`
}

type UserVolumeAccumulator struct {
	User                       solana.PublicKey `bin:"user"`
	NeedsClaim                 bool             `bin:"needs_claim"`
	TotalUnclaimedTokens       uint64           `bin:"total_unclaimed_tokens"`
	TotalClaimedTokens         uint64           `bin:"total_claimed_tokens"`
	CurrentSolVolume           uint64           `bin:"current_sol_volume"`
	LastUpdateTimestamp        int64            `bin:"last_update_timestamp"`
	HasTotalClaimedTokens      bool             `bin:"has_total_claimed_tokens"`
	CashbackEarned             uint64           `bin:"cashback_earned"`
	TotalCashbackClaimed       uint64           `bin:"total_cashback_claimed"`
	StableCashbackEarned       uint64           `bin:"stable_cashback_earned"`
	TotalStableCashbackClaimed uint64           `bin:"total_stable_cashback_claimed"`
}
