// Code generated by internal/gen; DO NOT EDIT.
// Generated at 2025-12-07T17:54:49Z

package pumpfees

import (
	"bytes"
	"fmt"

	bin "github.com/gagliardetto/binary"
	"github.com/gagliardetto/solana-go"
)

var FeeConfigDiscriminator = []byte{143, 52, 146, 187, 219, 123, 76, 155}

func (a *FeeConfig) Unmarshal(data []byte) error {
	if len(data) < 8 {
		return fmt.Errorf("account FeeConfig: data too short")
	}
	if !bytes.Equal(data[:8], FeeConfigDiscriminator) {
		return fmt.Errorf("account FeeConfig: discriminator mismatch")
	}
	dec := bin.NewBorshDecoder(data[8:])
	return dec.Decode(a)
}

func (a *FeeConfig) Address(pubkey solana.PublicKey) solana.PublicKey {
	return pubkey
}
