// Code generated by internal/gen; DO NOT EDIT.

package pumpfees

import (
	"bytes"
	"fmt"

	bin "github.com/gagliardetto/binary"
	"github.com/gagliardetto/solana-go"
)

var BondingCurveDiscriminator = []byte{23, 183, 248, 55, 96, 216, 172, 96}

func (a *BondingCurve) Unmarshal(data []byte) error {
	if len(data) < 8 {
		return fmt.Errorf("account BondingCurve: data too short")
	}
	if !bytes.Equal(data[:8], BondingCurveDiscriminator) {
		return fmt.Errorf("account BondingCurve: discriminator mismatch")
	}
	dec := bin.NewBorshDecoder(data[8:])
	return dec.Decode(a)
}

func (a *BondingCurve) Address(pubkey solana.PublicKey) solana.PublicKey {
	return pubkey
}

var BuybackVaultDiscriminator = []byte{153, 166, 71, 144, 179, 189, 137, 251}

func (a *BuybackVault) Unmarshal(data []byte) error {
	if len(data) < 8 {
		return fmt.Errorf("account BuybackVault: data too short")
	}
	if !bytes.Equal(data[:8], BuybackVaultDiscriminator) {
		return fmt.Errorf("account BuybackVault: discriminator mismatch")
	}
	dec := bin.NewBorshDecoder(data[8:])
	return dec.Decode(a)
}

func (a *BuybackVault) Address(pubkey solana.PublicKey) solana.PublicKey {
	return pubkey
}

var DonationFeePdaDiscriminator = []byte{246, 197, 96, 9, 193, 30, 93, 115}

func (a *DonationFeePda) Unmarshal(data []byte) error {
	if len(data) < 8 {
		return fmt.Errorf("account DonationFeePda: data too short")
	}
	if !bytes.Equal(data[:8], DonationFeePdaDiscriminator) {
		return fmt.Errorf("account DonationFeePda: discriminator mismatch")
	}
	dec := bin.NewBorshDecoder(data[8:])
	return dec.Decode(a)
}

func (a *DonationFeePda) Address(pubkey solana.PublicKey) solana.PublicKey {
	return pubkey
}

var FeeConfigDiscriminator = []byte{143, 52, 146, 187, 219, 123, 76, 155}

func (a *FeeConfig) Unmarshal(data []byte) error {
	if len(data) < 8 {
		return fmt.Errorf("account FeeConfig: data too short")
	}
	if !bytes.Equal(data[:8], FeeConfigDiscriminator) {
		return fmt.Errorf("account FeeConfig: discriminator mismatch")
	}
	dec := bin.NewBorshDecoder(data[8:])
	return dec.Decode(a)
}

func (a *FeeConfig) Address(pubkey solana.PublicKey) solana.PublicKey {
	return pubkey
}

var FeeProgramGlobalDiscriminator = []byte{162, 165, 245, 49, 29, 37, 55, 242}

func (a *FeeProgramGlobal) Unmarshal(data []byte) error {
	if len(data) < 8 {
		return fmt.Errorf("account FeeProgramGlobal: data too short")
	}
	if !bytes.Equal(data[:8], FeeProgramGlobalDiscriminator) {
		return fmt.Errorf("account FeeProgramGlobal: discriminator mismatch")
	}
	dec := bin.NewBorshDecoder(data[8:])
	return dec.Decode(a)
}

func (a *FeeProgramGlobal) Address(pubkey solana.PublicKey) solana.PublicKey {
	return pubkey
}

var GlobalDiscriminator = []byte{167, 232, 232, 177, 200, 108, 114, 127}

func (a *Global) Unmarshal(data []byte) error {
	if len(data) < 8 {
		return fmt.Errorf("account Global: data too short")
	}
	if !bytes.Equal(data[:8], GlobalDiscriminator) {
		return fmt.Errorf("account Global: discriminator mismatch")
	}
	dec := bin.NewBorshDecoder(data[8:])
	return dec.Decode(a)
}

func (a *Global) Address(pubkey solana.PublicKey) solana.PublicKey {
	return pubkey
}

var PoolDiscriminator = []byte{241, 154, 109, 4, 17, 177, 109, 188}

func (a *Pool) Unmarshal(data []byte) error {
	if len(data) < 8 {
		return fmt.Errorf("account Pool: data too short")
	}
	if !bytes.Equal(data[:8], PoolDiscriminator) {
		return fmt.Errorf("account Pool: discriminator mismatch")
	}
	dec := bin.NewBorshDecoder(data[8:])
	return dec.Decode(a)
}

func (a *Pool) Address(pubkey solana.PublicKey) solana.PublicKey {
	return pubkey
}

var SharingConfigDiscriminator = []byte{216, 74, 9, 0, 56, 140, 93, 75}

func (a *SharingConfig) Unmarshal(data []byte) error {
	if len(data) < 8 {
		return fmt.Errorf("account SharingConfig: data too short")
	}
	if !bytes.Equal(data[:8], SharingConfigDiscriminator) {
		return fmt.Errorf("account SharingConfig: discriminator mismatch")
	}
	dec := bin.NewBorshDecoder(data[8:])
	return dec.Decode(a)
}

func (a *SharingConfig) Address(pubkey solana.PublicKey) solana.PublicKey {
	return pubkey
}

var SocialFeePdaDiscriminator = []byte{139, 96, 53, 17, 42, 169, 206, 150}

func (a *SocialFeePda) Unmarshal(data []byte) error {
	if len(data) < 8 {
		return fmt.Errorf("account SocialFeePda: data too short")
	}
	if !bytes.Equal(data[:8], SocialFeePdaDiscriminator) {
		return fmt.Errorf("account SocialFeePda: discriminator mismatch")
	}
	dec := bin.NewBorshDecoder(data[8:])
	return dec.Decode(a)
}

func (a *SocialFeePda) Address(pubkey solana.PublicKey) solana.PublicKey {
	return pubkey
}
