// Code generated by internal/gen; DO NOT EDIT.
// Generated at 2025-12-07T17:54:49Z

package pumpfees

type ProgramError struct {
	Code uint32
	Name string
	Msg  string
}

var Errors = map[uint32]ProgramError{
	6000: {Code: 6000, Name: "UnauthorizedProgram", Msg: "Only Pump and PumpSwap programs can call this instruction"},
	6001: {Code: 6001, Name: "InvalidAdmin", Msg: "Invalid admin"},
	6002: {Code: 6002, Name: "NoFeeTiers", Msg: "No fee tiers provided"},
	6003: {Code: 6003, Name: "TooManyFeeTiers", Msg: "format"},
	6004: {Code: 6004, Name: "OffsetNotContinuous", Msg: "The offset should be <= fee_config.fee_tiers.len()"},
	6005: {Code: 6005, Name: "FeeTiersNotSorted", Msg: "Fee tiers must be sorted by market cap threshold (ascending)"},
	6006: {Code: 6006, Name: "InvalidFeeTotal", Msg: "Fee total must not exceed 10_000bps"},
	6007: {Code: 6007, Name: "ZeroMarketCap", Msg: "Market cap must be greater than 0"},
	6008: {Code: 6008, Name: "ZeroTradeSize", Msg: "Trade size must be greater than 0"},
}

func ErrorFromCode(code uint32) (ProgramError, bool) {
	err, ok := Errors[code]
	return err, ok
}
