// Code generated by internal/gen; DO NOT EDIT.

package pumpfees

type ProgramError struct {
	Code uint32
	Name string
	Msg  string
}

var Errors = map[uint32]ProgramError{
	6000: {Code: 6000, Name: "UnauthorizedProgram", Msg: "Only Pump and PumpSwap programs can call this instruction"},
	6001: {Code: 6001, Name: "InvalidAdmin", Msg: "Invalid admin"},
	6002: {Code: 6002, Name: "NoFeeTiers", Msg: "No fee tiers provided"},
	6003: {Code: 6003, Name: "TooManyFeeTiers", Msg: "format"},
	6004: {Code: 6004, Name: "OffsetNotContinuous", Msg: "The offset should be <= fee_config.fee_tiers.len()"},
	6005: {Code: 6005, Name: "FeeTiersNotSorted", Msg: "Fee tiers must be sorted by market cap threshold (ascending)"},
	6006: {Code: 6006, Name: "InvalidFeeTotal", Msg: "Fee total must not exceed 10_000bps"},
	6007: {Code: 6007, Name: "InvalidSharingConfig", Msg: "Invalid Sharing Config"},
	6008: {Code: 6008, Name: "InvalidPool", Msg: "Invalid Pool"},
	6009: {Code: 6009, Name: "SharingConfigAdminRevoked", Msg: "Sharing config authority has been revoked - sharing config can only be updated once"},
	6010: {Code: 6010, Name: "NoShareholders", Msg: "No shareholders provided"},
	6011: {Code: 6011, Name: "TooManyShareholders", Msg: "format"},
	6012: {Code: 6012, Name: "DuplicateShareholder", Msg: "Duplicate shareholder address"},
	6013: {Code: 6013, Name: "NotEnoughRemainingAccounts", Msg: "Not enough remaining accounts"},
	6014: {Code: 6014, Name: "InvalidShareTotal", Msg: "Invalid share total - must equal 10_000 basis points"},
	6015: {Code: 6015, Name: "ShareCalculationOverflow", Msg: "Share calculation overflow"},
	6016: {Code: 6016, Name: "NotAuthorized", Msg: "The given account is not authorized to execute this instruction."},
	6017: {Code: 6017, Name: "ZeroShareNotAllowed", Msg: "Shareholder cannot have zero share"},
	6018: {Code: 6018, Name: "SharingConfigNotActive", Msg: "Fee sharing config is not active"},
	6019: {Code: 6019, Name: "AmmAccountsRequiredForGraduatedCoin", Msg: "AMM accounts are required for graduated coins"},
	6020: {Code: 6020, Name: "ShareholderAccountMismatch", Msg: "Remaining account key doesn't match shareholder address"},
	6021: {Code: 6021, Name: "FeatureDeactivated", Msg: "Feature is currently deactivated"},
	6022: {Code: 6022, Name: "UserIdTooLong", Msg: "User ID exceeds maximum length"},
	6023: {Code: 6023, Name: "DeprecatedInstruction", Msg: "Instruction is deprecated"},
	6024: {Code: 6024, Name: "FeeSharesAlreadyUpdated", Msg: "Reward split can only be updated once"},
	6025: {Code: 6025, Name: "MathOverflow", Msg: "Math overflow"},
	6026: {Code: 6026, Name: "InvalidBuybackIndex", Msg: "Invalid buybackindex"},
	6027: {Code: 6027, Name: "ClaimRateLimitExceeded", Msg: "Claim rate limit exceeded"},
	6028: {Code: 6028, Name: "InvalidFeeConfigAccount", Msg: "Account is not a valid FeeConfig for this instruction"},
	6029: {Code: 6029, Name: "AccountTypeNotSupported", Msg: "Account type not supported"},
	6030: {Code: 6030, Name: "InvalidMint", Msg: "Mint does not match quote mint"},
	6031: {Code: 6031, Name: "UnsupportedQuoteMint", Msg: "Unsupported quote mint"},
}

func ErrorFromCode(code uint32) (ProgramError, bool) {
	err, ok := Errors[code]
	return err, ok
}
