// Code generated by internal/gen; DO NOT EDIT.
// Generated at 2025-12-07T17:54:49Z

package pumpfees

import (
	"bytes"
	"fmt"

	bin "github.com/gagliardetto/binary"
	"github.com/gagliardetto/solana-go"
)

var GetFeesDiscriminator = []byte{231, 37, 126, 85, 207, 91, 63, 52}

type GetFeesArgs struct {
	IsPumpPool        bool        `bin:"is_pump_pool"`
	MarketCapLamports bin.Uint128 `bin:"market_cap_lamports"`
	TradeSizeLamports uint64      `bin:"trade_size_lamports"`
}

type GetFeesAccounts struct {
	FeeConfig       solana.PublicKey
	ConfigProgramId solana.PublicKey
}

func (a GetFeesAccounts) ToAccountMetas() []*solana.AccountMeta {
	metas := make([]*solana.AccountMeta, 0, 2)
	metas = append(metas, solana.NewAccountMeta(a.FeeConfig, false, false))
	metas = append(metas, solana.NewAccountMeta(a.ConfigProgramId, false, false))
	return metas
}

func BuildGetFees(accounts GetFeesAccounts, args GetFeesArgs) (solana.Instruction, error) {
	buf := bytes.NewBuffer(make([]byte, 0, 128))
	buf.Write(GetFeesDiscriminator)
	if err := bin.NewBorshEncoder(buf).Encode(args); err != nil {
		return nil, fmt.Errorf("encode args: %w", err)
	}
	data := buf.Bytes()
	return solana.NewInstruction(ProgramKey, accounts.ToAccountMetas(), data), nil
}

func DeriveGetFeesFeeConfigPDA(accounts GetFeesAccounts, args GetFeesArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 2)
	seeds = append(seeds, []byte{102, 101, 101, 95, 99, 111, 110, 102, 105, 103})
	seeds = append(seeds, accounts.ConfigProgramId[:])
	return solana.FindProgramAddress(seeds, ProgramKey)
}

var InitializeFeeConfigDiscriminator = []byte{62, 162, 20, 133, 121, 65, 145, 27}

type InitializeFeeConfigArgs struct{}

type InitializeFeeConfigAccounts struct {
	Admin           solana.PublicKey
	FeeConfig       solana.PublicKey
	SystemProgram   solana.PublicKey
	ConfigProgramId solana.PublicKey
	EventAuthority  solana.PublicKey
	Program         solana.PublicKey
}

func (a InitializeFeeConfigAccounts) ToAccountMetas() []*solana.AccountMeta {
	metas := make([]*solana.AccountMeta, 0, 6)
	var defaultInitializeFeeConfigAdmin = func() solana.PublicKey {
		return solana.MustPublicKeyFromBase58("8LWu7QM2dGR1G8nKDHthckea57bkCzXyBTAKPJUBDHo8")
	}

	metas = append(metas, solana.NewAccountMeta(defaultInitializeFeeConfigAdmin(), true, false))
	metas = append(metas, solana.NewAccountMeta(a.FeeConfig, true, false))
	var defaultInitializeFeeConfigSystemProgram = func() solana.PublicKey {
		return solana.MustPublicKeyFromBase58("11111111111111111111111111111111")
	}

	metas = append(metas, solana.NewAccountMeta(defaultInitializeFeeConfigSystemProgram(), false, false))
	metas = append(metas, solana.NewAccountMeta(a.ConfigProgramId, false, false))
	metas = append(metas, solana.NewAccountMeta(a.EventAuthority, false, false))
	metas = append(metas, solana.NewAccountMeta(a.Program, false, false))
	return metas
}

func BuildInitializeFeeConfig(accounts InitializeFeeConfigAccounts, args InitializeFeeConfigArgs) (solana.Instruction, error) {
	buf := bytes.NewBuffer(make([]byte, 0, 128))
	buf.Write(InitializeFeeConfigDiscriminator)
	data := buf.Bytes()
	return solana.NewInstruction(ProgramKey, accounts.ToAccountMetas(), data), nil
}

func DeriveInitializeFeeConfigFeeConfigPDA(accounts InitializeFeeConfigAccounts, args InitializeFeeConfigArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 2)
	seeds = append(seeds, []byte{102, 101, 101, 95, 99, 111, 110, 102, 105, 103})
	seeds = append(seeds, accounts.ConfigProgramId[:])
	return solana.FindProgramAddress(seeds, ProgramKey)
}

func DeriveInitializeFeeConfigEventAuthorityPDA(accounts InitializeFeeConfigAccounts, args InitializeFeeConfigArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 1)
	seeds = append(seeds, []byte{95, 95, 101, 118, 101, 110, 116, 95, 97, 117, 116, 104, 111, 114, 105, 116, 121})
	return solana.FindProgramAddress(seeds, ProgramKey)
}

var UpdateAdminDiscriminator = []byte{161, 176, 40, 213, 60, 184, 179, 228}

type UpdateAdminArgs struct{}

type UpdateAdminAccounts struct {
	Admin           solana.PublicKey
	FeeConfig       solana.PublicKey
	NewAdmin        solana.PublicKey
	ConfigProgramId solana.PublicKey
	EventAuthority  solana.PublicKey
	Program         solana.PublicKey
}

func (a UpdateAdminAccounts) ToAccountMetas() []*solana.AccountMeta {
	metas := make([]*solana.AccountMeta, 0, 6)
	metas = append(metas, solana.NewAccountMeta(a.Admin, false, true))
	metas = append(metas, solana.NewAccountMeta(a.FeeConfig, true, false))
	metas = append(metas, solana.NewAccountMeta(a.NewAdmin, false, false))
	metas = append(metas, solana.NewAccountMeta(a.ConfigProgramId, false, false))
	metas = append(metas, solana.NewAccountMeta(a.EventAuthority, false, false))
	metas = append(metas, solana.NewAccountMeta(a.Program, false, false))
	return metas
}

func BuildUpdateAdmin(accounts UpdateAdminAccounts, args UpdateAdminArgs) (solana.Instruction, error) {
	buf := bytes.NewBuffer(make([]byte, 0, 128))
	buf.Write(UpdateAdminDiscriminator)
	data := buf.Bytes()
	return solana.NewInstruction(ProgramKey, accounts.ToAccountMetas(), data), nil
}

func DeriveUpdateAdminFeeConfigPDA(accounts UpdateAdminAccounts, args UpdateAdminArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 2)
	seeds = append(seeds, []byte{102, 101, 101, 95, 99, 111, 110, 102, 105, 103})
	seeds = append(seeds, accounts.ConfigProgramId[:])
	return solana.FindProgramAddress(seeds, ProgramKey)
}

func DeriveUpdateAdminEventAuthorityPDA(accounts UpdateAdminAccounts, args UpdateAdminArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 1)
	seeds = append(seeds, []byte{95, 95, 101, 118, 101, 110, 116, 95, 97, 117, 116, 104, 111, 114, 105, 116, 121})
	return solana.FindProgramAddress(seeds, ProgramKey)
}

var UpdateFeeConfigDiscriminator = []byte{104, 184, 103, 242, 88, 151, 107, 20}

type UpdateFeeConfigArgs struct {
	FeeTiers []FeeTier `bin:"fee_tiers"`
	FlatFees Fees      `bin:"flat_fees"`
}

type UpdateFeeConfigAccounts struct {
	FeeConfig       solana.PublicKey
	Admin           solana.PublicKey
	ConfigProgramId solana.PublicKey
	EventAuthority  solana.PublicKey
	Program         solana.PublicKey
}

func (a UpdateFeeConfigAccounts) ToAccountMetas() []*solana.AccountMeta {
	metas := make([]*solana.AccountMeta, 0, 5)
	metas = append(metas, solana.NewAccountMeta(a.FeeConfig, true, false))
	metas = append(metas, solana.NewAccountMeta(a.Admin, false, true))
	metas = append(metas, solana.NewAccountMeta(a.ConfigProgramId, false, false))
	metas = append(metas, solana.NewAccountMeta(a.EventAuthority, false, false))
	metas = append(metas, solana.NewAccountMeta(a.Program, false, false))
	return metas
}

func BuildUpdateFeeConfig(accounts UpdateFeeConfigAccounts, args UpdateFeeConfigArgs) (solana.Instruction, error) {
	buf := bytes.NewBuffer(make([]byte, 0, 128))
	buf.Write(UpdateFeeConfigDiscriminator)
	if err := bin.NewBorshEncoder(buf).Encode(args); err != nil {
		return nil, fmt.Errorf("encode args: %w", err)
	}
	data := buf.Bytes()
	return solana.NewInstruction(ProgramKey, accounts.ToAccountMetas(), data), nil
}

func DeriveUpdateFeeConfigFeeConfigPDA(accounts UpdateFeeConfigAccounts, args UpdateFeeConfigArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 2)
	seeds = append(seeds, []byte{102, 101, 101, 95, 99, 111, 110, 102, 105, 103})
	seeds = append(seeds, accounts.ConfigProgramId[:])
	return solana.FindProgramAddress(seeds, ProgramKey)
}

func DeriveUpdateFeeConfigEventAuthorityPDA(accounts UpdateFeeConfigAccounts, args UpdateFeeConfigArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 1)
	seeds = append(seeds, []byte{95, 95, 101, 118, 101, 110, 116, 95, 97, 117, 116, 104, 111, 114, 105, 116, 121})
	return solana.FindProgramAddress(seeds, ProgramKey)
}

var UpsertFeeTiersDiscriminator = []byte{227, 23, 150, 12, 77, 86, 94, 4}

type UpsertFeeTiersArgs struct {
	FeeTiers []FeeTier `bin:"fee_tiers"`
	Offset   uint8     `bin:"offset"`
}

type UpsertFeeTiersAccounts struct {
	FeeConfig       solana.PublicKey
	Admin           solana.PublicKey
	ConfigProgramId solana.PublicKey
	EventAuthority  solana.PublicKey
	Program         solana.PublicKey
}

func (a UpsertFeeTiersAccounts) ToAccountMetas() []*solana.AccountMeta {
	metas := make([]*solana.AccountMeta, 0, 5)
	metas = append(metas, solana.NewAccountMeta(a.FeeConfig, true, false))
	metas = append(metas, solana.NewAccountMeta(a.Admin, false, true))
	metas = append(metas, solana.NewAccountMeta(a.ConfigProgramId, false, false))
	metas = append(metas, solana.NewAccountMeta(a.EventAuthority, false, false))
	metas = append(metas, solana.NewAccountMeta(a.Program, false, false))
	return metas
}

func BuildUpsertFeeTiers(accounts UpsertFeeTiersAccounts, args UpsertFeeTiersArgs) (solana.Instruction, error) {
	buf := bytes.NewBuffer(make([]byte, 0, 128))
	buf.Write(UpsertFeeTiersDiscriminator)
	if err := bin.NewBorshEncoder(buf).Encode(args); err != nil {
		return nil, fmt.Errorf("encode args: %w", err)
	}
	data := buf.Bytes()
	return solana.NewInstruction(ProgramKey, accounts.ToAccountMetas(), data), nil
}

func DeriveUpsertFeeTiersFeeConfigPDA(accounts UpsertFeeTiersAccounts, args UpsertFeeTiersArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 2)
	seeds = append(seeds, []byte{102, 101, 101, 95, 99, 111, 110, 102, 105, 103})
	seeds = append(seeds, accounts.ConfigProgramId[:])
	return solana.FindProgramAddress(seeds, ProgramKey)
}

func DeriveUpsertFeeTiersEventAuthorityPDA(accounts UpsertFeeTiersAccounts, args UpsertFeeTiersArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 1)
	seeds = append(seeds, []byte{95, 95, 101, 118, 101, 110, 116, 95, 97, 117, 116, 104, 111, 114, 105, 116, 121})
	return solana.FindProgramAddress(seeds, ProgramKey)
}
