// Code generated by internal/gen; DO NOT EDIT.
// Generated at 2025-12-07T17:54:49Z

package pumpfees

import "github.com/gagliardetto/solana-go"

const ProgramID string = "pfeeUxB6jkeY1Hxd7CsFCAjcbHA9rWtchMGdZ6VojVZ"
const ProgramName string = "pump_fees"
const ProgramVersion string = "0.1.0"

var ProgramKey = solana.MustPublicKeyFromBase58(ProgramID)
