// Code generated by internal/gen; DO NOT EDIT.
// Generated at 2025-12-07T17:54:49Z

package pumpfees

import (
	bin "github.com/gagliardetto/binary"
	"github.com/gagliardetto/solana-go"
)

type FeeConfig struct {
	Bump     uint8            `bin:"bump"`
	Admin    solana.PublicKey `bin:"admin"`
	FlatFees Fees             `bin:"flat_fees"`
	FeeTiers []FeeTier        `bin:"fee_tiers"`
}

type FeeTier struct {
	MarketCapLamportsThreshold bin.Uint128 `bin:"market_cap_lamports_threshold"`
	Fees                       Fees        `bin:"fees"`
}

type Fees struct {
	LpFeeBps       uint64 `bin:"lp_fee_bps"`
	ProtocolFeeBps uint64 `bin:"protocol_fee_bps"`
	CreatorFeeBps  uint64 `bin:"creator_fee_bps"`
}

type InitializeFeeConfigEvent struct {
	Timestamp int64            `bin:"timestamp"`
	Admin     solana.PublicKey `bin:"admin"`
	FeeConfig solana.PublicKey `bin:"fee_config"`
}

type UpdateAdminEvent struct {
	Timestamp int64            `bin:"timestamp"`
	OldAdmin  solana.PublicKey `bin:"old_admin"`
	NewAdmin  solana.PublicKey `bin:"new_admin"`
}

type UpdateFeeConfigEvent struct {
	Timestamp int64            `bin:"timestamp"`
	Admin     solana.PublicKey `bin:"admin"`
	FeeConfig solana.PublicKey `bin:"fee_config"`
	FeeTiers  []FeeTier        `bin:"fee_tiers"`
	FlatFees  Fees             `bin:"flat_fees"`
}

type UpsertFeeTiersEvent struct {
	Timestamp int64            `bin:"timestamp"`
	Admin     solana.PublicKey `bin:"admin"`
	FeeConfig solana.PublicKey `bin:"fee_config"`
	FeeTiers  []FeeTier        `bin:"fee_tiers"`
	Offset    uint8            `bin:"offset"`
}
