// Code generated by internal/gen; DO NOT EDIT.

package pumpfees

import (
	bin "github.com/gagliardetto/binary"
	"github.com/gagliardetto/solana-go"
)

type BondingCurve struct {
	VirtualTokenReserves uint64           `bin:"virtual_token_reserves"`
	VirtualQuoteReserves uint64           `bin:"virtual_quote_reserves"`
	RealTokenReserves    uint64           `bin:"real_token_reserves"`
	RealQuoteReserves    uint64           `bin:"real_quote_reserves"`
	TokenTotalSupply     uint64           `bin:"token_total_supply"`
	Complete             bool             `bin:"complete"`
	Creator              solana.PublicKey `bin:"creator"`
	IsMayhemMode         bool             `bin:"is_mayhem_mode"`
}

type BuybackVault struct {
	Authority          solana.PublicKey `bin:"authority"`
	TotalClaimed       uint64           `bin:"total_claimed"`
	TotalClaimedToken1 uint64           `bin:"total_claimed_token1"`
	TotalClaimedToken2 uint64           `bin:"total_claimed_token2"`
	LastClaimed        int64            `bin:"last_claimed"`
	ClaimRateLimit     int64            `bin:"claim_rate_limit"`
	Reserved           [128]uint8       `bin:"_reserved"`
}

type ConfigStatus uint8

const (
	ConfigStatusPaused ConfigStatus = iota
	ConfigStatusActive
)

type CreateFeeSharingConfigEvent struct {
	Timestamp           int64             `bin:"timestamp"`
	Mint                solana.PublicKey  `bin:"mint"`
	BondingCurve        solana.PublicKey  `bin:"bonding_curve"`
	Pool                *solana.PublicKey `bin:"pool optional"`
	SharingConfig       solana.PublicKey  `bin:"sharing_config"`
	Admin               solana.PublicKey  `bin:"admin"`
	InitialShareholders []Shareholder     `bin:"initial_shareholders"`
	Status              ConfigStatus      `bin:"status"`
}

type DonationFeePda struct {
	Bump         uint8            `bin:"bump"`
	Version      uint8            `bin:"version"`
	ConfigId     solana.PublicKey `bin:"config_id"`
	BaseMint     solana.PublicKey `bin:"base_mint"`
	QuoteMint    solana.PublicKey `bin:"quote_mint"`
	Creator      solana.PublicKey `bin:"creator"`
	TotalDonated uint64           `bin:"total_donated"`
	LastCrankTs  int64            `bin:"last_crank_ts"`
	Reserved     [64]uint8        `bin:"_reserved"`
}

type DonationFeePdaCranked struct {
	Timestamp      int64            `bin:"timestamp"`
	Signer         solana.PublicKey `bin:"signer"`
	DonationFeePda solana.PublicKey `bin:"donation_fee_pda"`
	ConfigId       solana.PublicKey `bin:"config_id"`
	BaseMint       solana.PublicKey `bin:"base_mint"`
	QuoteMint      solana.PublicKey `bin:"quote_mint"`
	Creator        solana.PublicKey `bin:"creator"`
	Amount         uint64           `bin:"amount"`
}

type DonationFeePdaCreated struct {
	Timestamp      int64            `bin:"timestamp"`
	CreatedBy      solana.PublicKey `bin:"created_by"`
	DonationFeePda solana.PublicKey `bin:"donation_fee_pda"`
	ConfigId       solana.PublicKey `bin:"config_id"`
	BaseMint       solana.PublicKey `bin:"base_mint"`
	QuoteMint      solana.PublicKey `bin:"quote_mint"`
	Creator        solana.PublicKey `bin:"creator"`
}

type ExtendFeeConfigEvent struct {
	FeeConfig   solana.PublicKey `bin:"fee_config"`
	User        solana.PublicKey `bin:"user"`
	CurrentSize uint64           `bin:"current_size"`
	NewSize     uint64           `bin:"new_size"`
	Timestamp   int64            `bin:"timestamp"`
}

type FeeConfig struct {
	Bump           uint8            `bin:"bump"`
	Admin          solana.PublicKey `bin:"admin"`
	FlatFees       Fees             `bin:"flat_fees"`
	FeeTiers       []FeeTier        `bin:"fee_tiers"`
	StableFeeTiers []FeeTier        `bin:"stable_fee_tiers"`
}

type FeeProgramGlobal struct {
	Bump                 uint8            `bin:"bump"`
	Authority            solana.PublicKey `bin:"authority"`
	DisableFlags         uint8            `bin:"disable_flags"`
	SocialClaimAuthority solana.PublicKey `bin:"social_claim_authority"`
	ClaimRateLimit       uint64           `bin:"claim_rate_limit"`
	Reserved             [256]uint8       `bin:"_reserved"`
}

type FeeTier struct {
	MarketCapLamportsThreshold bin.Uint128 `bin:"market_cap_lamports_threshold"`
	Fees                       Fees        `bin:"fees"`
}

type Fees struct {
	LpFeeBps       uint64 `bin:"lp_fee_bps"`
	ProtocolFeeBps uint64 `bin:"protocol_fee_bps"`
	CreatorFeeBps  uint64 `bin:"creator_fee_bps"`
}

type Global struct {
	Initialized                 bool                `bin:"initialized"`
	Authority                   solana.PublicKey    `bin:"authority"`
	FeeRecipient                solana.PublicKey    `bin:"fee_recipient"`
	InitialVirtualTokenReserves uint64              `bin:"initial_virtual_token_reserves"`
	InitialVirtualSolReserves   uint64              `bin:"initial_virtual_sol_reserves"`
	InitialRealTokenReserves    uint64              `bin:"initial_real_token_reserves"`
	TokenTotalSupply            uint64              `bin:"token_total_supply"`
	FeeBasisPoints              uint64              `bin:"fee_basis_points"`
	WithdrawAuthority           solana.PublicKey    `bin:"withdraw_authority"`
	EnableMigrate               bool                `bin:"enable_migrate"`
	PoolMigrationFee            uint64              `bin:"pool_migration_fee"`
	CreatorFeeBasisPoints       uint64              `bin:"creator_fee_basis_points"`
	FeeRecipients               [7]solana.PublicKey `bin:"fee_recipients"`
	SetCreatorAuthority         solana.PublicKey    `bin:"set_creator_authority"`
	AdminSetCreatorAuthority    solana.PublicKey    `bin:"admin_set_creator_authority"`
	CreateV2Enabled             bool                `bin:"create_v2_enabled"`
	WhitelistPda                solana.PublicKey    `bin:"whitelist_pda"`
	ReservedFeeRecipient        solana.PublicKey    `bin:"reserved_fee_recipient"`
	MayhemModeEnabled           bool                `bin:"mayhem_mode_enabled"`
	ReservedFeeRecipients       [7]solana.PublicKey `bin:"reserved_fee_recipients"`
}

type InitializeFeeConfigEvent struct {
	Timestamp int64            `bin:"timestamp"`
	Admin     solana.PublicKey `bin:"admin"`
	FeeConfig solana.PublicKey `bin:"fee_config"`
}

type InitializeFeeProgramGlobalEvent struct {
	Timestamp            int64            `bin:"timestamp"`
	Authority            solana.PublicKey `bin:"authority"`
	SocialClaimAuthority solana.PublicKey `bin:"social_claim_authority"`
	DisableFlags         uint8            `bin:"disable_flags"`
	ClaimRateLimit       uint64           `bin:"claim_rate_limit"`
}

type OptionBool struct {
	Field0 bool `bin:"Field0"`
}

type Pool struct {
	PoolBump              uint8            `bin:"pool_bump"`
	Index                 uint16           `bin:"index"`
	Creator               solana.PublicKey `bin:"creator"`
	BaseMint              solana.PublicKey `bin:"base_mint"`
	QuoteMint             solana.PublicKey `bin:"quote_mint"`
	LpMint                solana.PublicKey `bin:"lp_mint"`
	PoolBaseTokenAccount  solana.PublicKey `bin:"pool_base_token_account"`
	PoolQuoteTokenAccount solana.PublicKey `bin:"pool_quote_token_account"`
	LpSupply              uint64           `bin:"lp_supply"`
	CoinCreator           solana.PublicKey `bin:"coin_creator"`
	IsMayhemMode          bool             `bin:"is_mayhem_mode"`
}

type ResetFeeSharingConfigEvent struct {
	Timestamp       int64            `bin:"timestamp"`
	Mint            solana.PublicKey `bin:"mint"`
	SharingConfig   solana.PublicKey `bin:"sharing_config"`
	OldAdmin        solana.PublicKey `bin:"old_admin"`
	OldShareholders []Shareholder    `bin:"old_shareholders"`
	NewAdmin        solana.PublicKey `bin:"new_admin"`
	NewShareholders []Shareholder    `bin:"new_shareholders"`
	OldVersion      uint8            `bin:"old_version"`
	NewVersion      uint8            `bin:"new_version"`
}

type SetAuthorityEvent struct {
	Timestamp    int64            `bin:"timestamp"`
	OldAuthority solana.PublicKey `bin:"old_authority"`
	NewAuthority solana.PublicKey `bin:"new_authority"`
}

type SetClaimRateLimitEvent struct {
	Timestamp      int64  `bin:"timestamp"`
	ClaimRateLimit uint64 `bin:"claim_rate_limit"`
}

type SetDisableFlagsEvent struct {
	Timestamp    int64 `bin:"timestamp"`
	DisableFlags uint8 `bin:"disable_flags"`
}

type SetSocialClaimAuthorityEvent struct {
	Timestamp            int64            `bin:"timestamp"`
	SocialClaimAuthority solana.PublicKey `bin:"social_claim_authority"`
}

type Shareholder struct {
	Address  solana.PublicKey `bin:"address"`
	ShareBps uint16           `bin:"share_bps"`
}

type SharingConfig struct {
	Bump         uint8            `bin:"bump"`
	Version      uint8            `bin:"version"`
	Status       ConfigStatus     `bin:"status"`
	Mint         solana.PublicKey `bin:"mint"`
	Admin        solana.PublicKey `bin:"admin"`
	AdminRevoked bool             `bin:"admin_revoked"`
	Shareholders []Shareholder    `bin:"shareholders"`
}

type SocialFeePda struct {
	Bump               uint8      `bin:"bump"`
	Version            uint8      `bin:"version"`
	UserId             string     `bin:"user_id"`
	Platform           uint8      `bin:"platform"`
	TotalClaimed       uint64     `bin:"total_claimed"`
	LastClaimed        uint64     `bin:"last_claimed"`
	TotalStableClaimed uint64     `bin:"total_stable_claimed"`
	Reserved           [120]uint8 `bin:"_reserved"`
}

type SocialFeePdaClaimed struct {
	Timestamp              int64            `bin:"timestamp"`
	UserId                 string           `bin:"user_id"`
	Platform               uint8            `bin:"platform"`
	SocialFeePda           solana.PublicKey `bin:"social_fee_pda"`
	Recipient              solana.PublicKey `bin:"recipient"`
	SocialClaimAuthority   solana.PublicKey `bin:"social_claim_authority"`
	AmountClaimed          uint64           `bin:"amount_claimed"`
	ClaimableBefore        uint64           `bin:"claimable_before"`
	LifetimeClaimed        uint64           `bin:"lifetime_claimed"`
	RecipientBalanceBefore uint64           `bin:"recipient_balance_before"`
	RecipientBalanceAfter  uint64           `bin:"recipient_balance_after"`
	QuoteMint              solana.PublicKey `bin:"quote_mint"`
	LifetimeStableClaimed  uint64           `bin:"lifetime_stable_claimed"`
}

type SocialFeePdaCreated struct {
	Timestamp    int64            `bin:"timestamp"`
	UserId       string           `bin:"user_id"`
	Platform     uint8            `bin:"platform"`
	SocialFeePda solana.PublicKey `bin:"social_fee_pda"`
	CreatedBy    solana.PublicKey `bin:"created_by"`
}

type SweepBuybackEvent struct {
	Index        uint8            `bin:"index"`
	SolAmount    uint64           `bin:"sol_amount"`
	TokenAmount  uint64           `bin:"token_amount"`
	Destination  solana.PublicKey `bin:"destination"`
	BuybackVault solana.PublicKey `bin:"buyback_vault"`
	Mint         solana.PublicKey `bin:"mint"`
}

type UpdateAdminEvent struct {
	Timestamp int64            `bin:"timestamp"`
	OldAdmin  solana.PublicKey `bin:"old_admin"`
	NewAdmin  solana.PublicKey `bin:"new_admin"`
}

type UpdateFeeConfigEvent struct {
	Timestamp int64            `bin:"timestamp"`
	Admin     solana.PublicKey `bin:"admin"`
	FeeConfig solana.PublicKey `bin:"fee_config"`
	FeeTiers  []FeeTier        `bin:"fee_tiers"`
	FlatFees  Fees             `bin:"flat_fees"`
}

type UpdateFeeSharesEvent struct {
	Timestamp       int64            `bin:"timestamp"`
	Mint            solana.PublicKey `bin:"mint"`
	SharingConfig   solana.PublicKey `bin:"sharing_config"`
	Admin           solana.PublicKey `bin:"admin"`
	NewShareholders []Shareholder    `bin:"new_shareholders"`
	Version         uint8            `bin:"version"`
}

type UpdateStableFeeConfigEvent struct {
	Timestamp      int64            `bin:"timestamp"`
	Admin          solana.PublicKey `bin:"admin"`
	FeeConfig      solana.PublicKey `bin:"fee_config"`
	StableFeeTiers []FeeTier        `bin:"stable_fee_tiers"`
	FlatFees       Fees             `bin:"flat_fees"`
}

type UpsertFeeTiersEvent struct {
	Timestamp int64            `bin:"timestamp"`
	Admin     solana.PublicKey `bin:"admin"`
	FeeConfig solana.PublicKey `bin:"fee_config"`
	FeeTiers  []FeeTier        `bin:"fee_tiers"`
	Offset    uint8            `bin:"offset"`
}

type UpsertStableFeeTiersEvent struct {
	Timestamp      int64            `bin:"timestamp"`
	Admin          solana.PublicKey `bin:"admin"`
	FeeConfig      solana.PublicKey `bin:"fee_config"`
	StableFeeTiers []FeeTier        `bin:"stable_fee_tiers"`
	Offset         uint8            `bin:"offset"`
}
